<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Descripción de datos | EEBE Estadística</title>
  <meta name="description" content="EEBE" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Descripción de datos | EEBE Estadística" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="EEBE" />
  <meta name="github-repo" content="alejandro-isglobal/master" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Descripción de datos | EEBE Estadística" />
  
  <meta name="twitter:description" content="EEBE" />
  

<meta name="author" content="Alejandro Cáceres (alejandro.caceres.dominguez@upc.edu)" />


<meta name="date" content="2023-11-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="probabilidad.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística EEBE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Objetivo</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#lectura-recomendada"><i class="fa fa-check"></i><b>1.1</b> Lectura recomendada</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html"><i class="fa fa-check"></i><b>2</b> Descripción de datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#método-científico"><i class="fa fa-check"></i><b>2.1</b> Método científico</a></li>
<li class="chapter" data-level="2.2" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#estadística"><i class="fa fa-check"></i><b>2.2</b> Estadística</a></li>
<li class="chapter" data-level="2.3" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#datos"><i class="fa fa-check"></i><b>2.3</b> Datos</a></li>
<li class="chapter" data-level="2.4" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#tipos-de-resultado"><i class="fa fa-check"></i><b>2.4</b> Tipos de resultado</a></li>
<li class="chapter" data-level="2.5" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#experimentos-aleatorios"><i class="fa fa-check"></i><b>2.5</b> Experimentos aleatorios</a></li>
<li class="chapter" data-level="2.6" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#frecuencias-absolutas"><i class="fa fa-check"></i><b>2.6</b> Frecuencias absolutas</a></li>
<li class="chapter" data-level="2.7" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#frecuencias-relativas"><i class="fa fa-check"></i><b>2.7</b> Frecuencias relativas</a></li>
<li class="chapter" data-level="2.8" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#diagrama-de-barras"><i class="fa fa-check"></i><b>2.8</b> Diagrama de barras</a></li>
<li class="chapter" data-level="2.9" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#gráfico-de-sectores-pie"><i class="fa fa-check"></i><b>2.9</b> Gráfico de sectores (pie)</a></li>
<li class="chapter" data-level="2.10" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#variables-categóricas-ordinales"><i class="fa fa-check"></i><b>2.10</b> Variables categóricas ordinales</a></li>
<li class="chapter" data-level="2.11" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#frecuencias-acumuladas-absolutas-y-relativas"><i class="fa fa-check"></i><b>2.11</b> Frecuencias acumuladas absolutas y relativas</a></li>
<li class="chapter" data-level="2.12" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#gráfica-de-frecuencia-acumulada"><i class="fa fa-check"></i><b>2.12</b> Gráfica de frecuencia acumulada</a></li>
<li class="chapter" data-level="2.13" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#variables-numéricas"><i class="fa fa-check"></i><b>2.13</b> Variables numéricas</a></li>
<li class="chapter" data-level="2.14" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#transformando-datos-continuos"><i class="fa fa-check"></i><b>2.14</b> Transformando datos continuos</a></li>
<li class="chapter" data-level="2.15" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#tabla-de-frecuencias-para-una-variable-continua"><i class="fa fa-check"></i><b>2.15</b> Tabla de frecuencias para una variable continua</a></li>
<li class="chapter" data-level="2.16" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#histograma"><i class="fa fa-check"></i><b>2.16</b> Histograma</a></li>
<li class="chapter" data-level="2.17" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#gráfica-de-frecuencia-acumulada-1"><i class="fa fa-check"></i><b>2.17</b> Gráfica de frecuencia acumulada</a></li>
<li class="chapter" data-level="2.18" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#estadísticas-de-resumen"><i class="fa fa-check"></i><b>2.18</b> Estadísticas de resumen</a></li>
<li class="chapter" data-level="2.19" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#promedio-media-muestral"><i class="fa fa-check"></i><b>2.19</b> Promedio (media muestral)</a></li>
<li class="chapter" data-level="2.20" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#promedio"><i class="fa fa-check"></i><b>2.20</b> Promedio</a></li>
<li class="chapter" data-level="2.21" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#mediana"><i class="fa fa-check"></i><b>2.21</b> mediana</a></li>
<li class="chapter" data-level="2.22" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#dispersión"><i class="fa fa-check"></i><b>2.22</b> Dispersión</a></li>
<li class="chapter" data-level="2.23" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#variación-de-la-muestra"><i class="fa fa-check"></i><b>2.23</b> Variación de la muestra</a></li>
<li class="chapter" data-level="2.24" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#rango-intercuartílico-iqr"><i class="fa fa-check"></i><b>2.24</b> Rango intercuartílico (IQR)</a></li>
<li class="chapter" data-level="2.25" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#diagrama-de-caja"><i class="fa fa-check"></i><b>2.25</b> Diagrama de caja</a></li>
<li class="chapter" data-level="2.26" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#preguntas"><i class="fa fa-check"></i><b>2.26</b> Preguntas</a></li>
<li class="chapter" data-level="2.27" data-path="descripción-de-datos.html"><a href="descripción-de-datos.html#ejercicios"><i class="fa fa-check"></i><b>2.27</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>3</b> Probabilidad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probabilidad.html"><a href="probabilidad.html#experimentos-aleatorios-1"><i class="fa fa-check"></i><b>3.1</b> Experimentos aleatorios</a></li>
<li class="chapter" data-level="3.2" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-de-medición"><i class="fa fa-check"></i><b>3.2</b> Probabilidad de medición</a></li>
<li class="chapter" data-level="3.3" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-clásica"><i class="fa fa-check"></i><b>3.3</b> Probabilidad clásica</a></li>
<li class="chapter" data-level="3.4" data-path="probabilidad.html"><a href="probabilidad.html#frecuencias-relativas-1"><i class="fa fa-check"></i><b>3.4</b> Frecuencias relativas</a></li>
<li class="chapter" data-level="3.5" data-path="probabilidad.html"><a href="probabilidad.html#frecuencias-relativas-en-el-infinito"><i class="fa fa-check"></i><b>3.5</b> Frecuencias relativas en el infinito</a></li>
<li class="chapter" data-level="3.6" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-frecuentista"><i class="fa fa-check"></i><b>3.6</b> Probabilidad frecuentista</a></li>
<li class="chapter" data-level="3.7" data-path="probabilidad.html"><a href="probabilidad.html#probabilidades-clásicas-y-frecuentistas"><i class="fa fa-check"></i><b>3.7</b> Probabilidades clásicas y frecuentistas</a></li>
<li class="chapter" data-level="3.8" data-path="probabilidad.html"><a href="probabilidad.html#definición-de-probabilidad"><i class="fa fa-check"></i><b>3.8</b> Definición de probabilidad</a></li>
<li class="chapter" data-level="3.9" data-path="probabilidad.html"><a href="probabilidad.html#tabla-de-probabilidades"><i class="fa fa-check"></i><b>3.9</b> Tabla de probabilidades</a></li>
<li class="chapter" data-level="3.10" data-path="probabilidad.html"><a href="probabilidad.html#espacio-muestral"><i class="fa fa-check"></i><b>3.10</b> Espacio muestral</a></li>
<li class="chapter" data-level="3.11" data-path="probabilidad.html"><a href="probabilidad.html#eventos"><i class="fa fa-check"></i><b>3.11</b> Eventos</a></li>
<li class="chapter" data-level="3.12" data-path="probabilidad.html"><a href="probabilidad.html#álgebra-de-eventos"><i class="fa fa-check"></i><b>3.12</b> Álgebra de eventos</a></li>
<li class="chapter" data-level="3.13" data-path="probabilidad.html"><a href="probabilidad.html#resultados-mutuamente-excluyentes"><i class="fa fa-check"></i><b>3.13</b> Resultados mutuamente excluyentes</a></li>
<li class="chapter" data-level="3.14" data-path="probabilidad.html"><a href="probabilidad.html#probabilidades-conjuntas"><i class="fa fa-check"></i><b>3.14</b> Probabilidades conjuntas</a></li>
<li class="chapter" data-level="3.15" data-path="probabilidad.html"><a href="probabilidad.html#tabla-de-contingencia"><i class="fa fa-check"></i><b>3.15</b> Tabla de contingencia</a></li>
<li class="chapter" data-level="3.16" data-path="probabilidad.html"><a href="probabilidad.html#la-regla-de-la-suma"><i class="fa fa-check"></i><b>3.16</b> La regla de la suma:</a></li>
<li class="chapter" data-level="3.17" data-path="probabilidad.html"><a href="probabilidad.html#preguntas-1"><i class="fa fa-check"></i><b>3.17</b> Preguntas</a></li>
<li class="chapter" data-level="3.18" data-path="probabilidad.html"><a href="probabilidad.html#ejercicios-1"><i class="fa fa-check"></i><b>3.18</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html"><i class="fa fa-check"></i><b>4</b> Probabilidad condicional</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#probabilidad-conjunta"><i class="fa fa-check"></i><b>4.1</b> Probabilidad conjunta</a></li>
<li class="chapter" data-level="4.2" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#independencia-estadística"><i class="fa fa-check"></i><b>4.2</b> Independencia estadística</a></li>
<li class="chapter" data-level="4.3" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#la-probabilidad-condicional"><i class="fa fa-check"></i><b>4.3</b> La probabilidad condicional</a></li>
<li class="chapter" data-level="4.4" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#tabla-de-contingencia-condicional"><i class="fa fa-check"></i><b>4.4</b> Tabla de contingencia condicional</a></li>
<li class="chapter" data-level="4.5" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#independencia-estadística-1"><i class="fa fa-check"></i><b>4.5</b> Independencia estadística</a></li>
<li class="chapter" data-level="4.6" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#dependencia-estadística"><i class="fa fa-check"></i><b>4.6</b> Dependencia estadística</a></li>
<li class="chapter" data-level="4.7" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#prueba-de-diagnóstico"><i class="fa fa-check"></i><b>4.7</b> Prueba de diagnóstico</a></li>
<li class="chapter" data-level="4.8" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#probabilidades-inversas"><i class="fa fa-check"></i><b>4.8</b> Probabilidades inversas</a></li>
<li class="chapter" data-level="4.9" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#teorema-de-bayes"><i class="fa fa-check"></i><b>4.9</b> Teorema de Bayes</a></li>
<li class="chapter" data-level="4.10" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#preguntas-2"><i class="fa fa-check"></i><b>4.10</b> Preguntas</a></li>
<li class="chapter" data-level="4.11" data-path="probabilidad-condicional.html"><a href="probabilidad-condicional.html#ejercicios-2"><i class="fa fa-check"></i><b>4.11</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html"><i class="fa fa-check"></i><b>5</b> Variables aleatorias discretas</a>
<ul>
<li class="chapter" data-level="5.1" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#objetivo-1"><i class="fa fa-check"></i><b>5.1</b> Objetivo</a></li>
<li class="chapter" data-level="5.2" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#frecuencias-relativas-2"><i class="fa fa-check"></i><b>5.2</b> Frecuencias relativas</a></li>
<li class="chapter" data-level="5.3" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#variable-aleatoria"><i class="fa fa-check"></i><b>5.3</b> Variable aleatoria</a></li>
<li class="chapter" data-level="5.4" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#eventos-de-observar-una-variable-aleatoria"><i class="fa fa-check"></i><b>5.4</b> Eventos de observar una variable aleatoria</a></li>
<li class="chapter" data-level="5.5" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#probabilidad-de-variables-aleatorias"><i class="fa fa-check"></i><b>5.5</b> Probabilidad de variables aleatorias</a></li>
<li class="chapter" data-level="5.6" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#funciones-de-probabilidad"><i class="fa fa-check"></i><b>5.6</b> Funciones de probabilidad</a></li>
<li class="chapter" data-level="5.7" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#funciones-de-probabilidad-1"><i class="fa fa-check"></i><b>5.7</b> Funciones de probabilidad</a></li>
<li class="chapter" data-level="5.8" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#probabilidades-y-frecuencias-relativas"><i class="fa fa-check"></i><b>5.8</b> Probabilidades y frecuencias relativas</a></li>
<li class="chapter" data-level="5.9" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#la-media-o-el-valor-esperado"><i class="fa fa-check"></i><b>5.9</b> La media o el valor esperado</a></li>
<li class="chapter" data-level="5.10" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#varianza"><i class="fa fa-check"></i><b>5.10</b> Varianza</a></li>
<li class="chapter" data-level="5.11" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#funciones-de-probabilidad-para-funciones-de-x"><i class="fa fa-check"></i><b>5.11</b> Funciones de probabilidad para funciones de <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="5.12" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#distribución-de-probabilidad"><i class="fa fa-check"></i><b>5.12</b> Distribución de probabilidad</a></li>
<li class="chapter" data-level="5.13" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#función-de-probabilidad-y-distribución-de-probabilidad"><i class="fa fa-check"></i><b>5.13</b> Función de probabilidad y distribución de probabilidad</a></li>
<li class="chapter" data-level="5.14" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#cuantiles"><i class="fa fa-check"></i><b>5.14</b> Cuantiles</a></li>
<li class="chapter" data-level="5.15" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#resumen"><i class="fa fa-check"></i><b>5.15</b> Resumen</a></li>
<li class="chapter" data-level="5.16" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#preguntas-3"><i class="fa fa-check"></i><b>5.16</b> Preguntas</a></li>
<li class="chapter" data-level="5.17" data-path="variables-aleatorias-discretas.html"><a href="variables-aleatorias-discretas.html#ejercicios-3"><i class="fa fa-check"></i><b>5.17</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html"><i class="fa fa-check"></i><b>6</b> Variables aleatorias continuas</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#objetivo-2"><i class="fa fa-check"></i><b>6.1</b> Objetivo</a></li>
<li class="chapter" data-level="6.2" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#variables-aleatorias-continuas-1"><i class="fa fa-check"></i><b>6.2</b> Variables aleatorias continuas</a></li>
<li class="chapter" data-level="6.3" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#frecuencias-relativas-3"><i class="fa fa-check"></i><b>6.3</b> frecuencias relativas</a></li>
<li class="chapter" data-level="6.4" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#función-de-densidad-de-probabilidad"><i class="fa fa-check"></i><b>6.4</b> función de densidad de probabilidad</a></li>
<li class="chapter" data-level="6.5" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#área-total-bajo-la-curva"><i class="fa fa-check"></i><b>6.5</b> Área total bajo la curva</a></li>
<li class="chapter" data-level="6.6" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#probabilidades-de-variables-continuas"><i class="fa fa-check"></i><b>6.6</b> Probabilidades de variables continuas</a></li>
<li class="chapter" data-level="6.7" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#distribución-de-probabilidad-1"><i class="fa fa-check"></i><b>6.7</b> Distribución de probabilidad</a></li>
<li class="chapter" data-level="6.8" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#gráficas-de-probabilidad"><i class="fa fa-check"></i><b>6.8</b> Gráficas de probabilidad</a></li>
<li class="chapter" data-level="6.9" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#media"><i class="fa fa-check"></i><b>6.9</b> Media</a></li>
<li class="chapter" data-level="6.10" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#varianza-1"><i class="fa fa-check"></i><b>6.10</b> Varianza</a></li>
<li class="chapter" data-level="6.11" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#funciones-de-x"><i class="fa fa-check"></i><b>6.11</b> Funciones de <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="6.12" data-path="variables-aleatorias-continuas.html"><a href="variables-aleatorias-continuas.html#ejercicios-4"><i class="fa fa-check"></i><b>6.12</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><i class="fa fa-check"></i><b>7</b> Modelos de probabilidad para variables aletorias discretas</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#objetivo-3"><i class="fa fa-check"></i><b>7.1</b> Objetivo</a></li>
<li class="chapter" data-level="7.2" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#función-de-probabilidad"><i class="fa fa-check"></i><b>7.2</b> Función de probabilidad</a></li>
<li class="chapter" data-level="7.3" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#modelo-de-probabilidad"><i class="fa fa-check"></i><b>7.3</b> Modelo de probabilidad</a></li>
<li class="chapter" data-level="7.4" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#modelos-paramétricos"><i class="fa fa-check"></i><b>7.4</b> Modelos paramétricos</a></li>
<li class="chapter" data-level="7.5" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#distribución-uniforme-un-parámetro"><i class="fa fa-check"></i><b>7.5</b> Distribución uniforme (un parámetro)</a></li>
<li class="chapter" data-level="7.6" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#distribución-uniforme-dos-parámetros"><i class="fa fa-check"></i><b>7.6</b> Distribución uniforme (dos parámetros)</a></li>
<li class="chapter" data-level="7.7" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#ensayo-de-bernoulli"><i class="fa fa-check"></i><b>7.7</b> Ensayo de Bernoulli</a></li>
<li class="chapter" data-level="7.8" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#experimento-binomial"><i class="fa fa-check"></i><b>7.8</b> Experimento binomial</a></li>
<li class="chapter" data-level="7.9" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#función-de-probabilidad-binomial"><i class="fa fa-check"></i><b>7.9</b> Función de probabilidad binomial</a></li>
<li class="chapter" data-level="7.10" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#función-de-probabilidad-binomial-negativa"><i class="fa fa-check"></i><b>7.10</b> Función de probabilidad binomial negativa</a></li>
<li class="chapter" data-level="7.11" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#distribución-geométrica"><i class="fa fa-check"></i><b>7.11</b> Distribución geométrica</a></li>
<li class="chapter" data-level="7.12" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#modelo-hipergeométrico"><i class="fa fa-check"></i><b>7.12</b> Modelo hipergeométrico</a></li>
<li class="chapter" data-level="7.13" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#preguntas-4"><i class="fa fa-check"></i><b>7.13</b> Preguntas</a></li>
<li class="chapter" data-level="7.14" data-path="modelos-de-probabilidad-para-variables-aletorias-discretas.html"><a href="modelos-de-probabilidad-para-variables-aletorias-discretas.html#ejercicios-5"><i class="fa fa-check"></i><b>7.14</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html"><i class="fa fa-check"></i><b>8</b> Modelos de Poisson y Exponencial</a>
<ul>
<li class="chapter" data-level="8.1" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#objetivo-4"><i class="fa fa-check"></i><b>8.1</b> Objetivo</a></li>
<li class="chapter" data-level="8.2" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#modelos-de-probabilidad-para-variables-discretas"><i class="fa fa-check"></i><b>8.2</b> Modelos de probabilidad para variables discretas</a></li>
<li class="chapter" data-level="8.3" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#experimento-de-poissson"><i class="fa fa-check"></i><b>8.3</b> Experimento de Poissson</a></li>
<li class="chapter" data-level="8.4" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#función-de-masa-de-probabilidad-de-poisson"><i class="fa fa-check"></i><b>8.4</b> Función de masa de probabilidad de Poisson</a></li>
<li class="chapter" data-level="8.5" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#modelos-de-probabilidad-para-variables-continuas"><i class="fa fa-check"></i><b>8.5</b> Modelos de probabilidad para variables continuas</a></li>
<li class="chapter" data-level="8.6" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#experimento-exponencial"><i class="fa fa-check"></i><b>8.6</b> Experimento exponencial</a></li>
<li class="chapter" data-level="8.7" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#densidad-de-probabilidad-exponencial"><i class="fa fa-check"></i><b>8.7</b> Densidad de probabilidad exponencial</a></li>
<li class="chapter" data-level="8.8" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#distribución-exponencial"><i class="fa fa-check"></i><b>8.8</b> Distribución exponencial</a></li>
<li class="chapter" data-level="8.9" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#preguntas-5"><i class="fa fa-check"></i><b>8.9</b> Preguntas</a></li>
<li class="chapter" data-level="8.10" data-path="modelos-de-poisson-y-exponencial.html"><a href="modelos-de-poisson-y-exponencial.html#ejercicios-6"><i class="fa fa-check"></i><b>8.10</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="distribución-normal.html"><a href="distribución-normal.html"><i class="fa fa-check"></i><b>9</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="9.1" data-path="distribución-normal.html"><a href="distribución-normal.html#objetivo-5"><i class="fa fa-check"></i><b>9.1</b> Objetivo</a></li>
<li class="chapter" data-level="9.2" data-path="distribución-normal.html"><a href="distribución-normal.html#historia"><i class="fa fa-check"></i><b>9.2</b> Historia</a></li>
<li class="chapter" data-level="9.3" data-path="distribución-normal.html"><a href="distribución-normal.html#densidad-normal"><i class="fa fa-check"></i><b>9.3</b> Densidad normal</a></li>
<li class="chapter" data-level="9.4" data-path="distribución-normal.html"><a href="distribución-normal.html#definición"><i class="fa fa-check"></i><b>9.4</b> Definición</a></li>
<li class="chapter" data-level="9.5" data-path="distribución-normal.html"><a href="distribución-normal.html#distribución-de-probabilidad-2"><i class="fa fa-check"></i><b>9.5</b> Distribución de probabilidad</a></li>
<li class="chapter" data-level="9.6" data-path="distribución-normal.html"><a href="distribución-normal.html#densidad-normal-estándar"><i class="fa fa-check"></i><b>9.6</b> Densidad normal estándar</a></li>
<li class="chapter" data-level="9.7" data-path="distribución-normal.html"><a href="distribución-normal.html#distribución-estándar"><i class="fa fa-check"></i><b>9.7</b> Distribución estándar</a></li>
<li class="chapter" data-level="9.8" data-path="distribución-normal.html"><a href="distribución-normal.html#estandarización"><i class="fa fa-check"></i><b>9.8</b> Estandarización</a></li>
<li class="chapter" data-level="9.9" data-path="distribución-normal.html"><a href="distribución-normal.html#resumen-de-modelos-de-probabilidad"><i class="fa fa-check"></i><b>9.9</b> Resumen de modelos de probabilidad</a></li>
<li class="chapter" data-level="9.10" data-path="distribución-normal.html"><a href="distribución-normal.html#funciones-r-de-modelos-de-probabilidad"><i class="fa fa-check"></i><b>9.10</b> Funciones R de modelos de probabilidad</a></li>
<li class="chapter" data-level="9.11" data-path="distribución-normal.html"><a href="distribución-normal.html#preguntas-6"><i class="fa fa-check"></i><b>9.11</b> Preguntas</a></li>
<li class="chapter" data-level="9.12" data-path="distribución-normal.html"><a href="distribución-normal.html#ejercicios-7"><i class="fa fa-check"></i><b>9.12</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html"><i class="fa fa-check"></i><b>10</b> Distribuciones de muestreo</a>
<ul>
<li class="chapter" data-level="10.1" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#objetivo-6"><i class="fa fa-check"></i><b>10.1</b> Objetivo</a></li>
<li class="chapter" data-level="10.2" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#muestra-aleatoria"><i class="fa fa-check"></i><b>10.2</b> Muestra aleatoria</a></li>
<li class="chapter" data-level="10.3" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#cálculo-de-probabilidades"><i class="fa fa-check"></i><b>10.3</b> Cálculo de probabilidades</a></li>
<li class="chapter" data-level="10.4" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#estimación-de-los-parámetros"><i class="fa fa-check"></i><b>10.4</b> Estimación de los parámetros</a></li>
<li class="chapter" data-level="10.5" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#margen-de-error-de-las-estimaciones"><i class="fa fa-check"></i><b>10.5</b> Margen de error de las estimaciones</a></li>
<li class="chapter" data-level="10.6" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#inferencia"><i class="fa fa-check"></i><b>10.6</b> Inferencia</a></li>
<li class="chapter" data-level="10.7" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#distribución-media-muestral"><i class="fa fa-check"></i><b>10.7</b> Distribución media muestral</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#suma-muestral"><i class="fa fa-check"></i><b>10.7.1</b> Suma muestral</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#variaza-muestral"><i class="fa fa-check"></i><b>10.8</b> Variaza muestral</a></li>
<li class="chapter" data-level="10.9" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#probabilidades-de-la-varianza-muestral"><i class="fa fa-check"></i><b>10.9</b> Probabilidades de la varianza muestral</a></li>
<li class="chapter" data-level="10.10" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#chi2-estadística"><i class="fa fa-check"></i><b>10.10</b> <span class="math inline">\(\chi^2\)</span>-estadística</a></li>
<li class="chapter" data-level="10.11" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#preguntas-7"><i class="fa fa-check"></i><b>10.11</b> Preguntas</a></li>
<li class="chapter" data-level="10.12" data-path="distribuciones-de-muestreo.html"><a href="distribuciones-de-muestreo.html#ejercicios-8"><i class="fa fa-check"></i><b>10.12</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html"><i class="fa fa-check"></i><b>11</b> Teorema central del límite</a>
<ul>
<li class="chapter" data-level="11.1" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html#objetivo-7"><i class="fa fa-check"></i><b>11.1</b> Objetivo</a></li>
<li class="chapter" data-level="11.2" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html#margen-de-error"><i class="fa fa-check"></i><b>11.2</b> Margen de error</a></li>
<li class="chapter" data-level="11.3" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html#ejemplo-cables"><i class="fa fa-check"></i><b>11.3</b> Ejemplo (cables)</a></li>
<li class="chapter" data-level="11.4" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html#teorema-central-del-límite-1"><i class="fa fa-check"></i><b>11.4</b> Teorema central del límite</a></li>
<li class="chapter" data-level="11.5" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html#suma-muestral-y-clt"><i class="fa fa-check"></i><b>11.5</b> Suma muestral y CLT</a></li>
<li class="chapter" data-level="11.6" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html#preguntas-8"><i class="fa fa-check"></i><b>11.6</b> Preguntas</a></li>
<li class="chapter" data-level="11.7" data-path="teorema-central-del-límite.html"><a href="teorema-central-del-límite.html#ejercicios-9"><i class="fa fa-check"></i><b>11.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html"><i class="fa fa-check"></i><b>12</b> Máxima verosimilitud y Método de los Momentos</a>
<ul>
<li class="chapter" data-level="12.1" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#objetivo-8"><i class="fa fa-check"></i><b>12.1</b> Objetivo</a></li>
<li class="chapter" data-level="12.2" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#estadística-1"><i class="fa fa-check"></i><b>12.2</b> Estadística</a></li>
<li class="chapter" data-level="12.3" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#propiedades"><i class="fa fa-check"></i><b>12.3</b> Propiedades</a></li>
<li class="chapter" data-level="12.4" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#máxima-verosimilitud"><i class="fa fa-check"></i><b>12.4</b> Máxima verosimilitud</a></li>
<li class="chapter" data-level="12.5" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#máxima-verosimilitud-1"><i class="fa fa-check"></i><b>12.5</b> Máxima verosimilitud</a></li>
<li class="chapter" data-level="12.6" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#método-de-los-momentos"><i class="fa fa-check"></i><b>12.6</b> Método de los Momentos</a></li>
<li class="chapter" data-level="12.7" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#método-de-momentos-para-varios-parámetros"><i class="fa fa-check"></i><b>12.7</b> Método de Momentos para varios parámetros</a></li>
<li class="chapter" data-level="12.8" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#preguntas-9"><i class="fa fa-check"></i><b>12.8</b> Preguntas</a></li>
<li class="chapter" data-level="12.9" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#ejercicios-10"><i class="fa fa-check"></i><b>12.9</b> Ejercicios</a></li>
<li class="chapter" data-level="12.10" data-path="máxima-verosimilitud-y-método-de-los-momentos.html"><a href="máxima-verosimilitud-y-método-de-los-momentos.html#método-de-los-momentos-1"><i class="fa fa-check"></i><b>12.10</b> Método de los momentos</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">EEBE Estadística</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descripción-de-datos" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Descripción de datos<a href="descripción-de-datos.html#descripción-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo, presentaremos herramientas para describir datos.</p>
<p>Lo haremos utilizando tablas, figuras y estadísticos descriptivos de tendencia central y dispersión.</p>
<p>También presentaremos conceptos clave en estadística como experimentos aleatorios, observaciones, resultados y frecuencias absolutas y relativas.</p>
<div id="método-científico" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Método científico<a href="descripción-de-datos.html#método-científico" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Uno de los objetivos del método científico es proporcionar un marco para resolver los problemas que surgen en el estudio de los fenómenos naturales o en el diseño de nuevas tecnologías.</p>
<p>Los humanos modernos han desarrollado un <strong>método</strong> durante miles de años que todavía está en desarrollo.</p>
<p>El método tiene tres actividades humanas principales:</p>
<ul>
<li><em>Observación</em> caracterizada por la adquisición de <strong>datos</strong></li>
<li><em>Razón</em> caracterizada por el desarrollo de <strong>modelos</strong> matemáticos</li>
<li><em>Acción</em> caracterizada por el desarrollo de nuevos <strong>experimentos</strong> (tecnología)</li>
</ul>
<p>Su compleja interacción y resultados son la base de la <em>actividad científica</em>.</p>
<p><img src="figures/stats.JPG" /></p>
</div>
<div id="estadística" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Estadística<a href="descripción-de-datos.html#estadística" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La estadística se ocupa de la interacción entre <em>modelos</em> y <em>datos</em> (la parte inferior de la figura).</p>
<p>Las preguntas de tipo estadístico son:</p>
<ul>
<li>¿Cuál es el mejor modelo para mis datos (inferencia)?</li>
<li>¿Cuáles son los datos que produciría un determinado modelo (predicción)?</li>
</ul>
</div>
<div id="datos" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Datos<a href="descripción-de-datos.html#datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Los datos se presentan en forma de observaciones.</p>
<p>Una <strong>Observación</strong> o <em>Realización</em> es la adquisición de un número o una característica de un experimento.</p>
<p>Por ejemplo, tomemos la serie de números que se producen por la repetición de un experimento (1: éxito, 0: fracaso)</p>
<p>… 1 0 0 1 0 <strong>1</strong> 0 1 1 …</p>
<p>El número en negrita es <strong>una observación</strong> en una repetición del experimento</p>
<p>Un <strong>resultado</strong> es una <strong>posible</strong> observación que es el resultado de un experimento.</p>
<p><strong>1</strong> es un resultado, <strong>0</strong> es el otro resultado del experimento.</p>
<p>Recuerda que la observación es <strong>concreta</strong> es el número que obtienes un día en el laboratorio. El resultado <strong>abstracto</strong> es una de las características del tipo de experimento que estás realizando.</p>
</div>
<div id="tipos-de-resultado" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Tipos de resultado<a href="descripción-de-datos.html#tipos-de-resultado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En estadística nos interesan principalmente dos tipos de resultados.</p>
<ul>
<li><p><strong>Categóricos</strong>: Si el resultado de un experimento es una cualidad. Pueden ser nominales (binario: sí, no; múltiple: colores) u ordinales cuando las cualidades pueden jerarquizarse (gravedad de una enfermedad).</p></li>
<li><p><strong>Numéricos</strong>: Si el resultado de un experimento es un número. El número puede ser discreto (número de correos electrónicos recibidos en una hora, número de leucocitos en sangre) o continuo (estado de carga de la batería, temperatura del motor).</p></li>
</ul>
</div>
<div id="experimentos-aleatorios" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Experimentos aleatorios<a href="descripción-de-datos.html#experimentos-aleatorios" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se puede decir que el tema de estudio de la estadística son los experimentos aleatorios, el medio por el cual producimos datos.</p>
<p><strong>Definición:</strong></p>
<p>Un <strong>experimento aleatorio</strong> es un experimento que da diferentes resultados cuando se repite de la misma manera.</p>
<p>Los experimentos aleatorios son de diferentes tipos, dependiendo de cómo se realicen:</p>
<ul>
<li>en el mismo objeto (persona): temperatura, niveles de azúcar.</li>
<li>sobre objetos diferentes pero de la misma medida: el peso de un animal.</li>
<li>sobre eventos: el número de huracanes por año.</li>
</ul>
</div>
<div id="frecuencias-absolutas" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Frecuencias absolutas<a href="descripción-de-datos.html#frecuencias-absolutas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cuando repetimos un experimento aleatorio con resultados <strong>categóricos</strong>, registramos una lista de resultados.</p>
<p>Resumimos las observaciones contando cuántas veces vimos un resultado particular.</p>
<p><strong>Frecuencia absoluta</strong>:</p>
<p><span class="math display">\[n_i\]</span></p>
<p>es el número de veces que observamos el resultado <span class="math inline">\(i\)</span>.</p>
<p><strong>Ejemplo (leucocitos)</strong></p>
<p>Extraigamos un leucocito de <strong>un</strong> donante y anotemos su tipo. Repitamos el experimento <span class="math inline">\(N=119\)</span> veces.</p>
<pre><code>(célula T, célula T, neutrófilo, ..., célula B)</code></pre>
<p>La segunda <strong>célula T</strong> en negrita es la segunda observación. La última <strong>célula B</strong> es la observación número 119.</p>
<p>Podemos listar los <strong>resultados</strong> (categorías) en una <strong>tabla de frecuencia</strong>:</p>
<pre><code>##      outcome ni
## 1     T Cell 34
## 2     B cell 50
## 3   basophil 20
## 4   Monocyte  5
## 5 Neutrophil 10</code></pre>
<p>De la tabla, podemos decir que, por ejemplo, <span class="math inline">\(n_1=34\)</span> es el número total de células T observadas en la repetición del experimento. También notamos que el número total de repeticiones <span class="math inline">\(N=\sum_i n_i=119\)</span>.</p>
</div>
<div id="frecuencias-relativas" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Frecuencias relativas<a href="descripción-de-datos.html#frecuencias-relativas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>También podemos resumir las observaciones calculando la <strong>proporción</strong> de cuántas veces vimos un resultado en particular.</p>
<p><span class="math display">\[f_i=n_i/N\]</span> donde <span class="math inline">\(N\)</span> es el número total de observaciones</p>
<p>En nuestro ejemplo se registraron <span class="math inline">\(n_1=34\)</span> células T, por lo que nos preguntamos por la proporción de células T del total de <span class="math inline">\(119\)</span>. Podemos agregar estas proporciones <span class="math inline">\(f_i\)</span> en la tabla las frecuencias.</p>
<pre><code>##      outcome ni         fi
## 1     T Cell 34 0.28571429
## 2     B cell 50 0.42016807
## 3   basophil 20 0.16806723
## 4   Monocyte  5 0.04201681
## 5 Neutrophil 10 0.08403361</code></pre>
<p>Las frecuencias relativas son <strong>fundamentales</strong> en estadística. Dan la proporción de un resultado en relación con los otros resultados. Más adelante las entenderemos como las observaciones de las probabilidades.</p>
<p>Para las frecuencias absolutas y relativas tenemos las propiedades</p>
<ul>
<li><span class="math inline">\(\sum_{i=1..M} n_i = N\)</span></li>
<li><span class="math inline">\(\sum_{i=1..M} f_i = 1\)</span></li>
</ul>
<p>donde <span class="math inline">\(M\)</span> es el número de resultados.</p>
</div>
<div id="diagrama-de-barras" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Diagrama de barras<a href="descripción-de-datos.html#diagrama-de-barras" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cuando tenemos muchos resultados y queremos ver cuáles son los más probables, podemos usar un gráfico de barras que es una cifra de <span class="math inline">\(n_i\)</span> Vs los resultados.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="gráfico-de-sectores-pie" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Gráfico de sectores (pie)<a href="descripción-de-datos.html#gráfico-de-sectores-pie" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>También podemos visualizar las frecuencias relativas con un gráfico de sectores.</p>
<p>El área del círculo representa el 100% de las observaciones (proporción = 1) y las secciones las frecuencias relativas de cada resultado.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="variables-categóricas-ordinales" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> Variables categóricas ordinales<a href="descripción-de-datos.html#variables-categóricas-ordinales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El tipo de leucocito de los ejemplos anteriores es una variable nominal <strong>categórica</strong>. Cada observación pertenece a una categoría (cualidad). Las categorías no siempre tienen un orden determindado.</p>
<p>A veces, las variables <strong>categóricas</strong> se pueden <strong>ordenar</strong> cuando cumplen una clasificación natural. Esto permite introducir <strong>frecuencias acumulativas</strong>.</p>
<p><strong>Ejemplo (misofonía)</strong></p>
<p>Este es un estudio clínico en 123 pacientes que fueron examinados por su grado de misofonía. La misofnía es ansiedad/ira descontrolada producida por ciertos sonidos.</p>
<p>Cada paciente fue evaluado con un cuestionario (AMISO) y se clasificaron en 4 grupos diferentes según la gravedad.</p>
<p>Los resultados del estudio son</p>
<pre><code>##   [1] 4 2 0 3 0 0 2 3 0 3 0 2 2 0 2 0 0 3 3 0 3 3 2 0 0 0 4 2 2 0 2 0 0 0 3 0 2
##  [38] 3 2 2 0 2 3 0 0 2 2 3 3 0 0 4 3 3 2 0 2 0 0 0 2 2 0 0 2 3 0 1 3 2 4 3 2 3
##  [75] 0 2 3 2 4 1 2 0 2 0 2 0 2 2 4 3 0 3 0 0 0 2 2 1 3 0 0 3 2 1 3 0 4 4 2 3 3
## [112] 3 0 3 2 1 2 3 3 4 2 3 2</code></pre>
<p>Cada observación es el resultado de un experimento aleatorio: medición del nivel de misofonía en un paciente. Esta serie de datos se puede resumir en términos de los resultados en la tabla de frecuencia</p>
<pre><code>##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073</code></pre>
</div>
<div id="frecuencias-acumuladas-absolutas-y-relativas" class="section level2 hasAnchor" number="2.11">
<h2><span class="header-section-number">2.11</span> Frecuencias acumuladas absolutas y relativas<a href="descripción-de-datos.html#frecuencias-acumuladas-absolutas-y-relativas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La gravedad de la misofonía es <strong>categórica</strong> <strong>ordinal</strong> porque sus resultados pueden ordenarse en relación con su grado.</p>
<p>Cuando los resultados se pueden ordenar, es útil preguntar cuántas observaciones se obtuvieron hasta un resultado dado. Llamamos a este número la <strong>frecuencia acumulada absoluta</strong> hasta el resultado <span class="math inline">\(i\)</span>:
<span class="math display">\[N_i=\sum_{k=1..i} n_k\]</span>
También es útil para calcular la <strong>proporción</strong> de las observaciones que se obtuvo hasta un resultado dado</p>
<p><span class="math display">\[F_i=\sum_{k=1..i} f_k\]</span></p>
<p>Podemos agregar estas frecuencias en la <strong>tabla de frecuencias</strong></p>
<pre><code>##   outcome ni         fi  Ni        Fi
## 0       0 41 0.33333333  41 0.3333333
## 1       1  5 0.04065041  46 0.3739837
## 2       2 37 0.30081301  83 0.6747967
## 3       3 31 0.25203252 114 0.9268293
## 4       4  9 0.07317073 123 1.0000000</code></pre>
<p>Por lo tanto, el <strong>67 %</strong> de los pacientes tenían misofonía hasta la gravedad <strong>2</strong> y el <strong>37 %</strong> de los pacientes tenían una gravedad inferior o igual a <strong>1</strong>.</p>
</div>
<div id="gráfica-de-frecuencia-acumulada" class="section level2 hasAnchor" number="2.12">
<h2><span class="header-section-number">2.12</span> Gráfica de frecuencia acumulada<a href="descripción-de-datos.html#gráfica-de-frecuencia-acumulada" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><span class="math inline">\(F_i\)</span> es una cantidad importante porque nos permite definir la acumulación de probabilidades hasta niveles intermedios.</p>
<p>La probabilidad de un nivel intermedio <span class="math inline">\(x\)</span> (<span class="math inline">\(i\leq x&lt; i+1\)</span>) es solo la acumulación hasta el nivel inferior <span class="math inline">\(F_x=F_i\)</span>.</p>
<p><span class="math inline">\(F_x\)</span> es por lo tanto una función de rango <strong>continuo</strong>. Podemos dibujarla con respecto a los resultados.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Por lo tanto, podemos decir que el <strong>67 %</strong> de los pacientes tenían misofonía hasta gravedad <span class="math inline">\(2.3\)</span>, aunque <span class="math inline">\(2.3\)</span> no es un resultado observado.</p>
</div>
<div id="variables-numéricas" class="section level2 hasAnchor" number="2.13">
<h2><span class="header-section-number">2.13</span> Variables numéricas<a href="descripción-de-datos.html#variables-numéricas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El resultado de un experimento aleatorio puede producir un número. Si el número es <strong>discreto</strong>, podemos generar una tabla de frecuencias, con frecuencias absolutas, relativas y acumulativas, e ilustrarlas con gráficos de barras, de sectores y acumulativos.</p>
<p>Cuando el número es <strong>continuo</strong> las frecuencias no son útiles, lo más probable es que observemos o no un número contínuo en particular.</p>
<p><strong>Ejemplo (misofonía)</strong></p>
<p>Los investigadores se preguntaron si la convexidad de la mandíbula afectaría la gravedad de la misofonía. La hipótesis científica es que el ángulo de convexidad de la mandíbula puede influir en el oído y su sensibilidad. Estos son los resultados de la convexidad de la mandíbula (grados) para cada paciente:</p>
<pre><code>##   [1]  7.97 18.23 12.27  7.81  9.81 13.50 19.30  7.70 12.30  7.90 12.60 19.00
##  [13]  7.27 14.00  5.40  8.00 11.20  7.75  7.94 16.69  7.62  7.02  7.00 19.20
##  [25]  7.96 14.70  7.24  7.80  7.90  4.70  4.40 14.00 14.40 16.00  1.40  9.76
##  [37]  7.90  7.90  7.40  6.30  7.76  7.30  7.00 11.23 16.00  7.90  7.29  6.91
##  [49]  7.10 13.40 11.60 -1.00  6.00  7.82  4.80 11.00  9.00 11.50 16.00 15.00
##  [61]  1.40 16.80  7.70 16.14  7.12 -1.00 17.00  9.26 18.70  3.40 21.30  7.50
##  [73]  6.03  7.50 19.00 19.01  8.10  7.80  6.10 15.26  7.95 18.00  4.60 15.00
##  [85]  7.50  8.00 16.80  8.54  7.00 18.30  7.80 16.00 14.00 12.30 11.40  8.50
##  [97]  7.00  7.96 17.60 10.00  3.50  6.70 17.00 20.26  6.64  1.80  7.02  2.46
## [109] 19.00 17.86  6.10  6.64 12.00  6.60  8.70 14.05  7.20 19.70  7.70  6.02
## [121]  2.50 19.00  6.80</code></pre>
</div>
<div id="transformando-datos-continuos" class="section level2 hasAnchor" number="2.14">
<h2><span class="header-section-number">2.14</span> Transformando datos continuos<a href="descripción-de-datos.html#transformando-datos-continuos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Como los resultados continuos no se pueden contar (de manera informativa), los transformamos en variables categóricas ordenadas.</p>
<ol style="list-style-type: decimal">
<li>Primero cubrimos el rango de las observaciones en intervalos regulares del mismo tamaño (contenedores)</li>
</ol>
<pre><code>## [1] &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Luego mapeamos cada observación a su intervalo: creando una variable categórica <strong>ordenada</strong>; en este caso con 5 resultados posibles</li>
</ol>
<pre><code>##   [1] &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot; 
##   [6] &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot; 
##  [11] &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [16] &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot; 
##  [21] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot; 
##  [26] &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [31] &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;[-1.02,3.46]&quot;
##  [36] &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [41] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot; 
##  [46] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot; 
##  [51] &quot;(7.92,12.4]&quot;  &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [56] &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot; 
##  [61] &quot;[-1.02,3.46]&quot; &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [66] &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;[-1.02,3.46]&quot;
##  [71] &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot; 
##  [76] &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot; 
##  [81] &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [86] &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot; 
##  [91] &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot; 
##  [96] &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot; 
## [101] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot; 
## [106] &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(16.8,21.3]&quot; 
## [111] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot; 
## [116] &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
## [121] &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;</code></pre>
<p>Por tanto, en lugar de decir que el primer paciente tenía un ángulo de convexidad de <span class="math inline">\(7.97\)</span>, decimos que su ángulo estaba entre el intervalo (o <strong>bin</strong>) <span class="math inline">\((7.92,12.4]\)</span>.</p>
<p>Ningún otro paciente tenía un ángulo de <span class="math inline">\(7.97\)</span>, pero muchos tenían ángulos entre <span class="math inline">\((7.92,12.4]\)</span>.</p>
</div>
<div id="tabla-de-frecuencias-para-una-variable-continua" class="section level2 hasAnchor" number="2.15">
<h2><span class="header-section-number">2.15</span> Tabla de frecuencias para una variable continua<a href="descripción-de-datos.html#tabla-de-frecuencias-para-una-variable-continua" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para una partición regular dada del intervalo de resultados en intervalos, podemos producir una tabla de frecuencias como antes</p>
<pre><code>##        outcome ni         fi  Ni         Fi
## 1 [-1.02,3.46]  8 0.06504065   8 0.06504065
## 2  (3.46,7.92] 51 0.41463415  59 0.47967480
## 3  (7.92,12.4] 26 0.21138211  85 0.69105691
## 4  (12.4,16.8] 20 0.16260163 105 0.85365854
## 5  (16.8,21.3] 18 0.14634146 123 1.00000000</code></pre>
</div>
<div id="histograma" class="section level2 hasAnchor" number="2.16">
<h2><span class="header-section-number">2.16</span> Histograma<a href="descripción-de-datos.html#histograma" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El histograma es la gráfica de <span class="math inline">\(n_i\)</span> o <span class="math inline">\(f_i\)</span> Vs los resultados en intervalos (bins). El histograma depende del tamaño de los bins.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Este es un histograma con 20 bins.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Vemos que la mayoría de las personas tienen ángulos dentro de <span class="math inline">\((7, 8]\)</span></p>
</div>
<div id="gráfica-de-frecuencia-acumulada-1" class="section level2 hasAnchor" number="2.17">
<h2><span class="header-section-number">2.17</span> Gráfica de frecuencia acumulada<a href="descripción-de-datos.html#gráfica-de-frecuencia-acumulada-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>También podemos graficar <span class="math inline">\(F_x\)</span> contra los resultados. Como <span class="math inline">\(F_x\)</span> es de rango continuo, podemos ordenar las observaciones (<span class="math inline">\(x_1 &lt;... x_j &lt; x_{j+1} &lt; x_n\)</span>) y por lo tanto</p>
<p><span class="math display">\[F_x = \frac{k}{n}\]</span></p>
<p>para <span class="math inline">\(x_{k} \leq x &lt; x_{k+1}\)</span>.</p>
<p><span class="math inline">\(F_x\)</span> se conoce como la <strong>distribución</strong> de los datos. <span class="math inline">\(F_x\)</span> no depende del tamaño del bin. Sin embargo, su <strong>resolución</strong> depende de la cantidad de datos.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="estadísticas-de-resumen" class="section level2 hasAnchor" number="2.18">
<h2><span class="header-section-number">2.18</span> Estadísticas de resumen<a href="descripción-de-datos.html#estadísticas-de-resumen" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las estadísticas de resumen son números calculados a partir de los datos que nos dicen características importantes de las variables numéricas (discretas o continuas).</p>
<p>Por ejemplo, tenemos estadísticas que describen los valores extremos:</p>
<ul>
<li><strong>mínimo</strong>: el resultado mínimo observado</li>
<li><strong>máximo</strong>: el resultado máximo observado</li>
</ul>
</div>
<div id="promedio-media-muestral" class="section level2 hasAnchor" number="2.19">
<h2><span class="header-section-number">2.19</span> Promedio (media muestral)<a href="descripción-de-datos.html#promedio-media-muestral" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Una estadística importante que describe el valor central de los resultados (dónde esperar la mayoría de las observaciones) es el <strong>promedio</strong></p>
<p><span class="math display">\[\bar{x}=\frac{1}{N} \sum_{j=1..N} x_j\]</span></p>
<p>donde <span class="math inline">\(x_j\)</span> es la <strong>observación</strong> <span class="math inline">\(j\)</span> de un total de <span class="math inline">\(N\)</span>.</p>
<p><strong>Ejemplo (Misofonía)</strong></p>
<p>La convexidad promedio se puede calcular directamente a partir de las <strong>observaciones</strong></p>
<p><span class="math inline">\(\bar{x}= \frac{1}{N}\sum_j x_j\)</span></p>
<p></br>
<span class="math inline">\(= \frac{1}{N}(7.97 + 18.23 + 12.27... + 6.80) = 10.19894\)</span></p>
<p>Para variables <strong>categóricamente ordenadas</strong>, podemos usar las frecuencias relativas para calcular el promedio</p>
<p><br>
<span class="math inline">\(\bar{x}=\frac{1}{N}\sum_{i=1...N} x_j=\frac{1}{N}\sum_{i=1...M} x_i*n_ {i}\)</span>
<br>
<span class="math display">\[=\sum_{i=1...M} x_i*f_{i}\]</span></p>
<p>donde pasamos de sumar <span class="math inline">\(N\)</span> <strong>observaciones</strong> a sumar <span class="math inline">\(M\)</span> <strong>resultados</strong>.</p>
<p>La forma <span class="math inline">\(\bar{x}= \sum_{i = 1...M} x_i f_i\)</span> muestra que el promedio es el <strong>centro de gravedad</strong> de los resultados. Como si cada resultado tuviera una densidad de masa dada por <span class="math inline">\(f_i\)</span>.</p>
<p><strong>Ejemplo (Misofonía)</strong></p>
<p>La <strong>severidad</strong> promedio de la misofonía en el estudio se puede calcular a partir de las frecuencias relativas de los <strong>resultados</strong></p>
<pre><code>##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073</code></pre>
<p><br>
<span class="math inline">\(\bar{x}=0*f_{0}+1*f_{1}+2*f_{2}+3*f_{3}+4*f_{4}=1.691057\)</span></p>
</div>
<div id="promedio" class="section level2 hasAnchor" number="2.20">
<h2><span class="header-section-number">2.20</span> Promedio<a href="descripción-de-datos.html#promedio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El promedio es también el centro de gravedad de las variables continuas. Ese es el punto donde las frecuencias reativas se equilibran.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="mediana" class="section level2 hasAnchor" number="2.21">
<h2><span class="header-section-number">2.21</span> mediana<a href="descripción-de-datos.html#mediana" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Otra medida de centralidad es la mediana. La mediana <span class="math inline">\(x_m\)</span>, o <span class="math inline">\(q_{0.5}\)</span>, es el valor por debajo del cual encontramos la mitad de las observaciones. Cuando ordenamos las observaciones <span class="math inline">\(x_1 &lt;... x_j &lt; x_{j+1} &lt; x_N\)</span>, las contamos hasta encontrar la mitad de ellas. <span class="math inline">\(x_m\)</span> es tal que</p>
<p><span class="math display">\[\sum_{i\leq m} 1 = \frac{N}{2}\]</span>
<strong>Ejemplo (Misofonía)</strong></p>
<p>Si ordenamos los ángulos de convexidad, vemos que <span class="math inline">\(62\)</span> observaciones (individuos) (<span class="math inline">\(N/2 \sim 123/2\)</span>) están por debajo de <span class="math inline">\(7.96\)</span>. La <strong>convexidad mediana</strong> es por lo tanto <span class="math inline">\(q_{0.5}=x_{62}=7.96\)</span></p>
<pre><code>##  [1] -1.00 -1.00  1.40  1.40  1.80  2.46  2.50  3.40  3.50  4.40  4.60  4.70
## [13]  4.80  5.40  6.00  6.02  6.03  6.10  6.10  6.30  6.60  6.64  6.64  6.70
## [25]  6.80  6.91  7.00  7.00  7.00  7.00  7.02  7.02  7.10  7.12  7.20  7.24
## [37]  7.27  7.29  7.30  7.40  7.50  7.50  7.50  7.62  7.70  7.70  7.70  7.75
## [49]  7.76  7.80  7.80  7.80  7.81  7.82  7.90  7.90  7.90  7.90  7.90  7.94
## [61]  7.95  7.96</code></pre>
<pre><code>##  [1]  7.96  7.97  8.00  8.00  8.10  8.50  8.54  8.70  9.00  9.26  9.76  9.81
## [13] 10.00 11.00 11.20 11.23 11.40 11.50 11.60 12.00 12.27 12.30 12.30 12.60
## [25] 13.40 13.50 14.00 14.00 14.00 14.05 14.40 14.70 15.00 15.00 15.26 16.00
## [37] 16.00 16.00 16.00 16.14 16.69 16.80 16.80 17.00 17.00 17.60 17.86 18.00
## [49] 18.23 18.30 18.70 19.00 19.00 19.00 19.00 19.01 19.20 19.30 19.70 20.26
## [61] 21.30</code></pre>
<pre><code>## [1] 7.96</code></pre>
<p>En términos de frecuencias, <span class="math inline">\(q_{0.5}\)</span> hace que la frecuencia acumulada <span class="math inline">\(F_x\)</span> sea igual a <span class="math inline">\(0.5\)</span></p>
<p><span class="math display">\[\sum_{i = 0, ... m} f_i =F_{q_{0.5}}=0.5\]</span>
o</p>
<p><span class="math display">\[q_{0.5}=F^{-1}(0.5)\]</span></p>
<p>En el gráfico de distribución, la mediana es el valor de <span class="math inline">\(x\)</span> en el que se encuentra la mitad del máximo de <span class="math inline">\(F\)</span>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>El promedio y la mediana no siempre son iguales.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
<div id="dispersión" class="section level2 hasAnchor" number="2.22">
<h2><span class="header-section-number">2.22</span> Dispersión<a href="descripción-de-datos.html#dispersión" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Otras estadísticas de resumen importantes de las observaciones son las de <strong>dispersión</strong>.</p>
<p>Muchos experimentos pueden compartir su media, pero difieren en cuán <strong>dispersos</strong> son los valores.</p>
<p>La dispersión de las observaciones es una medida del <strong>ruido</strong>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
</div>
<div id="variación-de-la-muestra" class="section level2 hasAnchor" number="2.23">
<h2><span class="header-section-number">2.23</span> Variación de la muestra<a href="descripción-de-datos.html#variación-de-la-muestra" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La dispersión sobre la media se mide con la varianza muestral</p>
<p><span class="math display">\[s^2=\frac{1}{N-1} \sum_{j=1..N} (x_j-\bar{x})^2\]</span></p>
<p>Este número, mide la distancia cuadrada promedio de las <strong>observaciones</strong> al promedio. La razón de <span class="math inline">\(N-1\)</span> se explicará cuando hablemos de inferencia, cuando estudiemos la dispersión de <span class="math inline">\(\bar{x}\)</span>, además de la dispersión de las observaciones.</p>
<p>En términos de las frecuencias de las variables <strong>categóricas y ordenadas</strong></p>
<p><span class="math display">\[s^2=\frac{N}{N-1} \sum_{i=1... M} (x_i-\bar{x})^2 f_i\]</span></p>
<p><span class="math inline">\(s^2\)</span> se puede considerar como el <strong>momento de inercia</strong> de las observaciones.</p>
<p>La raíz cuadrada de la varianza de la muestra se denomina <strong>desviación estándar</strong> <span class="math inline">\(s\)</span>.</p>
<p><strong>Ejemplo (Misofonía)</strong></p>
<p>La desviación estándar del ángulo de convexidad es</p>
<p></br>
<span class="math inline">\(s= [\frac{1}{123-1}((7.97-10.19894)^2+ (18.23-10.19894)^2\)</span>
</br><span class="math inline">\(+ (12.27-10.19894)^2 + ...)]^{1/2} = 5.086707\)</span></p>
<p>La convexidad de la mandíbula se desvía de su media en <span class="math inline">\(5.086707\)</span>.</p>
</div>
<div id="rango-intercuartílico-iqr" class="section level2 hasAnchor" number="2.24">
<h2><span class="header-section-number">2.24</span> Rango intercuartílico (IQR)<a href="descripción-de-datos.html#rango-intercuartílico-iqr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La dispersión de los datos también se puede medir con respecto a la mediana usando el <strong>rango intercuartílico</strong>:</p>
<ol style="list-style-type: decimal">
<li>Definimos el <strong>primer</strong> cuartil como el valor <span class="math inline">\(x_m\)</span> que hace que la frecuencia acumulada <span class="math inline">\(F_{q_{0.25}}\)</span> sea igual a <span class="math inline">\(0.25\)</span> (<span class="math inline">\(x\)</span> donde hemos acumulado una cuarta parte de las observaciones)</li>
</ol>
<p><span class="math display">\[F_{q_{0.25}}=0.25\]</span></p>
<ol style="list-style-type: decimal">
<li>Definimos el <strong>tercer</strong> cuartil como el valor <span class="math inline">\(x_m\)</span> que hace que la frecuencia acumulada <span class="math inline">\(F_{q_{0.75}}\)</span> sea igual a <span class="math inline">\(0.75\)</span> (<span class="math inline">\(x\)</span> donde hemos acumulado tres cuartos de observaciones)</li>
</ol>
<p><span class="math display">\[F_{q_{0.75}}=0.75\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>El <strong>rango intercuartílico</strong> (IQR) es <span class="math inline">\(IQR=q_{0.75} - q_{0.25}\)</span>. Esa es la distancia entre el tercer y el primer cuartil y captura el <span class="math inline">\(50\%\)</span> central de las observaciones</li>
</ol>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="diagrama-de-caja" class="section level2 hasAnchor" number="2.25">
<h2><span class="header-section-number">2.25</span> Diagrama de caja<a href="descripción-de-datos.html#diagrama-de-caja" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El rango intercuartílico, la mediana y los <span class="math inline">\(5\%\)</span> y <span class="math inline">\(95\%\)</span> de los datos se pueden visualizar en un <strong>diagrama de caja</strong>.</p>
<p>En el diagrama de caja, los valores de los resultados están en el eje y. El IQR es la caja, la mediana es la línea del medio y los bigotes marcan los <span class="math inline">\(5\%\)</span> y <span class="math inline">\(95\%\)</span> de los datos.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="preguntas" class="section level2 hasAnchor" number="2.26">
<h2><span class="header-section-number">2.26</span> Preguntas<a href="descripción-de-datos.html#preguntas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>1)</strong> En el siguiente diagrama de caja, el primer cuartil y el segundo cuartil de los datos son:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\((-1.00, 21.30)\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\((-1.00, 7.02)\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\((7.02, 7.96)\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\((7.02, 14.22)\)</span></p>
<p><img src="figures/box.png" /></p>
<p><strong>2)</strong> La principal desventaja de un histograma es que:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> Depende del tamaño del bin; <strong><span class="math inline">\(\qquad\)</span>b:</strong> No se puede utilizar para variables categóricas;
<strong><span class="math inline">\(\qquad\)</span>c:</strong> No se puede usar cuando el tamaño del bin es pequeño;
<strong><span class="math inline">\(\qquad\)</span>d:</strong> Se usa solo para frecuencias relativas;</p>
<p><strong>3)</strong> Si las frecuencias acumuladas relativas de un experimento aleatorio con resultados <span class="math inline">\(\{1,2,3,4\}\)</span> son: <span class="math inline">\(F(1)=0.15, \qquad F(2)=0.60, \qquad F(3)=0.85, \qquad F(4)=1\)</span>.</p>
<p>Entonces la frecuencia relativa para el resultado <span class="math inline">\(3\)</span> es</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\(0.15\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\(0.85\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\(0.45\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\(0.25\)</span></p>
<p><strong>4)</strong> En una muestra de tamaño <span class="math inline">\(10\)</span> de un experimento aleatorio obtuvimos los siguientes datos:</p>
<p><span class="math inline">\(8,\qquad 3,\qquad 3,\qquad 7,\qquad 3,\qquad 6,\qquad 5,\qquad 10,\qquad 3,\qquad 8\)</span>.</p>
<p>El primer cuartil de los datos es:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\(3.5\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\(4\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\(5\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\(3\)</span></p>
<p><strong>5)</strong> Imaginemos que recopilamos datos para dos cantidades que no son mutuamente excluyentes, por ejemplo, el sexo y la nacionalidad de los pasajeros de un vuelo. Si queremos hacer un solo gráfico circular para los datos, ¿cuál de estas afirmaciones es verdadera?</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> Solo podemos hacer un gráfico circular de nacionalidad porque tiene más de dos resultados posibles; <strong><span class="math inline">\(\qquad\)</span>b:</strong> Podemos hacer un gráfico circular para una variable nueva que marca el sexo <strong>y</strong> la nacionalidad; <strong><span class="math inline">\(\qquad\)</span>c:</strong> Podemos hacer un gráfico circular para la variale sexo o la variable nacionalidad; <strong><span class="math inline">\(\qquad\)</span>d:</strong> Solo podemos elegir si hacemos un gráfico circular para el sexo o un gráfico circular para la nacionalidad.</p>
</div>
<div id="ejercicios" class="section level2 hasAnchor" number="2.27">
<h2><span class="header-section-number">2.27</span> Ejercicios<a href="descripción-de-datos.html#ejercicios" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="ejercicio-1" class="section level4 hasAnchor" number="2.27.0.1">
<h4><span class="header-section-number">2.27.0.1</span> Ejercicio 1<a href="descripción-de-datos.html#ejercicio-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Hemos realizado un experimento 8 veces con los siguientes resultados</p>
<pre><code>## [1]  3  3 10  2  6 11  5  4</code></pre>
<p>Responde las siguientes cuestiones:</p>
<ul>
<li>Calcula las frecuencias relativas de cada resultado.</li>
<li>Calcula las frecuencias acumuladas de cada resultado.</li>
<li>¿Cuál es el promedio de las observaciones?</li>
<li>¿Cuál es la mediana?</li>
<li>¿Cuál es el tercer cuartil?</li>
<li>¿Cuál es el primer cuartil?</li>
</ul>
</div>
<div id="ejercicio-2" class="section level4 hasAnchor" number="2.27.0.2">
<h4><span class="header-section-number">2.27.0.2</span> Ejercicio 2<a href="descripción-de-datos.html#ejercicio-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Hemos realizado un experimento 10 veces con los siguientes resultados</p>
<pre><code>##  [1] 2.875775 7.883051 4.089769 8.830174 9.404673 0.455565 5.281055 8.924190
##  [9] 5.514350 4.566147</code></pre>
<p>Considera 10 bins de tamaño 1: [0,1], (1,2]…(9,10).</p>
<p>Responde las siguientes cuestiones:</p>
<ul>
<li><p>Calcula las frecuencias relativas de cada resultado y dibuja el histograma</p></li>
<li><p>Calcula las frecuencias acumulativas de cada resultado y dibuja la gráfica acumulativa.</p></li>
<li><p>Dibuja un diagrama de caja .</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probabilidad.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-DataDescription.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
