---
output: html_document
---

## Software científico

Aquí se pueden encontrar algunos de los paquetes de R que he desarrollado para el análisis de datos biomédicos de alta dimensionalidad 

- [X-Ra](https://xra.isglobal.org). R package. Calcula la inactivcion defectuosa del cromsomosoma X usando datos de mentilación.


- [teff](https://github.com/teff-package/teff). R package. Usa métodos de inferencia causal para determinar subgrupos de individuos que responden mejor a un tratamiento.

- [cosplice4gtex](http://cosplicing.isglobal.org). webapp. Calcula el co-splicing entre dos genes usando datos de GTEx.

- [lambda](https://github.com/isglobal-brge/lambda). R package. Calcula inter-study agreement para medir los cambios en las estructuras de redes genéticas entre diferentes tejidos

- [invClust](https://github.com/isglobal-brge/invClust). R package. Genotype inversion polymorphisims from SNP data.

- [inveRsion](https://www.bioconductor.org/packages/release/bioc/html/inveRsion.html). R package. Detecta inversiones polimórficas en datos de SNPs.

- [MLPAstats](https://github.com/cran/MLPAstats). R package. Detecta copy number variants (CNV) en datos de MLPA data.

- [ICC](https://www.kcl.ac.uk/ioppn/depts/neuroimaging/research/imaginganalysis/software/icctoolbox.aspx). Matlab tool. Calcula el la correación intra-clase para datos de resonancia magnética funcional.
