---
output: html_document
---

# Entendimiento estadístico con R:

1. [Estadística descriptiva](https://alejandro-isglobal.github.io/teaching/estadisticadescriptiva.html):

*La inferencia estadística esta enraizada en la estadística descriptiva. Los conceptos abtractos deben responder al resultado de observaciones. Aquí motivaré el objeto de estudio de la estadística desde una perspectiva conceptual. Intentaré demarcar lo que la estadística estudia, por qué y su utilidad. Usaré datos globales de parques eólicos para ilustrar los conceptos básicos.*


2. [Variables aleatorias discretas](https://alejandro-isglobal.github.io/teaching/vad.html):

*Las funciones de probabilidad son los objetos matemáticos que usamos para entender experimentos aletorios. Cuando describimos un tipo de experimento aleatorio por una familia de funciones de probabilidad decimos que modelamos el proceso de medición del experimento. Cuando escogemos una función en particular para unos datos decimos que ajustamos el modelo. Usando R y como ejemplo el error aleatorio cometido al trasmitir los píxeles de de una foto, explico como las distribuciones binomial, geométrica y binomial negativa se obtienen de la distribución de Bernoulli.*


------------

3. [Distribuciones de muestreo](https://alejandro-isglobal.github.io/teaching/muestreo.html):

*Las distribuciones de muestreo son la puerta de entrada a la inferencia estadística y de salida a la predicción. Usando datos de un contador Geiger muestro cómo estas distribuciones se usan para conocer los modelos probabilísticos de variables aletorias.*

------------

4. [Intervalos de confianza](https://alejandro-isglobal.github.io/teaching/intervalosdeconfianza.html):

*Los intervalos de confiaza son herramientas básicas de la inferencia estadística y como tal se calculan fácilmente en R. Usando R y un ejemplo como guía, en este tutotial explico conceptos teóricos que ayudan a ententender e interpretar un intervalo de confianza.  Por último describo las funciones para calcularlos directamente en R.*


------------

#Vídeos:

Diapos y videos que explican conceptos básicos en estadística usando R, hacen parte del curso de prácticas de estadística de la escuela de ingeniería de la [Universitat Politècnica de Catalunya](https://eebe.upc.edu/es)


1. Introducción a R: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/practica1.pdf), [dat1.txt](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/data/dat1.txt)

[Video 1](https://youtu.be/rj0qrpSmTnc), [Video 2](https://youtu.be/hp1RpL3QBuE), [Video 3](https://youtu.be/0kHW1qufx9M), [Video 4](https://youtu.be/EKbMF_8QxvQ)

2. Estadística descriptiva: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/practica2.pdf), [air.txt](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/data/air.txt)

[Video 1](https://youtu.be/wuRchCaCBBs), [Video 2](https://youtu.be/_3kT7o31u4I), [Video 3](https://youtu.be/oujlmfr67FA)

3. Regresión lineal: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/Practicas3.pdf), [data.txt](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/data/data.txt) 

[Video 1](https://youtu.be/kBRr3fMIh00), [Video 2](https://youtu.be/kLVufi8waos), [Video 3](https://youtu.be/SwRrrLfUCbo)

4. Variables aleatorias discretas y funciones de distribución: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/practica4.pdf)

[Video 1](https://youtu.be/pcZk2jKFs1o), [Video 2](https://youtu.be/-OUtWd7-nQ8), [Video 3](https://youtu.be/HBa-d8Ungsw)

5. Variables aleatorias continuas y funciones de distribución: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/lecture5.pdf), [Covid19_9abril.csv](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/data/Covid19_9abril.csv)

[Video 1](https://youtu.be/WMRgZEuSSBU), [Video 2](https://youtu.be/MG0W5-Sw48U), [Video 3](https://youtu.be/awQ34qKnZSw), 


6. Distribuciones de Muestreo: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/Practica6.pdf), [capture.txt](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/data/capture.txt) 

[Video 1](https://youtu.be/Ia1WOXowoYY) , [Video 2](https://youtu.be/igqlRlxjVrs), [Video 3](https://youtu.be/Iwj4eg1uZhs)

7. Intervalos de confianza: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/Practica7.pdf)

[Video 1](https://youtu.be/tYp_hXUm0-E), [Video 2](https://youtu.be/DBaid-WVCZ4), [Video 3](https://youtu.be/0kHW1qufx9M)

8. Pruebas de hipótesis: [diapos](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/slides/Practica7.pdf), [PLN_Number_SOC_Temp_StoragePeriod.csv](https://github.com/alejandro-isglobal/alejandro-isglobal.github.io/blob/master/data/PLN_Number_SOC_Temp_StoragePeriod.csv) 

[Video 1](https://youtu.be/5cbmYIq0Enc), [Video 2](https://youtu.be/2VrJAYzvRLM), [Video 3](https://youtu.be/kFKYAbrkp-s)

------------

# Análisis estadístico de Biomarcadores

- Biomarcadores: Curso 2021. Almirall.  [Diapos](https://alejandro-isglobal.github.io/teaching/Biomarkdown.html)
