<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Data description | Statistical Data Analysis</title>
  <meta name="description" content="This is the book for the statistics theory of the BIST master" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Data description | Statistical Data Analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the book for the statistics theory of the BIST master" />
  <meta name="github-repo" content="alejandro-isglobal/master" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Data description | Statistical Data Analysis" />
  
  <meta name="twitter:description" content="This is the book for the statistics theory of the BIST master" />
  

<meta name="author" content="Alejandro Caceres" />


<meta name="date" content="2024-10-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="probability.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SDA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#how"><i class="fa fa-check"></i><b>1.1</b> How</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i><b>1.2</b> Schedule</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#recommended-reading-list"><i class="fa fa-check"></i><b>1.3</b> Recommended reading list</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-description.html"><a href="data-description.html"><i class="fa fa-check"></i><b>2</b> Data description</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-description.html"><a href="data-description.html#scientific-method"><i class="fa fa-check"></i><b>2.1</b> Scientific method</a></li>
<li class="chapter" data-level="2.2" data-path="data-description.html"><a href="data-description.html#data"><i class="fa fa-check"></i><b>2.2</b> Data</a></li>
<li class="chapter" data-level="2.3" data-path="data-description.html"><a href="data-description.html#result-types"><i class="fa fa-check"></i><b>2.3</b> Result types</a></li>
<li class="chapter" data-level="2.4" data-path="data-description.html"><a href="data-description.html#random-experiments"><i class="fa fa-check"></i><b>2.4</b> Random experiments</a></li>
<li class="chapter" data-level="2.5" data-path="data-description.html"><a href="data-description.html#absolute-frequencies"><i class="fa fa-check"></i><b>2.5</b> Absolute frequencies</a></li>
<li class="chapter" data-level="2.6" data-path="data-description.html"><a href="data-description.html#relative-frequencies"><i class="fa fa-check"></i><b>2.6</b> Relative frequencies</a></li>
<li class="chapter" data-level="2.7" data-path="data-description.html"><a href="data-description.html#bar-chart"><i class="fa fa-check"></i><b>2.7</b> Bar chart</a></li>
<li class="chapter" data-level="2.8" data-path="data-description.html"><a href="data-description.html#pie-chart-pie"><i class="fa fa-check"></i><b>2.8</b> Pie chart (pie)</a></li>
<li class="chapter" data-level="2.9" data-path="data-description.html"><a href="data-description.html#ordinal-categorical-outcomes"><i class="fa fa-check"></i><b>2.9</b> Ordinal categorical outcomes</a></li>
<li class="chapter" data-level="2.10" data-path="data-description.html"><a href="data-description.html#absolute-and-relative-cumulative-frequencies"><i class="fa fa-check"></i><b>2.10</b> Absolute and relative cumulative frequencies</a></li>
<li class="chapter" data-level="2.11" data-path="data-description.html"><a href="data-description.html#cumulative-frequency-graph"><i class="fa fa-check"></i><b>2.11</b> Cumulative frequency graph</a></li>
<li class="chapter" data-level="2.12" data-path="data-description.html"><a href="data-description.html#numerical-outcomes"><i class="fa fa-check"></i><b>2.12</b> Numerical outcomes</a></li>
<li class="chapter" data-level="2.13" data-path="data-description.html"><a href="data-description.html#transforming-continuous-data"><i class="fa fa-check"></i><b>2.13</b> Transforming continuous data</a></li>
<li class="chapter" data-level="2.14" data-path="data-description.html"><a href="data-description.html#frequency-table-for-a-continuous-variable"><i class="fa fa-check"></i><b>2.14</b> Frequency table for a continuous variable</a></li>
<li class="chapter" data-level="2.15" data-path="data-description.html"><a href="data-description.html#histogram"><i class="fa fa-check"></i><b>2.15</b> Histogram</a></li>
<li class="chapter" data-level="2.16" data-path="data-description.html"><a href="data-description.html#cumulative-frequency-graph-1"><i class="fa fa-check"></i><b>2.16</b> Cumulative frequency graph</a></li>
<li class="chapter" data-level="2.17" data-path="data-description.html"><a href="data-description.html#summary-statistics"><i class="fa fa-check"></i><b>2.17</b> Summary Statistics</a></li>
<li class="chapter" data-level="2.18" data-path="data-description.html"><a href="data-description.html#average-sample-mean"><i class="fa fa-check"></i><b>2.18</b> Average (sample mean)</a></li>
<li class="chapter" data-level="2.19" data-path="data-description.html"><a href="data-description.html#median"><i class="fa fa-check"></i><b>2.19</b> Median</a></li>
<li class="chapter" data-level="2.20" data-path="data-description.html"><a href="data-description.html#dispersion"><i class="fa fa-check"></i><b>2.20</b> Dispersion</a></li>
<li class="chapter" data-level="2.21" data-path="data-description.html"><a href="data-description.html#sample-variance"><i class="fa fa-check"></i><b>2.21</b> Sample variance</a></li>
<li class="chapter" data-level="2.22" data-path="data-description.html"><a href="data-description.html#interquartile-range-iqr"><i class="fa fa-check"></i><b>2.22</b> Interquartile range (IQR)</a></li>
<li class="chapter" data-level="2.23" data-path="data-description.html"><a href="data-description.html#boxplot"><i class="fa fa-check"></i><b>2.23</b> Boxplot</a></li>
<li class="chapter" data-level="2.24" data-path="data-description.html"><a href="data-description.html#questions"><i class="fa fa-check"></i><b>2.24</b> Questions</a></li>
<li class="chapter" data-level="2.25" data-path="data-description.html"><a href="data-description.html#exercises"><i class="fa fa-check"></i><b>2.25</b> Exercises</a></li>
<li class="chapter" data-level="2.26" data-path="data-description.html"><a href="data-description.html#practice"><i class="fa fa-check"></i><b>2.26</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>3</b> Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probability.html"><a href="probability.html#random-experiments-1"><i class="fa fa-check"></i><b>3.1</b> Random experiments</a></li>
<li class="chapter" data-level="3.2" data-path="probability.html"><a href="probability.html#measurement-probability"><i class="fa fa-check"></i><b>3.2</b> Measurement probability</a></li>
<li class="chapter" data-level="3.3" data-path="probability.html"><a href="probability.html#classical-probability"><i class="fa fa-check"></i><b>3.3</b> Classical probability</a></li>
<li class="chapter" data-level="3.4" data-path="probability.html"><a href="probability.html#relative-frequencies-1"><i class="fa fa-check"></i><b>3.4</b> Relative frequencies</a></li>
<li class="chapter" data-level="3.5" data-path="probability.html"><a href="probability.html#relative-frequencies-at-infinity"><i class="fa fa-check"></i><b>3.5</b> Relative frequencies at infinity</a></li>
<li class="chapter" data-level="3.6" data-path="probability.html"><a href="probability.html#frequentist-probability"><i class="fa fa-check"></i><b>3.6</b> Frequentist probability</a></li>
<li class="chapter" data-level="3.7" data-path="probability.html"><a href="probability.html#classical-and-frequentist-probabilities"><i class="fa fa-check"></i><b>3.7</b> Classical and frequentist probabilities</a></li>
<li class="chapter" data-level="3.8" data-path="probability.html"><a href="probability.html#definition-of-probability"><i class="fa fa-check"></i><b>3.8</b> Definition of probability</a></li>
<li class="chapter" data-level="3.9" data-path="probability.html"><a href="probability.html#probabilities-table"><i class="fa fa-check"></i><b>3.9</b> Probabilities Table</a></li>
<li class="chapter" data-level="3.10" data-path="probability.html"><a href="probability.html#sample-space"><i class="fa fa-check"></i><b>3.10</b> Sample space</a></li>
<li class="chapter" data-level="3.11" data-path="probability.html"><a href="probability.html#events"><i class="fa fa-check"></i><b>3.11</b> Events</a></li>
<li class="chapter" data-level="3.12" data-path="probability.html"><a href="probability.html#algebra-of-events"><i class="fa fa-check"></i><b>3.12</b> Algebra of events</a></li>
<li class="chapter" data-level="3.13" data-path="probability.html"><a href="probability.html#mutually-exclusive-results"><i class="fa fa-check"></i><b>3.13</b> Mutually exclusive results</a></li>
<li class="chapter" data-level="3.14" data-path="probability.html"><a href="probability.html#joint-probabilities"><i class="fa fa-check"></i><b>3.14</b> Joint probabilities</a></li>
<li class="chapter" data-level="3.15" data-path="probability.html"><a href="probability.html#contingency-table"><i class="fa fa-check"></i><b>3.15</b> Contingency table</a></li>
<li class="chapter" data-level="3.16" data-path="probability.html"><a href="probability.html#the-addition-rule"><i class="fa fa-check"></i><b>3.16</b> The addition rule:</a></li>
<li class="chapter" data-level="3.17" data-path="probability.html"><a href="probability.html#questions-1"><i class="fa fa-check"></i><b>3.17</b> Questions</a></li>
<li class="chapter" data-level="3.18" data-path="probability.html"><a href="probability.html#exercises-1"><i class="fa fa-check"></i><b>3.18</b> Exercises</a></li>
<li class="chapter" data-level="3.19" data-path="probability.html"><a href="probability.html#practice-1"><i class="fa fa-check"></i><b>3.19</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>4</b> Conditional probability</a>
<ul>
<li class="chapter" data-level="4.1" data-path="conditional-probability.html"><a href="conditional-probability.html#joint-probability"><i class="fa fa-check"></i><b>4.1</b> Joint probability</a></li>
<li class="chapter" data-level="4.2" data-path="conditional-probability.html"><a href="conditional-probability.html#statistical-independence"><i class="fa fa-check"></i><b>4.2</b> Statistical independence</a></li>
<li class="chapter" data-level="4.3" data-path="conditional-probability.html"><a href="conditional-probability.html#the-conditional-probability"><i class="fa fa-check"></i><b>4.3</b> The conditional probability</a></li>
<li class="chapter" data-level="4.4" data-path="conditional-probability.html"><a href="conditional-probability.html#conditional-contingency-table"><i class="fa fa-check"></i><b>4.4</b> Conditional contingency table</a></li>
<li class="chapter" data-level="4.5" data-path="conditional-probability.html"><a href="conditional-probability.html#statistical-independence-1"><i class="fa fa-check"></i><b>4.5</b> Statistical independence</a></li>
<li class="chapter" data-level="4.6" data-path="conditional-probability.html"><a href="conditional-probability.html#statistical-dependency"><i class="fa fa-check"></i><b>4.6</b> Statistical dependency</a></li>
<li class="chapter" data-level="4.7" data-path="conditional-probability.html"><a href="conditional-probability.html#diagnostic-test"><i class="fa fa-check"></i><b>4.7</b> Diagnostic test</a></li>
<li class="chapter" data-level="4.8" data-path="conditional-probability.html"><a href="conditional-probability.html#inverse-probabilities"><i class="fa fa-check"></i><b>4.8</b> Inverse probabilities</a></li>
<li class="chapter" data-level="4.9" data-path="conditional-probability.html"><a href="conditional-probability.html#bayes-theorem"><i class="fa fa-check"></i><b>4.9</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="4.10" data-path="conditional-probability.html"><a href="conditional-probability.html#questions-2"><i class="fa fa-check"></i><b>4.10</b> Questions</a></li>
<li class="chapter" data-level="4.11" data-path="conditional-probability.html"><a href="conditional-probability.html#exercises-2"><i class="fa fa-check"></i><b>4.11</b> Exercises</a></li>
<li class="chapter" data-level="4.12" data-path="conditional-probability.html"><a href="conditional-probability.html#practice-2"><i class="fa fa-check"></i><b>4.12</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html"><i class="fa fa-check"></i><b>5</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#objective"><i class="fa fa-check"></i><b>5.1</b> Objective</a></li>
<li class="chapter" data-level="5.2" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#relative-frequencies-2"><i class="fa fa-check"></i><b>5.2</b> Relative frequencies</a></li>
<li class="chapter" data-level="5.3" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#random-variable"><i class="fa fa-check"></i><b>5.3</b> Random variable</a></li>
<li class="chapter" data-level="5.4" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#the-value-of-a-random-variable"><i class="fa fa-check"></i><b>5.4</b> The value of a random variable</a></li>
<li class="chapter" data-level="5.5" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-of-random-variables"><i class="fa fa-check"></i><b>5.5</b> Probability of random variables</a></li>
<li class="chapter" data-level="5.6" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-functions"><i class="fa fa-check"></i><b>5.6</b> Probability functions</a></li>
<li class="chapter" data-level="5.7" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-mass-functions"><i class="fa fa-check"></i><b>5.7</b> Probability mass functions</a></li>
<li class="chapter" data-level="5.8" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probabilities-and-relative-frequencies"><i class="fa fa-check"></i><b>5.8</b> Probabilities and relative frequencies</a></li>
<li class="chapter" data-level="5.9" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#mean-or-expected-value"><i class="fa fa-check"></i><b>5.9</b> Mean or expected value</a></li>
<li class="chapter" data-level="5.10" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#variance"><i class="fa fa-check"></i><b>5.10</b> Variance</a></li>
<li class="chapter" data-level="5.11" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-functions-for-functions-of-x"><i class="fa fa-check"></i><b>5.11</b> Probability functions for functions of <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="5.12" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-distribution"><i class="fa fa-check"></i><b>5.12</b> Probability distribution</a></li>
<li class="chapter" data-level="5.13" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-function-and-probability-distribution"><i class="fa fa-check"></i><b>5.13</b> Probability function and probability distribution</a></li>
<li class="chapter" data-level="5.14" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#quantiles"><i class="fa fa-check"></i><b>5.14</b> Quantiles</a></li>
<li class="chapter" data-level="5.15" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#summary"><i class="fa fa-check"></i><b>5.15</b> Summary</a></li>
<li class="chapter" data-level="5.16" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#questions-3"><i class="fa fa-check"></i><b>5.16</b> Questions</a></li>
<li class="chapter" data-level="5.17" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#exercises-3"><i class="fa fa-check"></i><b>5.17</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="continous-random-variables.html"><a href="continous-random-variables.html"><i class="fa fa-check"></i><b>6</b> Continous Random Variables</a>
<ul>
<li class="chapter" data-level="6.1" data-path="continous-random-variables.html"><a href="continous-random-variables.html#objective-1"><i class="fa fa-check"></i><b>6.1</b> Objective</a></li>
<li class="chapter" data-level="6.2" data-path="continous-random-variables.html"><a href="continous-random-variables.html#continuous-random-variables"><i class="fa fa-check"></i><b>6.2</b> Continuous random variables</a></li>
<li class="chapter" data-level="6.3" data-path="continous-random-variables.html"><a href="continous-random-variables.html#relative-frequencies-3"><i class="fa fa-check"></i><b>6.3</b> Relative frequencies</a></li>
<li class="chapter" data-level="6.4" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probability-density-function"><i class="fa fa-check"></i><b>6.4</b> Probability Density Function</a></li>
<li class="chapter" data-level="6.5" data-path="continous-random-variables.html"><a href="continous-random-variables.html#total-area-under-the-curve"><i class="fa fa-check"></i><b>6.5</b> Total area under the curve</a></li>
<li class="chapter" data-level="6.6" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probabilities-of-continous-variables"><i class="fa fa-check"></i><b>6.6</b> Probabilities of continous variables</a></li>
<li class="chapter" data-level="6.7" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probability-distribution-1"><i class="fa fa-check"></i><b>6.7</b> Probability distribution</a></li>
<li class="chapter" data-level="6.8" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probability-plots"><i class="fa fa-check"></i><b>6.8</b> Probability plots</a></li>
<li class="chapter" data-level="6.9" data-path="continous-random-variables.html"><a href="continous-random-variables.html#mean"><i class="fa fa-check"></i><b>6.9</b> Mean</a></li>
<li class="chapter" data-level="6.10" data-path="continous-random-variables.html"><a href="continous-random-variables.html#variance-1"><i class="fa fa-check"></i><b>6.10</b> Variance</a></li>
<li class="chapter" data-level="6.11" data-path="continous-random-variables.html"><a href="continous-random-variables.html#functions-of-x"><i class="fa fa-check"></i><b>6.11</b> Functions of <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="6.12" data-path="continous-random-variables.html"><a href="continous-random-variables.html#exercises-4"><i class="fa fa-check"></i><b>6.12</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html"><i class="fa fa-check"></i><b>7</b> Discrete Probability Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#objective-2"><i class="fa fa-check"></i><b>7.1</b> Objective</a></li>
<li class="chapter" data-level="7.2" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#probability-mass-function"><i class="fa fa-check"></i><b>7.2</b> Probability mass function</a></li>
<li class="chapter" data-level="7.3" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#probability-model"><i class="fa fa-check"></i><b>7.3</b> Probability model</a></li>
<li class="chapter" data-level="7.4" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#parametric-models"><i class="fa fa-check"></i><b>7.4</b> Parametric models</a></li>
<li class="chapter" data-level="7.5" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#uniform-distribution-one-parameter"><i class="fa fa-check"></i><b>7.5</b> Uniform distribution (one parameter)</a></li>
<li class="chapter" data-level="7.6" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#uniform-distribution-two-parameters"><i class="fa fa-check"></i><b>7.6</b> Uniform distribution (two parameters)</a></li>
<li class="chapter" data-level="7.7" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#bernoulli-trial"><i class="fa fa-check"></i><b>7.7</b> Bernoulli trial</a></li>
<li class="chapter" data-level="7.8" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#binomial-experiment"><i class="fa fa-check"></i><b>7.8</b> Binomial experiment</a></li>
<li class="chapter" data-level="7.9" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#binomial-probability-function"><i class="fa fa-check"></i><b>7.9</b> Binomial probability function</a></li>
<li class="chapter" data-level="7.10" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#negative-binomial-probability-function"><i class="fa fa-check"></i><b>7.10</b> Negative binomial probability function</a></li>
<li class="chapter" data-level="7.11" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#geometric-distribution"><i class="fa fa-check"></i><b>7.11</b> Geometric distribution</a></li>
<li class="chapter" data-level="7.12" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#hypergeometric-model"><i class="fa fa-check"></i><b>7.12</b> Hypergeometric model</a></li>
<li class="chapter" data-level="7.13" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#questions-4"><i class="fa fa-check"></i><b>7.13</b> Questions</a></li>
<li class="chapter" data-level="7.14" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#exercises-5"><i class="fa fa-check"></i><b>7.14</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html"><i class="fa fa-check"></i><b>8</b> Poisson and Exponential Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#objective-3"><i class="fa fa-check"></i><b>8.1</b> Objective</a></li>
<li class="chapter" data-level="8.2" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#discrete-probability-models-1"><i class="fa fa-check"></i><b>8.2</b> Discrete probability models</a></li>
<li class="chapter" data-level="8.3" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#poissson-experiment"><i class="fa fa-check"></i><b>8.3</b> Poissson experiment</a></li>
<li class="chapter" data-level="8.4" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#poisson-probability-mass-function"><i class="fa fa-check"></i><b>8.4</b> Poisson probability mass function</a></li>
<li class="chapter" data-level="8.5" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#continuous-probability-models"><i class="fa fa-check"></i><b>8.5</b> Continuous probability models</a></li>
<li class="chapter" data-level="8.6" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exponential-process"><i class="fa fa-check"></i><b>8.6</b> Exponential process</a></li>
<li class="chapter" data-level="8.7" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exponential-probability-density"><i class="fa fa-check"></i><b>8.7</b> Exponential probability density</a></li>
<li class="chapter" data-level="8.8" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exponential-distribution"><i class="fa fa-check"></i><b>8.8</b> Exponential Distribution</a></li>
<li class="chapter" data-level="8.9" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#questions-5"><i class="fa fa-check"></i><b>8.9</b> Questions</a></li>
<li class="chapter" data-level="8.10" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exercises-6"><i class="fa fa-check"></i><b>8.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="normal-distribution.html"><a href="normal-distribution.html"><i class="fa fa-check"></i><b>9</b> Normal Distribution</a>
<ul>
<li class="chapter" data-level="9.1" data-path="normal-distribution.html"><a href="normal-distribution.html#objective-4"><i class="fa fa-check"></i><b>9.1</b> Objective</a></li>
<li class="chapter" data-level="9.2" data-path="normal-distribution.html"><a href="normal-distribution.html#history"><i class="fa fa-check"></i><b>9.2</b> History</a></li>
<li class="chapter" data-level="9.3" data-path="normal-distribution.html"><a href="normal-distribution.html#normal-density"><i class="fa fa-check"></i><b>9.3</b> normal density</a></li>
<li class="chapter" data-level="9.4" data-path="normal-distribution.html"><a href="normal-distribution.html#definition"><i class="fa fa-check"></i><b>9.4</b> Definition</a></li>
<li class="chapter" data-level="9.5" data-path="normal-distribution.html"><a href="normal-distribution.html#probability-distribution-2"><i class="fa fa-check"></i><b>9.5</b> Probability distribution</a></li>
<li class="chapter" data-level="9.6" data-path="normal-distribution.html"><a href="normal-distribution.html#standard-normal-density"><i class="fa fa-check"></i><b>9.6</b> Standard normal density</a></li>
<li class="chapter" data-level="9.7" data-path="normal-distribution.html"><a href="normal-distribution.html#standard-distribution"><i class="fa fa-check"></i><b>9.7</b> Standard distribution</a></li>
<li class="chapter" data-level="9.8" data-path="normal-distribution.html"><a href="normal-distribution.html#standardization"><i class="fa fa-check"></i><b>9.8</b> Standardization</a></li>
<li class="chapter" data-level="9.9" data-path="normal-distribution.html"><a href="normal-distribution.html#summary-of-probability-models"><i class="fa fa-check"></i><b>9.9</b> Summary of probability models</a></li>
<li class="chapter" data-level="9.10" data-path="normal-distribution.html"><a href="normal-distribution.html#python-functions-of-probability-models"><i class="fa fa-check"></i><b>9.10</b> Python functions of probability models</a></li>
<li class="chapter" data-level="9.11" data-path="normal-distribution.html"><a href="normal-distribution.html#questions-6"><i class="fa fa-check"></i><b>9.11</b> Questions</a></li>
<li class="chapter" data-level="9.12" data-path="normal-distribution.html"><a href="normal-distribution.html#exercises-7"><i class="fa fa-check"></i><b>9.12</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sampling-distributions.html"><a href="sampling-distributions.html"><i class="fa fa-check"></i><b>10</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sampling-distributions.html"><a href="sampling-distributions.html#objective-5"><i class="fa fa-check"></i><b>10.1</b> Objective</a></li>
<li class="chapter" data-level="10.2" data-path="sampling-distributions.html"><a href="sampling-distributions.html#random-sample"><i class="fa fa-check"></i><b>10.2</b> Random sample</a></li>
<li class="chapter" data-level="10.3" data-path="sampling-distributions.html"><a href="sampling-distributions.html#calculation-of-probabilities"><i class="fa fa-check"></i><b>10.3</b> Calculation of probabilities</a></li>
<li class="chapter" data-level="10.4" data-path="sampling-distributions.html"><a href="sampling-distributions.html#parameter-estimation"><i class="fa fa-check"></i><b>10.4</b> Parameter estimation</a></li>
<li class="chapter" data-level="10.5" data-path="sampling-distributions.html"><a href="sampling-distributions.html#law-of-large-numbers"><i class="fa fa-check"></i><b>10.5</b> Law of large numbers</a></li>
<li class="chapter" data-level="10.6" data-path="sampling-distributions.html"><a href="sampling-distributions.html#inference"><i class="fa fa-check"></i><b>10.6</b> Inference</a></li>
<li class="chapter" data-level="10.7" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sample-mean"><i class="fa fa-check"></i><b>10.7</b> Sample mean</a></li>
<li class="chapter" data-level="10.8" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sample-sum"><i class="fa fa-check"></i><b>10.8</b> Sample sum</a></li>
<li class="chapter" data-level="10.9" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sample-variance-1"><i class="fa fa-check"></i><b>10.9</b> Sample variance</a></li>
<li class="chapter" data-level="10.10" data-path="sampling-distributions.html"><a href="sampling-distributions.html#probabilities-of-the-sample-variance"><i class="fa fa-check"></i><b>10.10</b> Probabilities of the sample variance</a></li>
<li class="chapter" data-level="10.11" data-path="sampling-distributions.html"><a href="sampling-distributions.html#chi2-statistic"><i class="fa fa-check"></i><b>10.11</b> <span class="math inline">\(\chi^2\)</span>-statistic</a></li>
<li class="chapter" data-level="10.12" data-path="sampling-distributions.html"><a href="sampling-distributions.html#questions-7"><i class="fa fa-check"></i><b>10.12</b> Questions</a></li>
<li class="chapter" data-level="10.13" data-path="sampling-distributions.html"><a href="sampling-distributions.html#exercises-8"><i class="fa fa-check"></i><b>10.13</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html"><i class="fa fa-check"></i><b>11</b> Central limit theorem</a>
<ul>
<li class="chapter" data-level="11.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#objective-6"><i class="fa fa-check"></i><b>11.1</b> Objective</a></li>
<li class="chapter" data-level="11.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#margin-of-error"><i class="fa fa-check"></i><b>11.2</b> Margin of error</a></li>
<li class="chapter" data-level="11.3" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#averages-of-normal-variables"><i class="fa fa-check"></i><b>11.3</b> Averages of normal variables</a></li>
<li class="chapter" data-level="11.4" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#central-limit-theorem-1"><i class="fa fa-check"></i><b>11.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="11.5" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#sample-sum-and-clt"><i class="fa fa-check"></i><b>11.5</b> Sample sum and CLT</a></li>
<li class="chapter" data-level="11.6" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#questions-8"><i class="fa fa-check"></i><b>11.6</b> Questions</a></li>
<li class="chapter" data-level="11.7" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#exercises-9"><i class="fa fa-check"></i><b>11.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html"><i class="fa fa-check"></i><b>12</b> Maximum likelihood</a>
<ul>
<li class="chapter" data-level="12.1" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#objective-7"><i class="fa fa-check"></i><b>12.1</b> Objective</a></li>
<li class="chapter" data-level="12.2" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#statistic"><i class="fa fa-check"></i><b>12.2</b> Statistic</a></li>
<li class="chapter" data-level="12.3" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#properties"><i class="fa fa-check"></i><b>12.3</b> Properties</a></li>
<li class="chapter" data-level="12.4" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#maximum-likelihood-1"><i class="fa fa-check"></i><b>12.4</b> Maximum likelihood</a></li>
<li class="chapter" data-level="12.5" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#maximum-likelihood-2"><i class="fa fa-check"></i><b>12.5</b> Maximum likelihood</a></li>
<li class="chapter" data-level="12.6" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#questions-9"><i class="fa fa-check"></i><b>12.6</b> Questions</a></li>
<li class="chapter" data-level="12.7" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#exercises-10"><i class="fa fa-check"></i><b>12.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="interval-estimation.html"><a href="interval-estimation.html"><i class="fa fa-check"></i><b>13</b> Interval estimation</a>
<ul>
<li class="chapter" data-level="13.1" data-path="interval-estimation.html"><a href="interval-estimation.html#objective-8"><i class="fa fa-check"></i><b>13.1</b> Objective</a></li>
<li class="chapter" data-level="13.2" data-path="interval-estimation.html"><a href="interval-estimation.html#estimation-of-the-mean"><i class="fa fa-check"></i><b>13.2</b> Estimation of the mean</a></li>
<li class="chapter" data-level="13.3" data-path="interval-estimation.html"><a href="interval-estimation.html#margin-of-error-1"><i class="fa fa-check"></i><b>13.3</b> Margin of error</a></li>
<li class="chapter" data-level="13.4" data-path="interval-estimation.html"><a href="interval-estimation.html#interval-estimation-for-the-mean"><i class="fa fa-check"></i><b>13.4</b> Interval estimation for the mean</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="interval-estimation.html"><a href="interval-estimation.html#case-1-known-variance"><i class="fa fa-check"></i><b>13.4.1</b> Case 1 (known variance)</a></li>
<li class="chapter" data-level="13.4.2" data-path="interval-estimation.html"><a href="interval-estimation.html#confidence-level"><i class="fa fa-check"></i><b>13.4.2</b> Confidence level</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="interval-estimation.html"><a href="interval-estimation.html#marging-of-error-for-unkown-variance"><i class="fa fa-check"></i><b>13.5</b> Marging of error for unkown variance</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="interval-estimation.html"><a href="interval-estimation.html#theorem-t-statistic"><i class="fa fa-check"></i><b>13.5.1</b> Theorem (T-statistic)</a></li>
<li class="chapter" data-level="13.5.2" data-path="interval-estimation.html"><a href="interval-estimation.html#case-2-unknown-variance"><i class="fa fa-check"></i><b>13.5.2</b> Case 2 (unknown variance)</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="interval-estimation.html"><a href="interval-estimation.html#estimation-of-proportions"><i class="fa fa-check"></i><b>13.6</b> Estimation of proportions</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="interval-estimation.html"><a href="interval-estimation.html#case-3-proportions"><i class="fa fa-check"></i><b>13.6.1</b> Case 3 (proportions)</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="interval-estimation.html"><a href="interval-estimation.html#estimation-of-the-variance"><i class="fa fa-check"></i><b>13.7</b> Estimation of the variance</a></li>
<li class="chapter" data-level="13.8" data-path="interval-estimation.html"><a href="interval-estimation.html#confidence-interval-for-the-variance"><i class="fa fa-check"></i><b>13.8</b> Confidence interval for the variance</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="interval-estimation.html"><a href="interval-estimation.html#theorem-chi2"><i class="fa fa-check"></i><b>13.8.1</b> Theorem (<span class="math inline">\(\chi^2\)</span>):</a></li>
<li class="chapter" data-level="13.8.2" data-path="interval-estimation.html"><a href="interval-estimation.html#confidence-interval-for-the-variance-1"><i class="fa fa-check"></i><b>13.8.2</b> Confidence interval for the variance</a></li>
<li class="chapter" data-level="13.8.3" data-path="interval-estimation.html"><a href="interval-estimation.html#case-4-variance"><i class="fa fa-check"></i><b>13.8.3</b> Case 4 (variance)</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="interval-estimation.html"><a href="interval-estimation.html#questions-10"><i class="fa fa-check"></i><b>13.9</b> Questions</a></li>
<li class="chapter" data-level="13.10" data-path="interval-estimation.html"><a href="interval-estimation.html#exercises-11"><i class="fa fa-check"></i><b>13.10</b> Exercises</a></li>
<li class="chapter" data-level="13.11" data-path="interval-estimation.html"><a href="interval-estimation.html#practice-3"><i class="fa fa-check"></i><b>13.11</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>14</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="14.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#objective-9"><i class="fa fa-check"></i><b>14.1</b> Objective</a></li>
<li class="chapter" data-level="14.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis"><i class="fa fa-check"></i><b>14.2</b> Hypothesis</a></li>
<li class="chapter" data-level="14.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-1"><i class="fa fa-check"></i><b>14.3</b> Hypothesis testing</a></li>
<li class="chapter" data-level="14.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-1-known-variance-1"><i class="fa fa-check"></i><b>14.4</b> Case 1 (known variance)</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-test-with-a-confidence-interval"><i class="fa fa-check"></i><b>14.4.1</b> Hypothesis test with a confidence interval</a></li>
<li class="chapter" data-level="14.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-test-with-acceptancerejection-zones"><i class="fa fa-check"></i><b>14.4.2</b> Hypothesis test with acceptance/rejection zones</a></li>
<li class="chapter" data-level="14.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-test-with-a-p-value"><i class="fa fa-check"></i><b>14.4.3</b> Hypothesis test with a P-value</a></li>
<li class="chapter" data-level="14.4.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#upper-tail-hypothesis"><i class="fa fa-check"></i><b>14.4.4</b> Upper tail hypothesis</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-2-unknown-variance-1"><i class="fa fa-check"></i><b>14.5</b> Case 2 (unknown variance)</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#lower-tail-hypothesis"><i class="fa fa-check"></i><b>14.5.1</b> Lower tail hypothesis</a></li>
<li class="chapter" data-level="14.5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-with-large-n-and-any-distribution"><i class="fa fa-check"></i><b>14.5.2</b> Hypothesis testing with large n and any distribution</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-3-proportions-1"><i class="fa fa-check"></i><b>14.6</b> Case 3 (proportions)</a></li>
<li class="chapter" data-level="14.7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-4-variances"><i class="fa fa-check"></i><b>14.7</b> Case 4 (variances)</a></li>
<li class="chapter" data-level="14.8" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#errors-in-hypothesis-testing"><i class="fa fa-check"></i><b>14.8</b> Errors in hypothesis testing</a></li>
<li class="chapter" data-level="14.9" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercises-12"><i class="fa fa-check"></i><b>14.9</b> Exercises</a></li>
<li class="chapter" data-level="14.10" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#practice-4"><i class="fa fa-check"></i><b>14.10</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="contingency-tables.html"><a href="contingency-tables.html"><i class="fa fa-check"></i><b>15</b> Contingency tables</a>
<ul>
<li class="chapter" data-level="15.1" data-path="contingency-tables.html"><a href="contingency-tables.html#objective-10"><i class="fa fa-check"></i><b>15.1</b> Objective</a></li>
<li class="chapter" data-level="15.2" data-path="contingency-tables.html"><a href="contingency-tables.html#difference-between-proportions"><i class="fa fa-check"></i><b>15.2</b> Difference between proportions</a></li>
<li class="chapter" data-level="15.3" data-path="contingency-tables.html"><a href="contingency-tables.html#difference-between-proportions-1"><i class="fa fa-check"></i><b>15.3</b> Difference between proportions</a></li>
<li class="chapter" data-level="15.4" data-path="contingency-tables.html"><a href="contingency-tables.html#contingency-table-of-conditional-probabilities"><i class="fa fa-check"></i><b>15.4</b> Contingency table of conditional probabilities</a></li>
<li class="chapter" data-level="15.5" data-path="contingency-tables.html"><a href="contingency-tables.html#test-for-the-difference-between-proportions"><i class="fa fa-check"></i><b>15.5</b> Test for the difference between proportions</a></li>
<li class="chapter" data-level="15.6" data-path="contingency-tables.html"><a href="contingency-tables.html#chi2-test"><i class="fa fa-check"></i><b>15.6</b> <span class="math inline">\(\chi^2\)</span> test</a></li>
<li class="chapter" data-level="15.7" data-path="contingency-tables.html"><a href="contingency-tables.html#fishers-exact-test"><i class="fa fa-check"></i><b>15.7</b> Fisher’s exact test</a></li>
<li class="chapter" data-level="15.8" data-path="contingency-tables.html"><a href="contingency-tables.html#hypergeometric-distribution"><i class="fa fa-check"></i><b>15.8</b> Hypergeometric distribution</a></li>
<li class="chapter" data-level="15.9" data-path="contingency-tables.html"><a href="contingency-tables.html#difference-between-several-proportions"><i class="fa fa-check"></i><b>15.9</b> Difference between several proportions</a></li>
<li class="chapter" data-level="15.10" data-path="contingency-tables.html"><a href="contingency-tables.html#questions-11"><i class="fa fa-check"></i><b>15.10</b> Questions</a></li>
<li class="chapter" data-level="15.11" data-path="contingency-tables.html"><a href="contingency-tables.html#practice-5"><i class="fa fa-check"></i><b>15.11</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html"><i class="fa fa-check"></i><b>16</b> Mean differences between two samples</a>
<ul>
<li class="chapter" data-level="16.1" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#objective-11"><i class="fa fa-check"></i><b>16.1</b> Objective</a></li>
<li class="chapter" data-level="16.2" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#differece-in-means-between-two-groups"><i class="fa fa-check"></i><b>16.2</b> Differece in means between two groups</a></li>
<li class="chapter" data-level="16.3" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#data-1"><i class="fa fa-check"></i><b>16.3</b> Data</a></li>
<li class="chapter" data-level="16.4" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#difference-between-means"><i class="fa fa-check"></i><b>16.4</b> Difference between means</a></li>
<li class="chapter" data-level="16.5" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#hypothesis-test"><i class="fa fa-check"></i><b>16.5</b> Hypothesis test</a></li>
<li class="chapter" data-level="16.6" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#estiamtor-of-the-mean-difference"><i class="fa fa-check"></i><b>16.6</b> Estiamtor of the mean difference</a></li>
<li class="chapter" data-level="16.7" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#standardized-error"><i class="fa fa-check"></i><b>16.7</b> Standardized error</a></li>
<li class="chapter" data-level="16.8" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#standardized-error-for-the-null"><i class="fa fa-check"></i><b>16.8</b> Standardized error for the null</a></li>
<li class="chapter" data-level="16.9" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#mean-differences-when-n-is-small"><i class="fa fa-check"></i><b>16.9</b> Mean differences when <span class="math inline">\(n\)</span> is small</a></li>
<li class="chapter" data-level="16.10" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#data-2"><i class="fa fa-check"></i><b>16.10</b> Data</a></li>
<li class="chapter" data-level="16.11" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#difference-between-means-1"><i class="fa fa-check"></i><b>16.11</b> Difference between means</a></li>
<li class="chapter" data-level="16.12" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#hypothesis-test-1"><i class="fa fa-check"></i><b>16.12</b> Hypothesis test</a></li>
<li class="chapter" data-level="16.13" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#estimator-of-the-mean-difference"><i class="fa fa-check"></i><b>16.13</b> Estimator of the mean difference</a></li>
<li class="chapter" data-level="16.14" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#standardized-error-for-the-null-1"><i class="fa fa-check"></i><b>16.14</b> Standardized error for the null</a></li>
<li class="chapter" data-level="16.15" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#unequal-variances"><i class="fa fa-check"></i><b>16.15</b> Unequal variances</a></li>
<li class="chapter" data-level="16.16" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#questions-12"><i class="fa fa-check"></i><b>16.16</b> Questions</a></li>
<li class="chapter" data-level="16.17" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#practice-6"><i class="fa fa-check"></i><b>16.17</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html"><i class="fa fa-check"></i><b>17</b> Mean differences across several groups</a>
<ul>
<li class="chapter" data-level="17.1" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#objective-12"><i class="fa fa-check"></i><b>17.1</b> Objective</a></li>
<li class="chapter" data-level="17.2" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#different-means-among-several-conditions"><i class="fa fa-check"></i><b>17.2</b> Different means among several conditions</a></li>
<li class="chapter" data-level="17.3" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#data-3"><i class="fa fa-check"></i><b>17.3</b> Data</a></li>
<li class="chapter" data-level="17.4" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#difference-between-means-2"><i class="fa fa-check"></i><b>17.4</b> Difference between means</a></li>
<li class="chapter" data-level="17.5" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#hypothesis-test-2"><i class="fa fa-check"></i><b>17.5</b> Hypothesis test</a></li>
<li class="chapter" data-level="17.6" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>17.6</b> Analysis of variance (ANOVA)</a></li>
<li class="chapter" data-level="17.7" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#anova-for-two-groups"><i class="fa fa-check"></i><b>17.7</b> ANOVA for two groups</a></li>
<li class="chapter" data-level="17.8" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#linear-model"><i class="fa fa-check"></i><b>17.8</b> Linear model</a></li>
<li class="chapter" data-level="17.9" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#way-anova"><i class="fa fa-check"></i><b>17.9</b> 2-way ANOVA</a></li>
<li class="chapter" data-level="17.10" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#data-4"><i class="fa fa-check"></i><b>17.10</b> Data</a></li>
<li class="chapter" data-level="17.11" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#modeling-residuals"><i class="fa fa-check"></i><b>17.11</b> Modeling residuals</a></li>
<li class="chapter" data-level="17.12" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#linear-model-1"><i class="fa fa-check"></i><b>17.12</b> Linear model</a></li>
<li class="chapter" data-level="17.13" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#hypothesis-test-3"><i class="fa fa-check"></i><b>17.13</b> Hypothesis test</a></li>
<li class="chapter" data-level="17.14" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#variance-components"><i class="fa fa-check"></i><b>17.14</b> Variance components</a></li>
<li class="chapter" data-level="17.15" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#way-anova-with-interaction"><i class="fa fa-check"></i><b>17.15</b> 2-way ANOVA with interaction</a></li>
<li class="chapter" data-level="17.16" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#linear-model-2"><i class="fa fa-check"></i><b>17.16</b> Linear model</a></li>
<li class="chapter" data-level="17.17" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#hypothesis-test-4"><i class="fa fa-check"></i><b>17.17</b> Hypothesis test</a></li>
<li class="chapter" data-level="17.18" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#variance-components-1"><i class="fa fa-check"></i><b>17.18</b> Variance components</a></li>
<li class="chapter" data-level="17.19" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#questions-13"><i class="fa fa-check"></i><b>17.19</b> Questions</a></li>
<li class="chapter" data-level="17.20" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#practice-7"><i class="fa fa-check"></i><b>17.20</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>18</b> Regression and correlation</a>
<ul>
<li class="chapter" data-level="18.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#objective-13"><i class="fa fa-check"></i><b>18.1</b> Objective</a></li>
<li class="chapter" data-level="18.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlations"><i class="fa fa-check"></i><b>18.2</b> Correlations</a></li>
<li class="chapter" data-level="18.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#data-5"><i class="fa fa-check"></i><b>18.3</b> Data</a></li>
<li class="chapter" data-level="18.4" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#normal-bivariate"><i class="fa fa-check"></i><b>18.4</b> Normal bivariate</a></li>
<li class="chapter" data-level="18.5" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#estimators"><i class="fa fa-check"></i><b>18.5</b> Estimators</a></li>
<li class="chapter" data-level="18.6" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-coefficient"><i class="fa fa-check"></i><b>18.6</b> Correlation coefficient</a></li>
<li class="chapter" data-level="18.7" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#hypothesis-contrast"><i class="fa fa-check"></i><b>18.7</b> Hypothesis contrast</a></li>
<li class="chapter" data-level="18.8" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#regression-analysis"><i class="fa fa-check"></i><b>18.8</b> Regression analysis</a></li>
<li class="chapter" data-level="18.9" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-model-3"><i class="fa fa-check"></i><b>18.9</b> Linear model</a></li>
<li class="chapter" data-level="18.10" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#hypothesis-contrast-1"><i class="fa fa-check"></i><b>18.10</b> Hypothesis contrast</a></li>
<li class="chapter" data-level="18.11" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#estimators-1"><i class="fa fa-check"></i><b>18.11</b> Estimators</a></li>
<li class="chapter" data-level="18.12" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#hypothesis-testing-2"><i class="fa fa-check"></i><b>18.12</b> Hypothesis testing</a></li>
<li class="chapter" data-level="18.13" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#stratified-analysis"><i class="fa fa-check"></i><b>18.13</b> Stratified analysis</a></li>
<li class="chapter" data-level="18.14" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#multiple-regression"><i class="fa fa-check"></i><b>18.14</b> Multiple Regression</a></li>
<li class="chapter" data-level="18.15" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#multiple-regression-interaction"><i class="fa fa-check"></i><b>18.15</b> Multiple Regression interaction</a></li>
<li class="chapter" data-level="18.16" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#model-diagnostics"><i class="fa fa-check"></i><b>18.16</b> Model diagnostics</a></li>
<li class="chapter" data-level="18.17" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#questions-14"><i class="fa fa-check"></i><b>18.17</b> Questions</a></li>
<li class="chapter" data-level="18.18" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#practice-8"><i class="fa fa-check"></i><b>18.18</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="group-work-sessions.html"><a href="group-work-sessions.html"><i class="fa fa-check"></i><b>19</b> Group Work sessions</a>
<ul>
<li class="chapter" data-level="19.1" data-path="group-work-sessions.html"><a href="group-work-sessions.html#objectives"><i class="fa fa-check"></i><b>19.1</b> Objectives</a></li>
<li class="chapter" data-level="19.2" data-path="group-work-sessions.html"><a href="group-work-sessions.html#misophonia-dataset"><i class="fa fa-check"></i><b>19.2</b> Misophonia dataset</a></li>
<li class="chapter" data-level="19.3" data-path="group-work-sessions.html"><a href="group-work-sessions.html#group-work-session-1-data-description"><i class="fa fa-check"></i><b>19.3</b> Group Work session 1: Data description</a></li>
<li class="chapter" data-level="19.4" data-path="group-work-sessions.html"><a href="group-work-sessions.html#group-work-session-2-inference"><i class="fa fa-check"></i><b>19.4</b> Group Work session 2: Inference</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="solutions-to-questions.html"><a href="solutions-to-questions.html"><i class="fa fa-check"></i><b>20</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="20.1" data-path="solutions-to-questions.html"><a href="solutions-to-questions.html#summary-of-probability-models-1"><i class="fa fa-check"></i><b>20.1</b> Summary of probability models</a></li>
<li class="chapter" data-level="20.2" data-path="solutions-to-questions.html"><a href="solutions-to-questions.html#python-functions-of-probability-models-1"><i class="fa fa-check"></i><b>20.2</b> Python functions of probability models</a></li>
<li class="chapter" data-level="20.3" data-path="solutions-to-questions.html"><a href="solutions-to-questions.html#summary-of-hypothesis"><i class="fa fa-check"></i><b>20.3</b> Summary of hypothesis</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-description" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Data description<a href="data-description.html#data-description" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we will introduce tools for describing data.</p>
<p>We will do so using tables, figures, and descriptive statistics of central tendency and dispersion.</p>
<p>We will also introduce key concepts in statistics such as random experiments, observations, outcomes, and absolute and relative frequencies.</p>
<div id="scientific-method" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Scientific method<a href="data-description.html#scientific-method" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the goals of the scientific method is to provide a framework for solving problems that arise in the study of natural phenomena or in the design of new technologies.</p>
<p>Modern humans have developed a <strong>method</strong> over thousands of years that is still in development.</p>
<p>The method has three main human activities:</p>
<ul>
<li><em>Observation</em> characterized by the acquisition of <strong>data</strong></li>
<li><em>Reason</em> characterized by the development of mathematical <strong>models</strong></li>
<li><em>Action</em> characterized by the development of new <strong>experiments</strong> (technology)</li>
</ul>
<p>Their complex interaction and results are the basis of <em>scientific activity</em>.</p>
<p><img src="figures/stats.JPG" /></p>
<p><strong>Statistics</strong> deals with the interaction between <em>models</em> and <em>data</em> (the bottom part of the figure).</p>
<p>The statistical questions are:</p>
<ul>
<li>What is the best model for my data (inference)?</li>
<li>What are the data that a certain model (prediction) would produce?</li>
</ul>
</div>
<div id="data" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Data<a href="data-description.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The data is presented in the form of observations.</p>
<p>An <strong>observation</strong> or <strong>realization</strong> is the acquisition of a number or characteristic from an experimental run.</p>
<p>For example, let’s take the series of numbers produced by repeating an experiment (1: success, 0: failure).</p>
<p>… 1 0 0 1 0 <strong>1</strong> 0 1 1 …</p>
<p>The number in bold is <strong>an observation</strong> from a repeat of the experiment.Remember that the observation is <strong>concrete</strong> is the number you get one day in the laboratory. An observation is a particular entity.</p>
<p>By contrast, an <strong>outcome</strong> is a <strong>possible</strong> observation that could result from the experiment.</p>
<p>In the example, <strong>1</strong> is one possible result, <strong>0</strong> is the other possible result of the experiment. The outcome of an experiment is <strong>abstract</strong>. You can obtain them by reasoning, no need to go to the lab. As such, the outcomes are characteristics of the experiments you are running. An outcome is a universal entity.</p>
</div>
<div id="result-types" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Result types<a href="data-description.html#result-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In statistics we are mainly interested in two types of outcomes.</p>
<ul>
<li><p><strong>Categorical</strong>: If the outcome of an experiment is a quality. They can be nominal (binary: yes, no; multiple: colors) or ordinal, when the qualities can be ranked (severity of a disease, emergency grades).</p></li>
<li><p><strong>Numeric</strong>: If the outcome of an experiment is a number. The number can be discrete (number of emails received in an hour, number of leukocytes in the blood) or continuous (battery charge status, engine temperature).</p></li>
</ul>
</div>
<div id="random-experiments" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Random experiments<a href="data-description.html#random-experiments" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We may boldly say that the subject matter of statistics is to gain knowledge from random experiments, the means by which we produce data.</p>
<p><strong>Definition:</strong></p>
<p>A <strong>random experiment</strong> is an experiment that gives a different result when repeated in the same way.</p>
<p>Random experiments are of different types, depending on how they are conducted:</p>
<ul>
<li>on the same object (person): temperature, sugar levels.</li>
<li>on different objects (animals): the weight of an animal.</li>
<li>on events (climate phenomena): the number of hurricanes per year.</li>
</ul>
</div>
<div id="absolute-frequencies" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Absolute frequencies<a href="data-description.html#absolute-frequencies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we repeat a random experiment with <strong>categorical</strong> outcomes, we make a list of the results.</p>
<p>We summarize the observations by counting how many times we saw a particular outcome.</p>
<p>The <strong>absolute frequency</strong>:</p>
<p><span class="math display">\[n_i\]</span></p>
<p>is the number of times we observe the result <span class="math inline">\(i\)</span>.</p>
<p><strong>Example (leukocytes)</strong></p>
<p>Consider the following random experiment. Let’s extract one leukocyte from a blood sample of one donor and write down its type. Let’s repeat the experiment <span class="math inline">\(N=119\)</span> times.</p>
<pre><code>(T cell, T cell, Neutrophil, ..., B cell)</code></pre>
<p>The second <strong>T cell</strong> in bold is the second observation (extraction). The last <strong>B cell</strong> is observation number <span class="math inline">\(119\)</span>.</p>
<p>We can list the observations using a <strong>frequency table</strong> of the outcomes (categories):</p>
<pre><code>##      outcome ni
## 1     T Cell 34
## 2     B cell 50
## 3   basophil 20
## 4   Monocyte  5
## 5 Neutrophil 10</code></pre>
<p>The table is putting together the outcomes (first column) and the observations (second column). From the table, we can say that, for example, <span class="math inline">\(n_1=34\)</span> is the total number of T cells observed in the repetition of the experiment. We also note that the total number of repetitions is <span class="math display">\[\sum_{i=1}^M n_i= N = 119\]</span>, where <span class="math inline">\(M\)</span> is the number of outcomes (number of rows in the table) and <span class="math inline">\(N\)</span> the number of observations (repetitions of the random experiment). The table may be regarded as the immune profile of the donor.</p>
</div>
<div id="relative-frequencies" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Relative frequencies<a href="data-description.html#relative-frequencies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can also summarize the observations by calculating the <strong>proportion</strong> of how many times we saw a particular result.</p>
<p><span class="math display">\[f_i = \frac{n_i}{N}\]</span></p>
<p>In our example, <span class="math inline">\(n_1=34\)</span> T cells were recorded, so we can ask about the proportion of T cells from the total number of leukocytes observed: <span class="math inline">\(119\)</span>. We can copy these proportions <span class="math inline">\(f_i\)</span> in the frequency table.</p>
<pre><code>##      outcome ni         fi
## 1     T Cell 34 0.28571429
## 2     B cell 50 0.42016807
## 3   basophil 20 0.16806723
## 4   Monocyte  5 0.04201681
## 5 Neutrophil 10 0.08403361</code></pre>
<p>Relative frequencies are <strong>fundamental</strong> in statistics. They give the proportion of one outcome in relation to the other outcomes. Later we will understand them as the observations of probabilities; or more accurately probability estimators.</p>
<p>For absolute and relative frequencies we have the properties</p>
<p><span class="math display">\[\sum_{i=1}^M n_i = N\]</span></p>
<p>and</p>
<p><span class="math display">\[\sum_{i=1}^M f_i = 1\]</span></p>
<p>where <span class="math inline">\(M\)</span> is the number of outcomes.</p>
</div>
<div id="bar-chart" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Bar chart<a href="data-description.html#bar-chart" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we have a lot of outcomes and want to see which ones are most likely, we can use a bar chart. This is a plot of the frequencies <span class="math inline">\(n_i\)</span> Vs the outcomes <span class="math inline">\(i\)</span>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="pie-chart-pie" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Pie chart (pie)<a href="data-description.html#pie-chart-pie" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can also visualize the relative frequencies <span class="math inline">\(f_i\)</span> using a pie chart.</p>
<p>In the pie chart, the area of the circle represents the 100% of the observations (proportion = 1) and the sections represent the relative frequencies of each outcome.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="ordinal-categorical-outcomes" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Ordinal categorical outcomes<a href="data-description.html#ordinal-categorical-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The leukocyte type in the examples above is a <strong>categorical</strong> nominal variable. Each observation belongs to a category (quality). The categories do not always have a certain order.</p>
<p>Sometimes <strong>categorical</strong> outcomes can be <strong>sorted</strong> when they have a natural ranking. This allows you to compute <strong>cumulative frequencies</strong>.</p>
<p><strong>Example (misophonia)</strong></p>
<p>This is a clinical study on <span class="math inline">\(123\)</span> patients who were examined for their degree of misophonia. Misophnia is uncontrolled anxiety/anger produced by particular sounds.</p>
<p>Each patient was evaluated with a questionnaire (AMISO) and they were classified into 4 different groups according to severity.</p>
<p>The results of the study are</p>
<pre><code>##   [1] 4 2 0 3 0 0 2 3 0 3 0 2 2 0 2 0 0 3 3 0 3 3 2 0 0 0 4 2 2 0 2 0 0 0 3 0 2
##  [38] 3 2 2 0 2 3 0 0 2 2 3 3 0 0 4 3 3 2 0 2 0 0 0 2 2 0 0 2 3 0 1 3 2 4 3 2 3
##  [75] 0 2 3 2 4 1 2 0 2 0 2 0 2 2 4 3 0 3 0 0 0 2 2 1 3 0 0 3 2 1 3 0 4 4 2 3 3
## [112] 3 0 3 2 1 2 3 3 4 2 3 2</code></pre>
<p>Each observation is the result of the run of one particular random experiment: the measurement of the level of misophonia in a patient. This data series can be summarized using the frequency table</p>
<pre><code>##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073</code></pre>
<p>About <span class="math inline">\(25\%\)</span> of the patients had misophonia grade 3. Note that the rows of table are <strong>ordered</strong> by the severity of the disease.</p>
</div>
<div id="absolute-and-relative-cumulative-frequencies" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> Absolute and relative cumulative frequencies<a href="data-description.html#absolute-and-relative-cumulative-frequencies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>misophonia severity is <strong>categorical</strong> <strong>ordinal</strong> because its outcomes can be meaningfully ordered by their degree.</p>
<p>When the outcomes of a random experiment can be ordered, it is useful to ask how many observations were obtained up to a given outcome. We call this number the <strong>absolute cumulative frequency</strong> up to the outcome <span class="math inline">\(i\)</span>, and compute it with sum the relative frequencies up to <span class="math inline">\(i\)</span>
<span class="math display">\[N_i =\sum_{k= 1}^i n_k\]</span>
It is also useful to calculate the <strong>proportion</strong> of observations up to a given result.</p>
<p><span class="math display">\[F_i =\sum_{k= 1}^i f_k\]</span>
This is called the <strong>relative cumulative frequency</strong>, or <strong>frequency distribution</strong> of the data.</p>
<p>We can add these frequencies to the <strong>frequency table</strong></p>
<pre><code>##   outcome ni         fi  Ni        Fi
## 0       0 41 0.33333333  41 0.3333333
## 1       1  5 0.04065041  46 0.3739837
## 2       2 37 0.30081301  83 0.6747967
## 3       3 31 0.25203252 114 0.9268293
## 4       4  9 0.07317073 123 1.0000000</code></pre>
<p>Therefore, <strong>67%</strong> of patients had misophonia up to severity <strong>2</strong>, and <strong>37%</strong> of patients had severity less than or equal to <strong>1</strong>.</p>
</div>
<div id="cumulative-frequency-graph" class="section level2 hasAnchor" number="2.11">
<h2><span class="header-section-number">2.11</span> Cumulative frequency graph<a href="data-description.html#cumulative-frequency-graph" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><span class="math inline">\(F_i\)</span> is an important quantity because it allows us to define the accumulation of frequencies up to <strong>intermediate</strong> levels of the outcomes.</p>
<p>The frequency up to an intermediate level <span class="math inline">\(x\)</span> (<span class="math inline">\(i\leq x&lt; i+1\)</span>) is just the accumulation up to the lower possible outcome of the experiment <span class="math display">\[F_x = F_i\]</span></p>
<p><span class="math inline">\(F_x\)</span> is therefore a function on a <strong>continuous</strong> range of values. We can draw it with respect to the outcomes</p>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Therefore, we can say that <strong>67%</strong> of the patients had misophonia up to severity <span class="math inline">\(2.3\)</span>, although <span class="math inline">\(2.3\)</span> is not an observed outcome.</p>
</div>
<div id="numerical-outcomes" class="section level2 hasAnchor" number="2.12">
<h2><span class="header-section-number">2.12</span> Numerical outcomes<a href="data-description.html#numerical-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The result of a random experiment can produce a number. If the number is <strong>discrete</strong>, we can generate a frequency table, with absolute, relative, and cumulative frequencies, and illustrate them with bar, pie, and cumulative charts.</p>
<p>When the outcome is <strong>continuous</strong> the frequency table is not so useful, because it is unlikely to obtain a repetition of the same measurement.</p>
<p><strong>Example (misophonia)</strong></p>
<p>The researchers wondered if the convexity of the jaw would affect the severity of misophonia. The scientific hypothesis is that the angle of convexity of the jaw can influence hearing and its sensitivity. These are the mandibular convexity observations in degrees for each patient:</p>
<pre><code>##   [1]  7.97 18.23 12.27  7.81  9.81 13.50 19.30  7.70 12.30  7.90 12.60 19.00
##  [13]  7.27 14.00  5.40  8.00 11.20  7.75  7.94 16.69  7.62  7.02  7.00 19.20
##  [25]  7.96 14.70  7.24  7.80  7.90  4.70  4.40 14.00 14.40 16.00  1.40  9.76
##  [37]  7.90  7.90  7.40  6.30  7.76  7.30  7.00 11.23 16.00  7.90  7.29  6.91
##  [49]  7.10 13.40 11.60 -1.00  6.00  7.82  4.80 11.00  9.00 11.50 16.00 15.00
##  [61]  1.40 16.80  7.70 16.14  7.12 -1.00 17.00  9.26 18.70  3.40 21.30  7.50
##  [73]  6.03  7.50 19.00 19.01  8.10  7.80  6.10 15.26  7.95 18.00  4.60 15.00
##  [85]  7.50  8.00 16.80  8.54  7.00 18.30  7.80 16.00 14.00 12.30 11.40  8.50
##  [97]  7.00  7.96 17.60 10.00  3.50  6.70 17.00 20.26  6.64  1.80  7.02  2.46
## [109] 19.00 17.86  6.10  6.64 12.00  6.60  8.70 14.05  7.20 19.70  7.70  6.02
## [121]  2.50 19.00  6.80</code></pre>
<p>while, in these set of observations, we see the repetition of the convexity degree <span class="math inline">\(7.90\)</span>, this is a result of measurement rounding or limited instrument resolution. Degrees are continuous and it is unlikely that to patients have the same value of convexity, if we had sufficient resolution.</p>
</div>
<div id="transforming-continuous-data" class="section level2 hasAnchor" number="2.13">
<h2><span class="header-section-number">2.13</span> Transforming continuous data<a href="data-description.html#transforming-continuous-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Since observations of continuous outcomes cannot be counted in frequencies (at least by definition), we may transform them into ordered categorical outcomes.</p>
<ol style="list-style-type: decimal">
<li>First we cover the range of observations in regular intervals of the same size (bins)</li>
</ol>
<pre><code>## [1] &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Then we map each observation to its interval: creating a categorical <strong>ordered</strong> outcomes; in this case we have 5 possible outcomes</li>
</ol>
<pre><code>##   [1] &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot; 
##   [6] &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot; 
##  [11] &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [16] &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot; 
##  [21] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot; 
##  [26] &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [31] &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;[-1.02,3.46]&quot;
##  [36] &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [41] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot; 
##  [46] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot; 
##  [51] &quot;(7.92,12.4]&quot;  &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [56] &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot; 
##  [61] &quot;[-1.02,3.46]&quot; &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [66] &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;[-1.02,3.46]&quot;
##  [71] &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot; 
##  [76] &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot; 
##  [81] &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [86] &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot; 
##  [91] &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot; 
##  [96] &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot; 
## [101] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot; 
## [106] &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(16.8,21.3]&quot; 
## [111] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot; 
## [116] &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
## [121] &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;</code></pre>
<p>Therefore, instead of saying that the first patient had an angle of convexity of <span class="math inline">\(7.97\)</span>, we say that his angle was in the interval (or <strong>bin</strong>) between <span class="math inline">\((7.92,12.4]\)</span>.</p>
<p>No other patients had an angle of <span class="math inline">\(7.97\)</span> degrees, but many had angles between <span class="math inline">\((7.92,12.4]\)</span>.</p>
</div>
<div id="frequency-table-for-a-continuous-variable" class="section level2 hasAnchor" number="2.14">
<h2><span class="header-section-number">2.14</span> Frequency table for a continuous variable<a href="data-description.html#frequency-table-for-a-continuous-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For a given regular partition of the range of the continuous outcomes into intervals, we can produce a frequency table as before</p>
<pre><code>##        outcome ni         fi  Ni         Fi
## 1 [-1.02,3.46]  8 0.06504065   8 0.06504065
## 2  (3.46,7.92] 51 0.41463415  59 0.47967480
## 3  (7.92,12.4] 26 0.21138211  85 0.69105691
## 4  (12.4,16.8] 20 0.16260163 105 0.85365854
## 5  (16.8,21.3] 18 0.14634146 123 1.00000000</code></pre>
</div>
<div id="histogram" class="section level2 hasAnchor" number="2.15">
<h2><span class="header-section-number">2.15</span> Histogram<a href="data-description.html#histogram" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The histogram is the graph of <span class="math inline">\(n_i\)</span> or <span class="math inline">\(f_i\)</span> Vs the interval outcomes (bins). The histogram depends on the size of the bin.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>This is a histogram with 20 bins .</p>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>We see that most people have angles in the interval <span class="math inline">\((7, 8]\)</span>.</p>
</div>
<div id="cumulative-frequency-graph-1" class="section level2 hasAnchor" number="2.16">
<h2><span class="header-section-number">2.16</span> Cumulative frequency graph<a href="data-description.html#cumulative-frequency-graph-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can also plot <span class="math inline">\(F_x\)</span> against the outcomes. Since <span class="math inline">\(F_x\)</span> has a continuous range, we can order the observations (<span class="math inline">\(x_1 &lt;... x_j &lt; x_{j+1} &lt; x_n\)</span>) and therefore</p>
<p><span class="math display">\[F_x = \frac{k}{ n}\]</span></p>
<p>for <span class="math inline">\(x_{k} \leq x &lt; x_{k+ 1}\)</span> .</p>
<p><span class="math inline">\(F_x\)</span> is known as the <strong>distribution</strong> of the data. <span class="math inline">\(F_x\)</span> does not depend on the size of the bin. However, its <strong>resolution</strong> depends on the amount of data.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="summary-statistics" class="section level2 hasAnchor" number="2.17">
<h2><span class="header-section-number">2.17</span> Summary Statistics<a href="data-description.html#summary-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Summary statistics are numbers calculated from the data that tell us important characteristics of the numerical outcomes (discrete or continuous).</p>
<p>For example, we have statistics that describe extreme values:</p>
<ul>
<li><strong>minimum</strong>: the minimum observation.</li>
<li><strong>maximum</strong>: the maximum observation.</li>
</ul>
</div>
<div id="average-sample-mean" class="section level2 hasAnchor" number="2.18">
<h2><span class="header-section-number">2.18</span> Average (sample mean)<a href="data-description.html#average-sample-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>An important statistic that describes the central value of the observations (where to expect most observations) is the <strong>average</strong></p>
<p><span class="math display">\[\bar{x}=\frac{1}{N} \sum_{j=1}^N x_j\]</span></p>
<p>where <span class="math inline">\(x_j\)</span> is the <strong>observation</strong> <span class="math inline">\(j\)</span> from a total of <span class="math inline">\(N\)</span> observations. We also call the average the <strong>sample mean</strong>. The sample is the set of observations, or the data obtained from the repetition of the random experiment.</p>
<p><strong>Example (misophonia)</strong></p>
<p>The average convexity can be calculated directly from the <strong>observations</strong> in the usual way</p>
<p><span class="math inline">\(\bar{x}= \frac{1}{ N}\sum_j x_j\)</span></p>
<p></br>
<span class="math inline">\(= \frac{1}{123}( 7.97 + 18.23 + 12.27... + 6.80) = 10.19894\)</span></p>
<p>For <strong>categorically ordered</strong> outcomes, we can <strong>also</strong> use the relative frequencies to calculate the average</p>
<p><br>
<span class="math inline">\(\bar{x}=\frac{1}{ N}\sum_{i=1}^N x_j =\frac{1}{N}\sum_{i=1}^M x_i n_ {i}=\)</span>
<br>
<span class="math display">\[\sum_{i=1}^M x_i f_{i}\]</span></p>
<p>where we went from adding <span class="math inline">\(N\)</span> <strong>observations</strong> to adding <span class="math inline">\(M\)</span> <strong>outcomes</strong>.</p>
<p>The form <span class="math inline">\(\bar{x}= \sum_{i = 1}^M x_i f_i\)</span> shows that the average is the <strong>center of mass</strong> of the data. As if each observation had a mass density given by <span class="math inline">\(f_i\)</span>.</p>
<p><strong>Example (misophonia)</strong></p>
<p>The average <strong>severity</strong> of misophonia in the study can be calculated from the relative frequencies of the <strong>outcomes</strong></p>
<pre><code>##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073</code></pre>
<p><br>
<span class="math inline">\(\bar{x}=0\times f_ {0}+ 1\times f_{1}+2 \times f_{2}+3 \times f_{3}+4 \times f_{4}=1.691057\)</span></p>
<p>The average is also the center of mass for continuous outcomes; that is, the point where the relative frequencies of the bins balance.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="median" class="section level2 hasAnchor" number="2.19">
<h2><span class="header-section-number">2.19</span> Median<a href="data-description.html#median" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Another measure of centrality is the median. The median <span class="math inline">\(x_m\)</span>, or <span class="math inline">\(q_{0.5}\)</span>, is the value below which we find half of the observations. When we order the observations <span class="math inline">\(x_1 &lt;... x_j &lt; x_{j+1} &lt; x_N\)</span>, we count them until we find half of them, then we report that value <span class="math inline">\(x_m\)</span>. Therefore, <span class="math inline">\(x_m\)</span> is the observation such that <span class="math inline">\(m\)</span> satisfies</p>
<p><span class="math display">\[\sum_{i\leq m} 1 = \frac{N}{2}\]</span>
<strong>Example (misophonia)</strong></p>
<p>If we order the angles of convexity and cut them in half, we see that <span class="math inline">\(62\)</span> observations (individuals) (<span class="math inline">\(N/2 \sim 123/2\)</span>) are below <span class="math inline">\(7.96\)</span>. The <strong>median convexity</strong> is therefore <span class="math inline">\(q_{0.5}= x_{62}=7.96\)</span></p>
<pre><code>##  [1] -1.00 -1.00  1.40  1.40  1.80  2.46  2.50  3.40  3.50  4.40  4.60  4.70
## [13]  4.80  5.40  6.00  6.02  6.03  6.10  6.10  6.30  6.60  6.64  6.64  6.70
## [25]  6.80  6.91  7.00  7.00  7.00  7.00  7.02  7.02  7.10  7.12  7.20  7.24
## [37]  7.27  7.29  7.30  7.40  7.50  7.50  7.50  7.62  7.70  7.70  7.70  7.75
## [49]  7.76  7.80  7.80  7.80  7.81  7.82  7.90  7.90  7.90  7.90  7.90  7.94
## [61]  7.95  7.96</code></pre>
<pre><code>##  [1]  7.96  7.97  8.00  8.00  8.10  8.50  8.54  8.70  9.00  9.26  9.76  9.81
## [13] 10.00 11.00 11.20 11.23 11.40 11.50 11.60 12.00 12.27 12.30 12.30 12.60
## [25] 13.40 13.50 14.00 14.00 14.00 14.05 14.40 14.70 15.00 15.00 15.26 16.00
## [37] 16.00 16.00 16.00 16.14 16.69 16.80 16.80 17.00 17.00 17.60 17.86 18.00
## [49] 18.23 18.30 18.70 19.00 19.00 19.00 19.00 19.01 19.20 19.30 19.70 20.26
## [61] 21.30</code></pre>
<p>We thus cut the data at</p>
<pre><code>## [1] 7.96</code></pre>
<p>to split them in half.</p>
<p>In terms of frequencies, <span class="math inline">\(q_{0.5}\)</span> makes the cumulative frequency <span class="math inline">\(F_x\)</span> equal to <span class="math inline">\(0.5\)</span></p>
<p><span class="math display">\[\sum_{i = 1}^m f_i =F_{q_{0.5}}=0.5\]</span>
that is</p>
<p><span class="math display">\[q_{ 0.5}= F^{-1}(0.5)\]</span></p>
<p>This last equation means that, in the distribution graph, the median <span class="math inline">\(q_{ 0.5}\)</span> is the value of <span class="math inline">\(x\)</span> at which we have climbed half of the total height of <span class="math inline">\(F_x\)</span>. We have accumulated half of the observations.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>The average and median are not always the same.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="dispersion" class="section level2 hasAnchor" number="2.20">
<h2><span class="header-section-number">2.20</span> Dispersion<a href="data-description.html#dispersion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Other important summary statistics for observations are the <strong>spread</strong> statistics.</p>
<p>Many experiments may share their average, but differ in how <strong>sparse</strong> the values are.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
<p>The dispersion of the observations is a measure of the <strong>noise</strong> or randomness of the experiment. If there is no spread, the random experiment gives always the same outcome and there is no need to learn statistics.</p>
</div>
<div id="sample-variance" class="section level2 hasAnchor" number="2.21">
<h2><span class="header-section-number">2.21</span> Sample variance<a href="data-description.html#sample-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The dispersion about the average is measured by the sample variance</p>
<p><span class="math display">\[s^2=\frac{ 1}{ N-1} \sum_{j=1}^N ( x_j -\bar{x})^2\]</span></p>
<p>This number measures the average squared distance of the <strong>observations</strong> from the average. The reason for <span class="math inline">\(N-1\)</span> will be explained when we talk about inference, when we study the spread of <span class="math inline">\(\bar{x}\)</span>, as well as the spread of the observations.</p>
<p>In terms of the frequencies of the outcomes that are <strong>categorical and ordered</strong>, we can <strong>also</strong> calculate the sample variance as</p>
<p><span class="math display">\[s^2=\frac{N}{N-1} \sum_{i=1}^M (x_i -\bar{x})^2 f_i\]</span></p>
<p>Take many observations and then make <span class="math inline">\(N/(N+1)\)</span> close to <span class="math inline">\(a\)</span>, then <span class="math inline">\(s^2\)</span> can be considered as the <strong>moment of inertia</strong> about the average of the observations.</p>
<p>The square root of the sample variance, <span class="math inline">\(s\)</span>, is called <strong>standard deviation</strong> of the sample.</p>
<p><strong>Example (misophonia)</strong></p>
<p>The standard deviation of the convexity angle is</p>
<p><span class="math inline">\(s= [\frac{ 1}{123-1}((7.97-10.19894)^2+ (18.23-10.19894)^2\)</span>
<span class="math display">\[+ (12.27-10.19894 )^ 2 + ...)]^{1/2} = 5.086707\]</span></p>
<p>The jaw convexity deviates from its average by <span class="math inline">\(5.086707\)</span>.</p>
</div>
<div id="interquartile-range-iqr" class="section level2 hasAnchor" number="2.22">
<h2><span class="header-section-number">2.22</span> Interquartile range (IQR)<a href="data-description.html#interquartile-range-iqr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The spread of the data can also be measured with respect to the median using the <strong>interquartile range</strong>:</p>
<ol style="list-style-type: decimal">
<li>We define the <strong>first</strong> quartile as the value <span class="math inline">\(x\)</span> that makes the cumulative frequency <span class="math inline">\(F_{q_{0.25}}\)</span> equal to <span class="math inline">\(0.25\)</span>, or the value of <span class="math inline">\(x\)</span> where we have accumulated a quarter of the observations, or the value that splits the first quarter of the observations.</li>
</ol>
<p><span class="math display">\[q_{0.25}=F^{-1}(0.25)\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>We define the <strong>third</strong> quartile as the value <span class="math inline">\(x\)</span> that makes the cumulative frequency <span class="math inline">\(F_{q_{0.75}}\)</span> equal to <span class="math inline">\(0.75\)</span>, or the value of <span class="math inline">\(x\)</span> where we have accumulated three quarters of observations.</li>
</ol>
<p><span class="math display">\[q_{0.75}=F^{-1}(0.75)\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>The <strong>interquartile range</strong> (IQR) is <span class="math display">\[IQR=q_{0.75} - q_{0.25}\]</span></li>
</ol>
<p>This is the distance between the third and first quartiles and captures the central <span class="math inline">\(50\%\)</span> of the observations</p>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="boxplot" class="section level2 hasAnchor" number="2.23">
<h2><span class="header-section-number">2.23</span> Boxplot<a href="data-description.html#boxplot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The interquartile range, median, and <span class="math inline">\(5\%\)</span> and <span class="math inline">\(95\%\)</span> of the data can be displayed in a <strong>box plot</strong>.</p>
<p>In the boxplot, the values of the outcomes are on the y-axis. The IQR is the box, the median is the middle line, and the whiskers mark the <span class="math inline">\(5\%\)</span> and <span class="math inline">\(95\%\)</span> of the data.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
<div id="questions" class="section level2 hasAnchor" number="2.24">
<h2><span class="header-section-number">2.24</span> Questions<a href="data-description.html#questions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>1)</strong> In the following boxplot, the first quartile and second quartile of the data are:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\((-1.00, 21.30)\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\((-1.00, 7.02)\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\((7.02, 7.96)\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\((7.02, 14.22)\)</span></p>
<p><img src="figures/box.png" /></p>
<p><strong>2)</strong> The main disadvantage of a histogram is that:</p>
<p><strong><span class="math inline">\(\qquad\)</span> a :</strong> Depends on the size of the bin ; <strong><span class="math inline">\(\qquad\)</span>b :</strong> Cannot be used for categorical outcome;
<strong><span class="math inline">\(\qquad\)</span> c :</strong> Cannot be used when the bin size is small;
<strong><span class="math inline">\(\qquad\)</span> d :</strong> Used only for relative frequencies;</p>
<p><strong>3)</strong> If the relative cumulative frequencies of a random experiment with outcomes <span class="math inline">\(\{1,2,3,4\}\)</span> are: <span class="math inline">\(F(1)=0.15, \qquad F(2)=0.60, \qquad F(3)=0.85, \qquad F(4)=1\)</span>.</p>
<p>Then the relative frequency for the outcome <span class="math inline">\(3\)</span> is</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\(0.15\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\(0.85\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\(0.45\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\(0.25\)</span></p>
<p><strong>4)</strong> In a sample of size <span class="math inline">\(10\)</span> from a random experiment we obtained the following data:</p>
<p><span class="math inline">\(8, \qquad 3, \qquad 3, \qquad 7, \qquad 3, \qquad 6, \qquad 5, \qquad 10, \qquad 3, \qquad 8\)</span>.</p>
<p>The first quartile of the data is:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\(3.5\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\(4\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\(5\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\(3\)</span></p>
<p><strong>5)</strong> Imagine that we collect data for two quantities that are not mutually exclusive, for example, the gender and nationality of passengers on a flight. If we want to make a single pie chart for the data, which of these statements is true?</p>
<p><strong><span class="math inline">\(\qquad\)</span>a :</strong> We can <strong>only</strong> make a nationality pie chart because it has more than two possible outcomes;</p>
<p><strong><span class="math inline">\(\qquad\)</span>b :</strong> We can make a pie graph for a new variable marking gender <strong>and</strong> nationality;</p>
<p><strong><span class="math inline">\(\qquad\)</span>c :</strong> We can make a pie chart for the variable sex <strong>or</strong> the variable nationality;</p>
<p><strong><span class="math inline">\(\qquad\)</span>d :</strong> We can only choose <strong>whether</strong> to make a pie chart for gender <strong>or</strong> a pie chart for nationality.</p>
</div>
<div id="exercises" class="section level2 hasAnchor" number="2.25">
<h2><span class="header-section-number">2.25</span> Exercises<a href="data-description.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-1" class="section level4 hasAnchor" number="2.25.0.1">
<h4><span class="header-section-number">2.25.0.1</span> Exercise 1<a href="data-description.html#exercise-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have performed an experiment 8 times with the following results</p>
<pre><code>## [1]  3  3 10  2  6 11  5  4</code></pre>
<p>Answer the following questions:</p>
<ul>
<li>Calculate the relative frequencies of each result.</li>
<li>Calculate the cumulative frequencies of each result.</li>
<li>What is the average of the observations?</li>
<li>What is the median?</li>
<li>What is the third quartile?</li>
<li>What is the first quartile?</li>
</ul>
</div>
<div id="exercise-2" class="section level4 hasAnchor" number="2.25.0.2">
<h4><span class="header-section-number">2.25.0.2</span> Exercise 2<a href="data-description.html#exercise-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have performed an experiment 10 times with the following results</p>
<pre><code>##  [1] 2.875775 7.883051 4.089769 8.830174 9.404673 0.455565 5.281055 8.924190
##  [9] 5.514350 4.566147</code></pre>
<p>Consider 10 bins of size 1: [0,1], (1,2] …( 9,10).</p>
<p>Answer the following questions:</p>
<ul>
<li><p>Calculate the relative frequencies of each result and draw the histogram</p></li>
<li><p>Calculate the cumulative frequencies of each result and draw the cumulative graph.</p></li>
<li><p>Draw a box plot .</p></li>
</ul>
</div>
</div>
<div id="practice" class="section level2 hasAnchor" number="2.26">
<h2><span class="header-section-number">2.26</span> Practice<a href="data-description.html#practice" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Load misophonia data from <code><a href="https://alejandro-isglobal.github.io/SDA/data/data_0.txt" class="uri">https://alejandro-isglobal.github.io/SDA/data/data_0.txt</a></code></p>
<ol style="list-style-type: decimal">
<li>Extract misophonia variable (Misofonia.dic)</li>
</ol>
<ul>
<li>Do a bar plot and a pie chart</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Extract convexity angle variable (Angulo<span class="math inline">\(\_\)</span>convexidad)</li>
</ol>
<ul>
<li>Calculate its sample mean (average), standard deviation and make a histogram</li>
<li>Calculate its median and inter-quartile range</li>
<li>Draw a boxplot</li>
</ul>
<p><a href="https://colab.research.google.com/drive/1ncTaoBgskCJcBIb0-PdnbUFr_AKU0XRF?usp=sharing">Solutions</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-DataDescription.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
