<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Interval estimation | Statistical Data Analysis</title>
  <meta name="description" content="This is the book for the statistics theory of the BIST master" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Interval estimation | Statistical Data Analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the book for the statistics theory of the BIST master" />
  <meta name="github-repo" content="alejandro-isglobal/master" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Interval estimation | Statistical Data Analysis" />
  
  <meta name="twitter:description" content="This is the book for the statistics theory of the BIST master" />
  

<meta name="author" content="Alejandro Caceres" />


<meta name="date" content="2023-08-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="maximum-likelihood.html"/>
<link rel="next" href="hypothesis-testing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SDA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#how"><i class="fa fa-check"></i><b>1.1</b> How</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i><b>1.2</b> Schedule</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#recommended-reading-list"><i class="fa fa-check"></i><b>1.3</b> Recommended reading list</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-description.html"><a href="data-description.html"><i class="fa fa-check"></i><b>2</b> Data description</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-description.html"><a href="data-description.html#scientific-method"><i class="fa fa-check"></i><b>2.1</b> Scientific method</a></li>
<li class="chapter" data-level="2.2" data-path="data-description.html"><a href="data-description.html#data"><i class="fa fa-check"></i><b>2.2</b> Data</a></li>
<li class="chapter" data-level="2.3" data-path="data-description.html"><a href="data-description.html#result-types"><i class="fa fa-check"></i><b>2.3</b> Result types</a></li>
<li class="chapter" data-level="2.4" data-path="data-description.html"><a href="data-description.html#random-experiments"><i class="fa fa-check"></i><b>2.4</b> Random experiments</a></li>
<li class="chapter" data-level="2.5" data-path="data-description.html"><a href="data-description.html#absolute-frequencies"><i class="fa fa-check"></i><b>2.5</b> Absolute frequencies</a></li>
<li class="chapter" data-level="2.6" data-path="data-description.html"><a href="data-description.html#relative-frequencies"><i class="fa fa-check"></i><b>2.6</b> Relative frequencies</a></li>
<li class="chapter" data-level="2.7" data-path="data-description.html"><a href="data-description.html#bar-chart"><i class="fa fa-check"></i><b>2.7</b> Bar chart</a></li>
<li class="chapter" data-level="2.8" data-path="data-description.html"><a href="data-description.html#pie-chart-pie"><i class="fa fa-check"></i><b>2.8</b> Pie chart (pie)</a></li>
<li class="chapter" data-level="2.9" data-path="data-description.html"><a href="data-description.html#ordinal-categorical-variables"><i class="fa fa-check"></i><b>2.9</b> Ordinal categorical variables</a></li>
<li class="chapter" data-level="2.10" data-path="data-description.html"><a href="data-description.html#absolute-and-relative-cumulative-frequencies"><i class="fa fa-check"></i><b>2.10</b> Absolute and relative cumulative frequencies</a></li>
<li class="chapter" data-level="2.11" data-path="data-description.html"><a href="data-description.html#cumulative-frequency-graph"><i class="fa fa-check"></i><b>2.11</b> Cumulative frequency graph</a></li>
<li class="chapter" data-level="2.12" data-path="data-description.html"><a href="data-description.html#numeric-variables"><i class="fa fa-check"></i><b>2.12</b> Numeric variables</a></li>
<li class="chapter" data-level="2.13" data-path="data-description.html"><a href="data-description.html#transforming-continuous-data"><i class="fa fa-check"></i><b>2.13</b> Transforming continuous data</a></li>
<li class="chapter" data-level="2.14" data-path="data-description.html"><a href="data-description.html#frequency-table-for-a-continuous-variable"><i class="fa fa-check"></i><b>2.14</b> Frequency table for a continuous variable</a></li>
<li class="chapter" data-level="2.15" data-path="data-description.html"><a href="data-description.html#histogram"><i class="fa fa-check"></i><b>2.15</b> Histogram</a></li>
<li class="chapter" data-level="2.16" data-path="data-description.html"><a href="data-description.html#cumulative-frequency-graph-1"><i class="fa fa-check"></i><b>2.16</b> Cumulative frequency graph</a></li>
<li class="chapter" data-level="2.17" data-path="data-description.html"><a href="data-description.html#summary-statistics"><i class="fa fa-check"></i><b>2.17</b> Summary Statistics</a></li>
<li class="chapter" data-level="2.18" data-path="data-description.html"><a href="data-description.html#average-sample-mean"><i class="fa fa-check"></i><b>2.18</b> Average (sample mean)</a></li>
<li class="chapter" data-level="2.19" data-path="data-description.html"><a href="data-description.html#median"><i class="fa fa-check"></i><b>2.19</b> Median</a></li>
<li class="chapter" data-level="2.20" data-path="data-description.html"><a href="data-description.html#dispersion"><i class="fa fa-check"></i><b>2.20</b> Dispersion</a></li>
<li class="chapter" data-level="2.21" data-path="data-description.html"><a href="data-description.html#sample-variance"><i class="fa fa-check"></i><b>2.21</b> Sample variance</a></li>
<li class="chapter" data-level="2.22" data-path="data-description.html"><a href="data-description.html#interquartile-range-iqr"><i class="fa fa-check"></i><b>2.22</b> Interquartile range (IQR)</a></li>
<li class="chapter" data-level="2.23" data-path="data-description.html"><a href="data-description.html#boxplot"><i class="fa fa-check"></i><b>2.23</b> Boxplot</a></li>
<li class="chapter" data-level="2.24" data-path="data-description.html"><a href="data-description.html#questions"><i class="fa fa-check"></i><b>2.24</b> Questions</a></li>
<li class="chapter" data-level="2.25" data-path="data-description.html"><a href="data-description.html#exercises"><i class="fa fa-check"></i><b>2.25</b> Exercises</a></li>
<li class="chapter" data-level="2.26" data-path="data-description.html"><a href="data-description.html#practice"><i class="fa fa-check"></i><b>2.26</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>3</b> Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probability.html"><a href="probability.html#random-experiments-1"><i class="fa fa-check"></i><b>3.1</b> Random experiments</a></li>
<li class="chapter" data-level="3.2" data-path="probability.html"><a href="probability.html#measurement-probability"><i class="fa fa-check"></i><b>3.2</b> Measurement probability</a></li>
<li class="chapter" data-level="3.3" data-path="probability.html"><a href="probability.html#classical-probability"><i class="fa fa-check"></i><b>3.3</b> Classical probability</a></li>
<li class="chapter" data-level="3.4" data-path="probability.html"><a href="probability.html#relative-frequencies-1"><i class="fa fa-check"></i><b>3.4</b> Relative frequencies</a></li>
<li class="chapter" data-level="3.5" data-path="probability.html"><a href="probability.html#relative-frequencies-at-infinity"><i class="fa fa-check"></i><b>3.5</b> Relative frequencies at infinity</a></li>
<li class="chapter" data-level="3.6" data-path="probability.html"><a href="probability.html#frequentist-probability"><i class="fa fa-check"></i><b>3.6</b> Frequentist probability</a></li>
<li class="chapter" data-level="3.7" data-path="probability.html"><a href="probability.html#classical-and-frequentist-probabilities"><i class="fa fa-check"></i><b>3.7</b> Classical and frequentist probabilities</a></li>
<li class="chapter" data-level="3.8" data-path="probability.html"><a href="probability.html#definition-of-probability"><i class="fa fa-check"></i><b>3.8</b> Definition of probability</a></li>
<li class="chapter" data-level="3.9" data-path="probability.html"><a href="probability.html#probabilities-table"><i class="fa fa-check"></i><b>3.9</b> Probabilities Table</a></li>
<li class="chapter" data-level="3.10" data-path="probability.html"><a href="probability.html#sample-space"><i class="fa fa-check"></i><b>3.10</b> Sample space</a></li>
<li class="chapter" data-level="3.11" data-path="probability.html"><a href="probability.html#events"><i class="fa fa-check"></i><b>3.11</b> Events</a></li>
<li class="chapter" data-level="3.12" data-path="probability.html"><a href="probability.html#algebra-of-events"><i class="fa fa-check"></i><b>3.12</b> Algebra of events</a></li>
<li class="chapter" data-level="3.13" data-path="probability.html"><a href="probability.html#mutually-exclusive-results"><i class="fa fa-check"></i><b>3.13</b> Mutually exclusive results</a></li>
<li class="chapter" data-level="3.14" data-path="probability.html"><a href="probability.html#joint-probabilities"><i class="fa fa-check"></i><b>3.14</b> Joint probabilities</a></li>
<li class="chapter" data-level="3.15" data-path="probability.html"><a href="probability.html#contingency-table"><i class="fa fa-check"></i><b>3.15</b> Contingency table</a></li>
<li class="chapter" data-level="3.16" data-path="probability.html"><a href="probability.html#the-addition-rule"><i class="fa fa-check"></i><b>3.16</b> The addition rule:</a></li>
<li class="chapter" data-level="3.17" data-path="probability.html"><a href="probability.html#questions-1"><i class="fa fa-check"></i><b>3.17</b> Questions</a></li>
<li class="chapter" data-level="3.18" data-path="probability.html"><a href="probability.html#exercises-1"><i class="fa fa-check"></i><b>3.18</b> Exercises</a></li>
<li class="chapter" data-level="3.19" data-path="probability.html"><a href="probability.html#practice-1"><i class="fa fa-check"></i><b>3.19</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>4</b> Conditional probability</a>
<ul>
<li class="chapter" data-level="4.1" data-path="conditional-probability.html"><a href="conditional-probability.html#joint-probability"><i class="fa fa-check"></i><b>4.1</b> Joint probability</a></li>
<li class="chapter" data-level="4.2" data-path="conditional-probability.html"><a href="conditional-probability.html#statistical-independence"><i class="fa fa-check"></i><b>4.2</b> Statistical independence</a></li>
<li class="chapter" data-level="4.3" data-path="conditional-probability.html"><a href="conditional-probability.html#the-conditional-probability"><i class="fa fa-check"></i><b>4.3</b> The conditional probability</a></li>
<li class="chapter" data-level="4.4" data-path="conditional-probability.html"><a href="conditional-probability.html#conditional-contingency-table"><i class="fa fa-check"></i><b>4.4</b> Conditional contingency table</a></li>
<li class="chapter" data-level="4.5" data-path="conditional-probability.html"><a href="conditional-probability.html#statistical-independence-1"><i class="fa fa-check"></i><b>4.5</b> Statistical independence</a></li>
<li class="chapter" data-level="4.6" data-path="conditional-probability.html"><a href="conditional-probability.html#statistical-dependency"><i class="fa fa-check"></i><b>4.6</b> Statistical dependency</a></li>
<li class="chapter" data-level="4.7" data-path="conditional-probability.html"><a href="conditional-probability.html#diagnostic-test"><i class="fa fa-check"></i><b>4.7</b> Diagnostic test</a></li>
<li class="chapter" data-level="4.8" data-path="conditional-probability.html"><a href="conditional-probability.html#inverse-probabilities"><i class="fa fa-check"></i><b>4.8</b> Inverse probabilities</a></li>
<li class="chapter" data-level="4.9" data-path="conditional-probability.html"><a href="conditional-probability.html#bayes-theorem"><i class="fa fa-check"></i><b>4.9</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="4.10" data-path="conditional-probability.html"><a href="conditional-probability.html#exercises-2"><i class="fa fa-check"></i><b>4.10</b> Exercises</a></li>
<li class="chapter" data-level="4.11" data-path="conditional-probability.html"><a href="conditional-probability.html#questions-2"><i class="fa fa-check"></i><b>4.11</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html"><i class="fa fa-check"></i><b>5</b> Discrete Random Variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#objective"><i class="fa fa-check"></i><b>5.1</b> Objective</a></li>
<li class="chapter" data-level="5.2" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#relative-frequencies-2"><i class="fa fa-check"></i><b>5.2</b> Relative frequencies</a></li>
<li class="chapter" data-level="5.3" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#random-variable"><i class="fa fa-check"></i><b>5.3</b> Random variable</a></li>
<li class="chapter" data-level="5.4" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#events-of-observing-a-random-variable"><i class="fa fa-check"></i><b>5.4</b> Events of observing a random variable</a></li>
<li class="chapter" data-level="5.5" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-of-random-variables"><i class="fa fa-check"></i><b>5.5</b> Probability of random variables</a></li>
<li class="chapter" data-level="5.6" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-functions"><i class="fa fa-check"></i><b>5.6</b> Probability functions</a></li>
<li class="chapter" data-level="5.7" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-functions-1"><i class="fa fa-check"></i><b>5.7</b> Probability functions</a></li>
<li class="chapter" data-level="5.8" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probabilities-and-relative-frequencies"><i class="fa fa-check"></i><b>5.8</b> Probabilities and relative frequencies</a></li>
<li class="chapter" data-level="5.9" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#mean-or-expected-value"><i class="fa fa-check"></i><b>5.9</b> Mean or expected value</a></li>
<li class="chapter" data-level="5.10" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#variance"><i class="fa fa-check"></i><b>5.10</b> Variance</a></li>
<li class="chapter" data-level="5.11" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-functions-for-functions-of-x"><i class="fa fa-check"></i><b>5.11</b> Probability functions for functions of <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="5.12" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-distribution"><i class="fa fa-check"></i><b>5.12</b> Probability distribution</a></li>
<li class="chapter" data-level="5.13" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#probability-function-and-probability-distribution"><i class="fa fa-check"></i><b>5.13</b> Probability function and probability distribution</a></li>
<li class="chapter" data-level="5.14" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#quantiles"><i class="fa fa-check"></i><b>5.14</b> Quantiles</a></li>
<li class="chapter" data-level="5.15" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#summary"><i class="fa fa-check"></i><b>5.15</b> Summary</a></li>
<li class="chapter" data-level="5.16" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#questions-3"><i class="fa fa-check"></i><b>5.16</b> Questions</a></li>
<li class="chapter" data-level="5.17" data-path="discrete-random-variables.html"><a href="discrete-random-variables.html#exercises-3"><i class="fa fa-check"></i><b>5.17</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="continous-random-variables.html"><a href="continous-random-variables.html"><i class="fa fa-check"></i><b>6</b> Continous Random Variables</a>
<ul>
<li class="chapter" data-level="6.1" data-path="continous-random-variables.html"><a href="continous-random-variables.html#objective-1"><i class="fa fa-check"></i><b>6.1</b> Objective</a></li>
<li class="chapter" data-level="6.2" data-path="continous-random-variables.html"><a href="continous-random-variables.html#continuous-random-variables"><i class="fa fa-check"></i><b>6.2</b> Continuous random variables</a></li>
<li class="chapter" data-level="6.3" data-path="continous-random-variables.html"><a href="continous-random-variables.html#relative-frequencies-3"><i class="fa fa-check"></i><b>6.3</b> relative frequencies</a></li>
<li class="chapter" data-level="6.4" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probability-density-function"><i class="fa fa-check"></i><b>6.4</b> probability density function</a></li>
<li class="chapter" data-level="6.5" data-path="continous-random-variables.html"><a href="continous-random-variables.html#total-area-under-the-curve"><i class="fa fa-check"></i><b>6.5</b> Total area under the curve</a></li>
<li class="chapter" data-level="6.6" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probabilities-of-continous-variables"><i class="fa fa-check"></i><b>6.6</b> Probabilities of continous variables</a></li>
<li class="chapter" data-level="6.7" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probability-distribution-1"><i class="fa fa-check"></i><b>6.7</b> Probability distribution</a></li>
<li class="chapter" data-level="6.8" data-path="continous-random-variables.html"><a href="continous-random-variables.html#probability-plots"><i class="fa fa-check"></i><b>6.8</b> Probability plots</a></li>
<li class="chapter" data-level="6.9" data-path="continous-random-variables.html"><a href="continous-random-variables.html#mean"><i class="fa fa-check"></i><b>6.9</b> Mean</a></li>
<li class="chapter" data-level="6.10" data-path="continous-random-variables.html"><a href="continous-random-variables.html#variance-1"><i class="fa fa-check"></i><b>6.10</b> Variance</a></li>
<li class="chapter" data-level="6.11" data-path="continous-random-variables.html"><a href="continous-random-variables.html#functions-of-x"><i class="fa fa-check"></i><b>6.11</b> Functions of <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="6.12" data-path="continous-random-variables.html"><a href="continous-random-variables.html#exercises-4"><i class="fa fa-check"></i><b>6.12</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html"><i class="fa fa-check"></i><b>7</b> Discrete Probability Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#objective-2"><i class="fa fa-check"></i><b>7.1</b> Objective</a></li>
<li class="chapter" data-level="7.2" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#probability-mass-function"><i class="fa fa-check"></i><b>7.2</b> Probability mass function</a></li>
<li class="chapter" data-level="7.3" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#probability-model"><i class="fa fa-check"></i><b>7.3</b> Probability model</a></li>
<li class="chapter" data-level="7.4" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#parametric-models"><i class="fa fa-check"></i><b>7.4</b> Parametric models</a></li>
<li class="chapter" data-level="7.5" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#uniform-distribution-one-parameter"><i class="fa fa-check"></i><b>7.5</b> Uniform distribution (one parameter)</a></li>
<li class="chapter" data-level="7.6" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#uniform-distribution-two-parameters"><i class="fa fa-check"></i><b>7.6</b> Uniform distribution (two parameters)</a></li>
<li class="chapter" data-level="7.7" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#bernoulli-trial"><i class="fa fa-check"></i><b>7.7</b> Bernoulli trial</a></li>
<li class="chapter" data-level="7.8" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#binomial-experiment"><i class="fa fa-check"></i><b>7.8</b> Binomial experiment</a></li>
<li class="chapter" data-level="7.9" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#binomial-probability-function"><i class="fa fa-check"></i><b>7.9</b> Binomial probability function</a></li>
<li class="chapter" data-level="7.10" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#negative-binomial-probability-function"><i class="fa fa-check"></i><b>7.10</b> Negative binomial probability function</a></li>
<li class="chapter" data-level="7.11" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#geometric-distribution"><i class="fa fa-check"></i><b>7.11</b> Geometric distribution</a></li>
<li class="chapter" data-level="7.12" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#hypergeometric-model"><i class="fa fa-check"></i><b>7.12</b> Hypergeometric model</a></li>
<li class="chapter" data-level="7.13" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#questions-4"><i class="fa fa-check"></i><b>7.13</b> Questions</a></li>
<li class="chapter" data-level="7.14" data-path="discrete-probability-models.html"><a href="discrete-probability-models.html#exercises-5"><i class="fa fa-check"></i><b>7.14</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html"><i class="fa fa-check"></i><b>8</b> Poisson and Exponential Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#objective-3"><i class="fa fa-check"></i><b>8.1</b> Objective</a></li>
<li class="chapter" data-level="8.2" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#discrete-probability-models-1"><i class="fa fa-check"></i><b>8.2</b> Discrete probability models</a></li>
<li class="chapter" data-level="8.3" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#poissson-experiment"><i class="fa fa-check"></i><b>8.3</b> Poissson experiment</a></li>
<li class="chapter" data-level="8.4" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#poisson-probability-mass-function"><i class="fa fa-check"></i><b>8.4</b> Poisson probability mass function</a></li>
<li class="chapter" data-level="8.5" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#continuous-probability-models"><i class="fa fa-check"></i><b>8.5</b> Continuous probability models</a></li>
<li class="chapter" data-level="8.6" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exponential-process"><i class="fa fa-check"></i><b>8.6</b> Exponential process</a></li>
<li class="chapter" data-level="8.7" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exponential-probability-density"><i class="fa fa-check"></i><b>8.7</b> Exponential probability density</a></li>
<li class="chapter" data-level="8.8" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exponential-distribution"><i class="fa fa-check"></i><b>8.8</b> Exponential Distribution</a></li>
<li class="chapter" data-level="8.9" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#questions-5"><i class="fa fa-check"></i><b>8.9</b> Questions</a></li>
<li class="chapter" data-level="8.10" data-path="poisson-and-exponential-models.html"><a href="poisson-and-exponential-models.html#exercises-6"><i class="fa fa-check"></i><b>8.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="normal-distribution.html"><a href="normal-distribution.html"><i class="fa fa-check"></i><b>9</b> Normal Distribution</a>
<ul>
<li class="chapter" data-level="9.1" data-path="normal-distribution.html"><a href="normal-distribution.html#objective-4"><i class="fa fa-check"></i><b>9.1</b> Objective</a></li>
<li class="chapter" data-level="9.2" data-path="normal-distribution.html"><a href="normal-distribution.html#history"><i class="fa fa-check"></i><b>9.2</b> History</a></li>
<li class="chapter" data-level="9.3" data-path="normal-distribution.html"><a href="normal-distribution.html#normal-density"><i class="fa fa-check"></i><b>9.3</b> normal density</a></li>
<li class="chapter" data-level="9.4" data-path="normal-distribution.html"><a href="normal-distribution.html#definition"><i class="fa fa-check"></i><b>9.4</b> Definition</a></li>
<li class="chapter" data-level="9.5" data-path="normal-distribution.html"><a href="normal-distribution.html#probability-distribution-2"><i class="fa fa-check"></i><b>9.5</b> Probability distribution</a></li>
<li class="chapter" data-level="9.6" data-path="normal-distribution.html"><a href="normal-distribution.html#standard-normal-density"><i class="fa fa-check"></i><b>9.6</b> Standard normal density</a></li>
<li class="chapter" data-level="9.7" data-path="normal-distribution.html"><a href="normal-distribution.html#standard-distribution"><i class="fa fa-check"></i><b>9.7</b> Standard distribution</a></li>
<li class="chapter" data-level="9.8" data-path="normal-distribution.html"><a href="normal-distribution.html#summary-of-probability-models"><i class="fa fa-check"></i><b>9.8</b> Summary of probability models</a></li>
<li class="chapter" data-level="9.9" data-path="normal-distribution.html"><a href="normal-distribution.html#r-functions-of-probability-models"><i class="fa fa-check"></i><b>9.9</b> R functions of probability models</a></li>
<li class="chapter" data-level="9.10" data-path="normal-distribution.html"><a href="normal-distribution.html#questions-6"><i class="fa fa-check"></i><b>9.10</b> Questions</a></li>
<li class="chapter" data-level="9.11" data-path="normal-distribution.html"><a href="normal-distribution.html#exercises-7"><i class="fa fa-check"></i><b>9.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sampling-distributions.html"><a href="sampling-distributions.html"><i class="fa fa-check"></i><b>10</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sampling-distributions.html"><a href="sampling-distributions.html#objective-5"><i class="fa fa-check"></i><b>10.1</b> Objective</a></li>
<li class="chapter" data-level="10.2" data-path="sampling-distributions.html"><a href="sampling-distributions.html#aleatory-sample"><i class="fa fa-check"></i><b>10.2</b> Aleatory sample</a></li>
<li class="chapter" data-level="10.3" data-path="sampling-distributions.html"><a href="sampling-distributions.html#calculation-of-probabilities"><i class="fa fa-check"></i><b>10.3</b> Calculation of probabilities</a></li>
<li class="chapter" data-level="10.4" data-path="sampling-distributions.html"><a href="sampling-distributions.html#parameter-estimation"><i class="fa fa-check"></i><b>10.4</b> Parameter estimation</a></li>
<li class="chapter" data-level="10.5" data-path="sampling-distributions.html"><a href="sampling-distributions.html#margin-of-error-of-estimates"><i class="fa fa-check"></i><b>10.5</b> Margin of error of estimates</a></li>
<li class="chapter" data-level="10.6" data-path="sampling-distributions.html"><a href="sampling-distributions.html#inference"><i class="fa fa-check"></i><b>10.6</b> Inference</a></li>
<li class="chapter" data-level="10.7" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sample-mean-distribution"><i class="fa fa-check"></i><b>10.7</b> Sample mean distribution</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sample-sum"><i class="fa fa-check"></i><b>10.7.1</b> Sample sum</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sample-variance-1"><i class="fa fa-check"></i><b>10.8</b> Sample variance</a></li>
<li class="chapter" data-level="10.9" data-path="sampling-distributions.html"><a href="sampling-distributions.html#probabilities-of-the-sample-variance"><i class="fa fa-check"></i><b>10.9</b> Probabilities of the sample variance</a></li>
<li class="chapter" data-level="10.10" data-path="sampling-distributions.html"><a href="sampling-distributions.html#chi2-statistic"><i class="fa fa-check"></i><b>10.10</b> <span class="math inline">\(\chi^2\)</span>-statistic</a></li>
<li class="chapter" data-level="10.11" data-path="sampling-distributions.html"><a href="sampling-distributions.html#questions-7"><i class="fa fa-check"></i><b>10.11</b> Questions</a></li>
<li class="chapter" data-level="10.12" data-path="sampling-distributions.html"><a href="sampling-distributions.html#exercises-8"><i class="fa fa-check"></i><b>10.12</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html"><i class="fa fa-check"></i><b>11</b> Central limit theorem</a>
<ul>
<li class="chapter" data-level="11.1" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#objective-6"><i class="fa fa-check"></i><b>11.1</b> Objective</a></li>
<li class="chapter" data-level="11.2" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#margin-of-error"><i class="fa fa-check"></i><b>11.2</b> Margin of error</a></li>
<li class="chapter" data-level="11.3" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#example-cables"><i class="fa fa-check"></i><b>11.3</b> Example (Cables)</a></li>
<li class="chapter" data-level="11.4" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#central-limit-theorem-1"><i class="fa fa-check"></i><b>11.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="11.5" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#sample-sum-and-clt"><i class="fa fa-check"></i><b>11.5</b> Sample sum and CLT</a></li>
<li class="chapter" data-level="11.6" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#questions-8"><i class="fa fa-check"></i><b>11.6</b> Questions</a></li>
<li class="chapter" data-level="11.7" data-path="central-limit-theorem.html"><a href="central-limit-theorem.html#exercises-9"><i class="fa fa-check"></i><b>11.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html"><i class="fa fa-check"></i><b>12</b> Maximum likelihood</a>
<ul>
<li class="chapter" data-level="12.1" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#objective-7"><i class="fa fa-check"></i><b>12.1</b> Objective</a></li>
<li class="chapter" data-level="12.2" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#statistic"><i class="fa fa-check"></i><b>12.2</b> Statistic</a></li>
<li class="chapter" data-level="12.3" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#properties"><i class="fa fa-check"></i><b>12.3</b> Properties</a></li>
<li class="chapter" data-level="12.4" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#maximum-likelihood-1"><i class="fa fa-check"></i><b>12.4</b> Maximum likelihood</a></li>
<li class="chapter" data-level="12.5" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#maximum-likelihood-2"><i class="fa fa-check"></i><b>12.5</b> Maximum likelihood</a></li>
<li class="chapter" data-level="12.6" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#questions-9"><i class="fa fa-check"></i><b>12.6</b> Questions</a></li>
<li class="chapter" data-level="12.7" data-path="maximum-likelihood.html"><a href="maximum-likelihood.html#exercises-10"><i class="fa fa-check"></i><b>12.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="interval-estimation.html"><a href="interval-estimation.html"><i class="fa fa-check"></i><b>13</b> Interval estimation</a>
<ul>
<li class="chapter" data-level="13.1" data-path="interval-estimation.html"><a href="interval-estimation.html#objective-8"><i class="fa fa-check"></i><b>13.1</b> Objective</a></li>
<li class="chapter" data-level="13.2" data-path="interval-estimation.html"><a href="interval-estimation.html#estimation-of-the-mean"><i class="fa fa-check"></i><b>13.2</b> Estimation of the mean</a></li>
<li class="chapter" data-level="13.3" data-path="interval-estimation.html"><a href="interval-estimation.html#margin-of-error-1"><i class="fa fa-check"></i><b>13.3</b> Margin of error</a></li>
<li class="chapter" data-level="13.4" data-path="interval-estimation.html"><a href="interval-estimation.html#interval-estimation-for-the-mean"><i class="fa fa-check"></i><b>13.4</b> Interval estimation for the mean</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="interval-estimation.html"><a href="interval-estimation.html#case-1-known-variance"><i class="fa fa-check"></i><b>13.4.1</b> Case 1 (known variance)</a></li>
<li class="chapter" data-level="13.4.2" data-path="interval-estimation.html"><a href="interval-estimation.html#confidence-level"><i class="fa fa-check"></i><b>13.4.2</b> Confidence level</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="interval-estimation.html"><a href="interval-estimation.html#marging-of-error-for-unkown-variance"><i class="fa fa-check"></i><b>13.5</b> Marging of error for unkown variance</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="interval-estimation.html"><a href="interval-estimation.html#theorem-t-statistic"><i class="fa fa-check"></i><b>13.5.1</b> Theorem (T-statistic)</a></li>
<li class="chapter" data-level="13.5.2" data-path="interval-estimation.html"><a href="interval-estimation.html#case-2-unknown-variance"><i class="fa fa-check"></i><b>13.5.2</b> Case 2 (unknown variance)</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="interval-estimation.html"><a href="interval-estimation.html#estimation-of-proportions"><i class="fa fa-check"></i><b>13.6</b> Estimation of proportions</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="interval-estimation.html"><a href="interval-estimation.html#case-3-proportions"><i class="fa fa-check"></i><b>13.6.1</b> Case 3 (proportions)</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="interval-estimation.html"><a href="interval-estimation.html#estimation-of-the-variance"><i class="fa fa-check"></i><b>13.7</b> Estimation of the variance</a></li>
<li class="chapter" data-level="13.8" data-path="interval-estimation.html"><a href="interval-estimation.html#confidence-interval-for-the-variance"><i class="fa fa-check"></i><b>13.8</b> Confidence interval for the variance</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="interval-estimation.html"><a href="interval-estimation.html#theorem-chi2"><i class="fa fa-check"></i><b>13.8.1</b> Theorem (<span class="math inline">\(\chi^2\)</span>):</a></li>
<li class="chapter" data-level="13.8.2" data-path="interval-estimation.html"><a href="interval-estimation.html#confidence-interval-for-the-variance-1"><i class="fa fa-check"></i><b>13.8.2</b> Confidence interval for the variance</a></li>
<li class="chapter" data-level="13.8.3" data-path="interval-estimation.html"><a href="interval-estimation.html#case-4-variance"><i class="fa fa-check"></i><b>13.8.3</b> Case 4 (variance)</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="interval-estimation.html"><a href="interval-estimation.html#questions-10"><i class="fa fa-check"></i><b>13.9</b> Questions</a></li>
<li class="chapter" data-level="13.10" data-path="interval-estimation.html"><a href="interval-estimation.html#exercises-11"><i class="fa fa-check"></i><b>13.10</b> Exercises</a></li>
<li class="chapter" data-level="13.11" data-path="interval-estimation.html"><a href="interval-estimation.html#practice-3"><i class="fa fa-check"></i><b>13.11</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>14</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="14.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#objective-9"><i class="fa fa-check"></i><b>14.1</b> Objective</a></li>
<li class="chapter" data-level="14.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis"><i class="fa fa-check"></i><b>14.2</b> Hypothesis</a></li>
<li class="chapter" data-level="14.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-1"><i class="fa fa-check"></i><b>14.3</b> Hypothesis testing</a></li>
<li class="chapter" data-level="14.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-1-known-variance-1"><i class="fa fa-check"></i><b>14.4</b> Case 1 (known variance)</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-test-with-a-confidence-interval"><i class="fa fa-check"></i><b>14.4.1</b> Hypothesis test with a confidence interval</a></li>
<li class="chapter" data-level="14.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-test-with-acceptancerejection-zones"><i class="fa fa-check"></i><b>14.4.2</b> Hypothesis test with acceptance/rejection zones</a></li>
<li class="chapter" data-level="14.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-test-with-a-p-value"><i class="fa fa-check"></i><b>14.4.3</b> Hypothesis test with a P-value</a></li>
<li class="chapter" data-level="14.4.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#upper-tail-hypothesis"><i class="fa fa-check"></i><b>14.4.4</b> Upper tail hypothesis</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-2-unknown-variance-1"><i class="fa fa-check"></i><b>14.5</b> Case 2 (unknown variance)</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#lower-tail-hypothesis"><i class="fa fa-check"></i><b>14.5.1</b> Lower tail hypothesis</a></li>
<li class="chapter" data-level="14.5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-with-large-n-and-any-distribution"><i class="fa fa-check"></i><b>14.5.2</b> Hypothesis testing with large n and any distribution</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-3-proportions-1"><i class="fa fa-check"></i><b>14.6</b> Case 3 (proportions)</a></li>
<li class="chapter" data-level="14.7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#case-4-variances"><i class="fa fa-check"></i><b>14.7</b> Case 4 (variances)</a></li>
<li class="chapter" data-level="14.8" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#errors-in-hypothesis-testing"><i class="fa fa-check"></i><b>14.8</b> Errors in hypothesis testing</a></li>
<li class="chapter" data-level="14.9" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercises-12"><i class="fa fa-check"></i><b>14.9</b> Exercises</a></li>
<li class="chapter" data-level="14.10" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#practice-4"><i class="fa fa-check"></i><b>14.10</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="contingency-tables.html"><a href="contingency-tables.html"><i class="fa fa-check"></i><b>15</b> Contingency tables</a>
<ul>
<li class="chapter" data-level="15.1" data-path="contingency-tables.html"><a href="contingency-tables.html#objective-10"><i class="fa fa-check"></i><b>15.1</b> Objective</a></li>
<li class="chapter" data-level="15.2" data-path="contingency-tables.html"><a href="contingency-tables.html#difference-between-proportions"><i class="fa fa-check"></i><b>15.2</b> Difference between proportions</a></li>
<li class="chapter" data-level="15.3" data-path="contingency-tables.html"><a href="contingency-tables.html#difference-between-proportions-1"><i class="fa fa-check"></i><b>15.3</b> Difference between proportions</a></li>
<li class="chapter" data-level="15.4" data-path="contingency-tables.html"><a href="contingency-tables.html#contingency-table-of-conditional-probabilities"><i class="fa fa-check"></i><b>15.4</b> Contingency table of conditional probabilities</a></li>
<li class="chapter" data-level="15.5" data-path="contingency-tables.html"><a href="contingency-tables.html#test-for-the-difference-between-proportions"><i class="fa fa-check"></i><b>15.5</b> Test for the difference between proportions</a></li>
<li class="chapter" data-level="15.6" data-path="contingency-tables.html"><a href="contingency-tables.html#chi2-test"><i class="fa fa-check"></i><b>15.6</b> <span class="math inline">\(\chi^2\)</span> test</a></li>
<li class="chapter" data-level="15.7" data-path="contingency-tables.html"><a href="contingency-tables.html#fishers-exact-test"><i class="fa fa-check"></i><b>15.7</b> Fisher’s exact test</a></li>
<li class="chapter" data-level="15.8" data-path="contingency-tables.html"><a href="contingency-tables.html#hypergeometric-distribution"><i class="fa fa-check"></i><b>15.8</b> Hypergeometric distribution</a></li>
<li class="chapter" data-level="15.9" data-path="contingency-tables.html"><a href="contingency-tables.html#difference-between-several-proportions"><i class="fa fa-check"></i><b>15.9</b> Difference between several proportions</a></li>
<li class="chapter" data-level="15.10" data-path="contingency-tables.html"><a href="contingency-tables.html#questions-11"><i class="fa fa-check"></i><b>15.10</b> Questions</a></li>
<li class="chapter" data-level="15.11" data-path="contingency-tables.html"><a href="contingency-tables.html#practice-5"><i class="fa fa-check"></i><b>15.11</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html"><i class="fa fa-check"></i><b>16</b> Mean differences between two samples</a>
<ul>
<li class="chapter" data-level="16.1" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#objective-11"><i class="fa fa-check"></i><b>16.1</b> Objective</a></li>
<li class="chapter" data-level="16.2" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#differet-means-between-two-groups"><i class="fa fa-check"></i><b>16.2</b> Differet means between two groups</a></li>
<li class="chapter" data-level="16.3" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#data-1"><i class="fa fa-check"></i><b>16.3</b> Data</a></li>
<li class="chapter" data-level="16.4" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#difference-between-means"><i class="fa fa-check"></i><b>16.4</b> Difference between means</a></li>
<li class="chapter" data-level="16.5" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#hypothesis-test"><i class="fa fa-check"></i><b>16.5</b> hypothesis test</a></li>
<li class="chapter" data-level="16.6" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#estiamtor-of-the-mean-difference"><i class="fa fa-check"></i><b>16.6</b> Estiamtor of the mean difference</a></li>
<li class="chapter" data-level="16.7" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#standardized-error"><i class="fa fa-check"></i><b>16.7</b> Standardized error</a></li>
<li class="chapter" data-level="16.8" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#standardized-error-for-the-null"><i class="fa fa-check"></i><b>16.8</b> Standardized error for the null</a></li>
<li class="chapter" data-level="16.9" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#mean-differences-when-n-is-small"><i class="fa fa-check"></i><b>16.9</b> Mean differences when <span class="math inline">\(n\)</span> is small</a></li>
<li class="chapter" data-level="16.10" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#data-2"><i class="fa fa-check"></i><b>16.10</b> Data</a></li>
<li class="chapter" data-level="16.11" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#difference-between-means-1"><i class="fa fa-check"></i><b>16.11</b> Difference between means</a></li>
<li class="chapter" data-level="16.12" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#hypothesis-test-1"><i class="fa fa-check"></i><b>16.12</b> hypothesis test</a></li>
<li class="chapter" data-level="16.13" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#estimator-of-the-mean-difference"><i class="fa fa-check"></i><b>16.13</b> Estimator of the mean difference</a></li>
<li class="chapter" data-level="16.14" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#standardized-error-for-the-null-1"><i class="fa fa-check"></i><b>16.14</b> Standardized error for the null</a></li>
<li class="chapter" data-level="16.15" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#unequal-variances"><i class="fa fa-check"></i><b>16.15</b> Unequal variances</a></li>
<li class="chapter" data-level="16.16" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#questions-12"><i class="fa fa-check"></i><b>16.16</b> Questions</a></li>
<li class="chapter" data-level="16.17" data-path="mean-differences-between-two-samples.html"><a href="mean-differences-between-two-samples.html#practice-6"><i class="fa fa-check"></i><b>16.17</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html"><i class="fa fa-check"></i><b>17</b> Mean differences across several groups</a>
<ul>
<li class="chapter" data-level="17.1" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#objective-12"><i class="fa fa-check"></i><b>17.1</b> Objective</a></li>
<li class="chapter" data-level="17.2" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#different-means-across-several-conditions"><i class="fa fa-check"></i><b>17.2</b> Different means across several conditions</a></li>
<li class="chapter" data-level="17.3" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#data-3"><i class="fa fa-check"></i><b>17.3</b> Data</a></li>
<li class="chapter" data-level="17.4" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#difference-between-means-2"><i class="fa fa-check"></i><b>17.4</b> Difference between means</a></li>
<li class="chapter" data-level="17.5" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#hypothesis-test-2"><i class="fa fa-check"></i><b>17.5</b> hypothesis test</a></li>
<li class="chapter" data-level="17.6" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>17.6</b> Analysis of variance (ANOVA)</a></li>
<li class="chapter" data-level="17.7" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#anova-for-two-groups"><i class="fa fa-check"></i><b>17.7</b> ANOVA for two groups</a></li>
<li class="chapter" data-level="17.8" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#linear-model"><i class="fa fa-check"></i><b>17.8</b> Linear model</a></li>
<li class="chapter" data-level="17.9" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#way-anova"><i class="fa fa-check"></i><b>17.9</b> 2-way ANOVA</a></li>
<li class="chapter" data-level="17.10" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#data-4"><i class="fa fa-check"></i><b>17.10</b> Data</a></li>
<li class="chapter" data-level="17.11" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#modeling-residuals"><i class="fa fa-check"></i><b>17.11</b> Modeling residuals</a></li>
<li class="chapter" data-level="17.12" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#difference-between-means-3"><i class="fa fa-check"></i><b>17.12</b> Difference between means</a></li>
<li class="chapter" data-level="17.13" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#linear-model-1"><i class="fa fa-check"></i><b>17.13</b> Linear model</a></li>
<li class="chapter" data-level="17.14" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#hypothesis-test-3"><i class="fa fa-check"></i><b>17.14</b> Hypothesis test</a></li>
<li class="chapter" data-level="17.15" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#variance-components"><i class="fa fa-check"></i><b>17.15</b> Variance components</a></li>
<li class="chapter" data-level="17.16" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#way-anova-with-interaction"><i class="fa fa-check"></i><b>17.16</b> 2-way ANOVA with interaction</a></li>
<li class="chapter" data-level="17.17" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#linear-model-2"><i class="fa fa-check"></i><b>17.17</b> Linear model</a></li>
<li class="chapter" data-level="17.18" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#hypothesis-test-4"><i class="fa fa-check"></i><b>17.18</b> Hypothesis test</a></li>
<li class="chapter" data-level="17.19" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#variance-components-1"><i class="fa fa-check"></i><b>17.19</b> Variance components</a></li>
<li class="chapter" data-level="17.20" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#questions-13"><i class="fa fa-check"></i><b>17.20</b> Questions</a></li>
<li class="chapter" data-level="17.21" data-path="mean-differences-across-several-groups.html"><a href="mean-differences-across-several-groups.html#practice-7"><i class="fa fa-check"></i><b>17.21</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html"><i class="fa fa-check"></i><b>18</b> Regression and correlation</a>
<ul>
<li class="chapter" data-level="18.1" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#objective-13"><i class="fa fa-check"></i><b>18.1</b> Objective</a></li>
<li class="chapter" data-level="18.2" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlations"><i class="fa fa-check"></i><b>18.2</b> Correlations</a></li>
<li class="chapter" data-level="18.3" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#data-5"><i class="fa fa-check"></i><b>18.3</b> Data</a></li>
<li class="chapter" data-level="18.4" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#normal-bivariate"><i class="fa fa-check"></i><b>18.4</b> Normal bivariate</a></li>
<li class="chapter" data-level="18.5" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#estimators"><i class="fa fa-check"></i><b>18.5</b> Estimators</a></li>
<li class="chapter" data-level="18.6" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#correlation-coefficient"><i class="fa fa-check"></i><b>18.6</b> Correlation coefficient</a></li>
<li class="chapter" data-level="18.7" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#hypothesis-contrast"><i class="fa fa-check"></i><b>18.7</b> Hypothesis contrast</a></li>
<li class="chapter" data-level="18.8" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#regression-analysis"><i class="fa fa-check"></i><b>18.8</b> Regression analysis</a></li>
<li class="chapter" data-level="18.9" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#linear-model-3"><i class="fa fa-check"></i><b>18.9</b> Linear model</a></li>
<li class="chapter" data-level="18.10" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#hypothesis-contrast-1"><i class="fa fa-check"></i><b>18.10</b> Hypothesis contrast</a></li>
<li class="chapter" data-level="18.11" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#estimators-1"><i class="fa fa-check"></i><b>18.11</b> Estimators</a></li>
<li class="chapter" data-level="18.12" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#hypothesis-testing-2"><i class="fa fa-check"></i><b>18.12</b> Hypothesis testing</a></li>
<li class="chapter" data-level="18.13" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#stratified-analysis"><i class="fa fa-check"></i><b>18.13</b> Stratified analysis</a></li>
<li class="chapter" data-level="18.14" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#multiple-regression"><i class="fa fa-check"></i><b>18.14</b> Multiple Regression</a></li>
<li class="chapter" data-level="18.15" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#multiple-regression-interaction"><i class="fa fa-check"></i><b>18.15</b> Multiple Regression interaction</a></li>
<li class="chapter" data-level="18.16" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#model-diagnostics"><i class="fa fa-check"></i><b>18.16</b> Model diagnostics</a></li>
<li class="chapter" data-level="18.17" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#questions-14"><i class="fa fa-check"></i><b>18.17</b> Questions</a></li>
<li class="chapter" data-level="18.18" data-path="regression-and-correlation.html"><a href="regression-and-correlation.html#practice-8"><i class="fa fa-check"></i><b>18.18</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="group-work-sessions.html"><a href="group-work-sessions.html"><i class="fa fa-check"></i><b>19</b> Group Work sessions</a>
<ul>
<li class="chapter" data-level="19.1" data-path="group-work-sessions.html"><a href="group-work-sessions.html#objectives"><i class="fa fa-check"></i><b>19.1</b> Objectives</a></li>
<li class="chapter" data-level="19.2" data-path="group-work-sessions.html"><a href="group-work-sessions.html#misophonia-dataset"><i class="fa fa-check"></i><b>19.2</b> Misophonia dataset</a></li>
<li class="chapter" data-level="19.3" data-path="group-work-sessions.html"><a href="group-work-sessions.html#group-work-session-1-data-description"><i class="fa fa-check"></i><b>19.3</b> Group Work session 1: Data description</a></li>
<li class="chapter" data-level="19.4" data-path="group-work-sessions.html"><a href="group-work-sessions.html#group-work-session-2-inference"><i class="fa fa-check"></i><b>19.4</b> Group Work session 2: Inference</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="interval-estimation" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Chapter 13</span> Interval estimation<a href="interval-estimation.html#interval-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="objective-8" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Objective<a href="interval-estimation.html#objective-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this chapter, we will introduce the concept of <strong>confidence intervals</strong> for means, proportions and variances.</p>
<p>We will derive the formulas for the confidence intervals under different conditions, like normality with known and unknown variance, and large <span class="math inline">\(n\)</span>.</p>
</div>
<div id="estimation-of-the-mean" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> Estimation of the mean<a href="interval-estimation.html#estimation-of-the-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have seen that whenever we take a random sample <span class="math inline">\((X_1, X_2, ... X_n)\)</span>, the sample mean
<span class="math display">\[\bar{X}=\frac{1}{n}\sum_{i=1}^n X_i\]</span></p>
<p>is an estimator of the mean <span class="math inline">\(\mu\)</span> of the random variable <span class="math inline">\(X\)</span>. The estimator is <strong>unbiased</strong></p>
<ul>
<li><span class="math inline">\(E(\bar{X})=\mu\)</span></li>
</ul>
<p>and <strong>consistent</strong></p>
<ul>
<li><span class="math inline">\(V(\bar{X})=\frac{\sigma^2}{n}\)</span></li>
</ul>
<p>where <span class="math inline">\(\sigma^2\)</span> is the variance of <span class="math inline">\(X\)</span>. We call <span class="math inline">\(se=\frac{\sigma}{\sqrt{n}}\)</span> the <strong>standard error</strong></p>
<p>when we take the values of the random sample then we take the value of <span class="math inline">\(\bar{x}\)</span> as the the value of the mean. That is</p>
<p><span class="math display">\[\bar{x}=\hat{\mu}\]</span></p>
<p>Since <span class="math inline">\(\bar{X}\)</span> is a random variable the estimation of the mean changes when we take another sample.</p>
</div>
<div id="margin-of-error-1" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> Margin of error<a href="interval-estimation.html#margin-of-error-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When deciding whether the <strong>error</strong> in estimation <span class="math display">\[\bar{X}-\mu\]</span> is large or not we usually compare it with a predefined tolerance. <strong>If we know</strong> that the the distribution of <span class="math inline">\(X\)</span> is normal <span class="math inline">\(X \rightarrow N(\mu, \sigma^2)\)</span>, we can compute how far the estimation of <span class="math inline">\(\bar{x}\)</span> falls from <span class="math inline">\(\mu\)</span>.</p>
<p>We defined the <strong>margin of error</strong> at <span class="math inline">\(5\%\)</span> level as the distance <span class="math inline">\(m\)</span> such that distribution of <span class="math inline">\(\bar{X}\)</span> captures <span class="math inline">\(95\%\)</span> of the estimations:</p>
<p><span class="math display">\[P(-m \leq \bar{X}-\mu \leq m)=P(\mu-m \leq \bar{X} \leq\mu + m)=0.95\]</span></p>
<p>If <span class="math inline">\(\bar{X}\)</span> is normally distributed then the marging of error is</p>
<p><span class="math display">\[m=z_{0.025} \frac{\sigma}{\sqrt{n}}=1.96\times se\]</span>
where <span class="math inline">\(z_{0.025}=\phi^{-1}(0.975)=\)</span> <code>qnorm(0.975)</code></p>
<p><strong>Example (cables):</strong></p>
<p>We perform take a random sample of size <span class="math inline">\(8\)</span>: Load a cable until it breaks and record the breaking load.</p>
<p><strong>If we know</strong> that our cables truly distribute as <span class="math display">\[X \rightarrow N(\mu=13, \sigma^2=0.35^2)\]</span> then</p>
<p><span class="math display">\[\bar{X} \rightarrow N(13, \frac{0.35^2}{8})\]</span></p>
<p>With mean <span class="math inline">\(E(\bar{X})=13\)</span> and standard error <span class="math inline">\(se=\frac{0.35}{\sqrt{8}}=0.1237\)</span></p>
<p>Therefore the marging of error at <span class="math inline">\(95\%\)</span> is</p>
<p><span class="math display">\[m=z_{0.025} \frac{\sigma}{\sqrt{n}}=1.96\times se=1.96\frac{0.35}{\sqrt{8}}=0.24\]</span>
Now, we take the random sample and find the results</p>
<pre><code>## [1] 13.34642 13.32620 13.01459 13.10811 12.96999 13.55309 13.75557 12.62747</code></pre>
<p>The observed average is <span class="math inline">\(\bar{x}=13.21\)</span>, and the error we would make if we replaced <span class="math inline">\(\mu\)</span> by <span class="math inline">\(\bar{x}\)</span>, would be</p>
<p><span class="math display">\[\bar{x}-\mu=13.21-13=0.21\]</span>
The <strong>observed error</strong> is within the margin of error</p>
<p><span class="math display">\[\bar{x}-\mu &lt;m\]</span>
Replacing <span class="math inline">\(\mu\)</span> by <span class="math inline">\(\bar{x}\)</span> is called a <strong>point estimation</strong> of the parameter.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<p><img src="_main_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
</div>
<div id="interval-estimation-for-the-mean" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> Interval estimation for the mean<a href="interval-estimation.html#interval-estimation-for-the-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The problem is that in real life we <strong>do not know</strong> the real values of <span class="math inline">\(\mu\)</span> or <span class="math inline">\(\sigma\)</span> for</p>
<p><span class="math display">\[X \rightarrow N(\mu, \sigma^2)\]</span>
We start by taking the sample</p>
<p><img src="_main_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
<p>and then computing the mean</p>
<p><img src="_main_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>What is the value of <span class="math inline">\(\mu\)</span>?</p>
<p>Our data suggest that it is <span class="math inline">\(\bar{x}=13.21\)</span>, but how <strong>confident</strong> are we? after all we know we are making a mistake but do not how big it is. Lets define the confidence interval for <span class="math inline">\(\mu\)</span></p>
<p>From the margin of error equation</p>
<p><span class="math display">\[P(-m \leq \bar{X} - \mu \leq  m)=0.95\]</span>
let’s solve for <span class="math inline">\(\mu\)</span> which is <strong>the real unknown</strong></p>
<p><span class="math display">\[P(\bar{X} - m \leq \mu \leq \bar{X} + m)=0.95\]</span></p>
<p>The left and right limits of the inequality are random variables which motivate the definition for the <strong>random confidence interval at <span class="math inline">\(95\%\)</span>:</strong></p>
<p><span class="math display">\[(L,U)=(\bar{X} - m,\bar{X} + m)\]</span></p>
<p>This interval is a new <strong>random variable</strong> and it has by definition a probability of <span class="math inline">\(0.95\)</span> to contain <span class="math inline">\(\mu\)</span>.</p>
<p>The <strong>observed interval</strong> that we obtain from the experiment is (script size)</p>
<p><span class="math display">\[(l,u)=(\bar{x} - m,\bar{x} + m)\]</span></p>
<p>This interval either contains or does not the parameter <span class="math inline">\(\mu\)</span>: we will <strong>never know</strong>!</p>
<p>We say that we have a confidence of <span class="math inline">\(95\%\)</span> that the interval <span class="math inline">\((l,u)\)</span> will capture the true unknown parameter <span class="math inline">\(\mu\)</span>. Think of buying a lottery scratch ticket that we cannot scratch to see the prize. The ticket either has or has not the prize, only that we do not know which case it is.</p>
<div id="case-1-known-variance" class="section level3 hasAnchor" number="13.4.1">
<h3><span class="header-section-number">13.4.1</span> Case 1 (known variance)<a href="interval-estimation.html#case-1-known-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Confidence intervals can be estimated in different cases. The first case is when</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(X\)</span> is a normal variable</li>
<li>and we know the value of <span class="math inline">\(\sigma\)</span></li>
</ol>
<p>the confidence interval at <span class="math inline">\(95\%\)</span> is</p>
<p><span class="math display">\[(l,u)=(\bar{x} - m, \bar{x} + m)\]</span>
where <span class="math display">\[m=z_{0.025} \frac{\sigma}{\sqrt{n}}\]</span></p>
<p>That is:</p>
<p><span class="math display">\[(l,u)=(\bar{x} - z_{0.025} \frac{\sigma}{\sqrt{n}}, \bar{x} + z_{0.025} \frac{\sigma}{\sqrt{n}})\]</span></p>
<p><strong>Example (cables):</strong></p>
<p>In our example, we assume that <span class="math inline">\(X\)</span> is normally distributed and that we know <span class="math inline">\(\sigma^2=0.35^2\)</span>.</p>
<ol style="list-style-type: decimal">
<li>Since <span class="math inline">\(\bar{X}\)</span> is normal, the margin of error is</li>
</ol>
<p><span class="math display">\[m=z_{0.025} \frac{\sigma}{\sqrt{n}}\]</span>
2. Since we know <span class="math inline">\(\sigma^2==0.35^2\)</span>, then the <span class="math inline">\(95\%\)</span> confidence interval is</p>
<p><span class="math inline">\((l,u)=(\bar{x} - m, \bar{x} + m)=\)</span> <span class="math display">\[(\bar{x}-z_{0.025} \frac{\sigma}{\sqrt{n}}, \bar{x}+z_{0.025} \frac{\sigma}{\sqrt{n}})= (12.97,13.45)\]</span></p>
<p>or we can also write it as</p>
<p><span class="math display">\[\hat{\mu}=\bar{x}  \pm m = 13.21 \pm 0.24\]</span>
This means that, when estimating the mean by the average, we are confident about the units but not so much about the decimal places.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>Remember that the confidence interval <span class="math inline">\((l,u)\)</span> is an observation of the random confidence interval <span class="math inline">\((L,U)\)</span>. Therefore, every time that we obtain a new sample then <span class="math inline">\((l,u)\)</span> change. If we perform <span class="math inline">\(100\)</span> samples of size <span class="math inline">\(n\)</span> then <span class="math inline">\(95%\)</span> of the confidence intervals will contain <span class="math inline">\(\mu\)</span>, we jsut do not know which!</p>
<p><img src="_main_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
</div>
<div id="confidence-level" class="section level3 hasAnchor" number="13.4.2">
<h3><span class="header-section-number">13.4.2</span> Confidence level<a href="interval-estimation.html#confidence-level" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can change our confidence from <span class="math inline">\(95\%\)</span> to <span class="math inline">\(99\%\)</span>. When we computed the margin of error at <span class="math inline">\(95\%\)</span>, we left out <span class="math inline">\(\alpha=0.05\)</span> probability, <span class="math inline">\(0.025\)</span> on each side.</p>
<p>Now, we can leave out <span class="math inline">\(\alpha=0.01\)</span> probability, <span class="math inline">\(0.005\)</span> on each side. Therefore the <span class="math inline">\(99\%\)</span> confidence interval is</p>
<p><span class="math inline">\((l,u) = (\bar{x} - z_{0.005}\frac{\sigma}{\sqrt{n}},\bar{x} + z_{0.005}\frac{\sigma}{\sqrt{n}})\)</span></p>
<p><span class="math display">\[= (\bar{x} - 2.58\frac{\sigma}{\sqrt{n}},\bar{x} + 2.58\frac{\sigma}{\sqrt{n}})\]</span></p>
<p><img src="figures/phi.JPG" /></p>
<p>where <span class="math inline">\(z_{0.005}=\phi^{-1}(0.995)=\)</span> <code>qnorm(0.995)</code>. We can also write it as</p>
<p><span class="math display">\[\hat{\mu}=\bar{x} \pm 2.58\frac{\sigma}{\sqrt{n}}\]</span>
For our cables, the <span class="math inline">\(99\%\)</span> confidence interval is</p>
<p><span class="math display">\[\hat{\mu}= 13.21 \pm 0.31\]</span></p>
<p>If we want to be more confident then we need larger confidence intervals!</p>
<p><strong>Example (Impact energy):</strong></p>
<p>A metallic material is tested for impact to measure the energy required to cut it at a given temperature. Ten specimens of A238 steel were cut at 60ºC at the following impact energies (J):</p>
<p><span class="math inline">\(64.1, 64.7, 64.5, 64.6, 64.5, 64.3, 64.6, 64.8, 64.2, 64.3\)</span></p>
<p>If we <strong>asume</strong> that the impact energy is normally distributed with <span class="math inline">\(\sigma=1J\)</span> what is the <span class="math inline">\(95\%\)</span> confidence interval for the mean of these data?</p>
<p>We know</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(X \rightarrow N(\mu, \sigma^2)\)</span></li>
<li><span class="math inline">\(\sigma=1J\)</span></li>
<li><span class="math inline">\(\alpha=0.05\)</span> (the confidence limit)</li>
</ol>
<p>The <span class="math inline">\(95\%\)</span> confidence interval is then</p>
<p><span class="math inline">\((l,u)=(\bar{x}-1.96 \frac{\sigma}{\sqrt{n}}, \bar{x}+1.96 \frac{\sigma}{\sqrt{n}})\)</span>
<span class="math display">\[=(64.46-1.96 \frac{1}{\sqrt{10}}, 64.46+1.96  \frac{1}{\sqrt{10}})=(63.84,65.08)\]</span></p>
<p>or</p>
<p><span class="math display">\[\hat{\mu}=64.46 \pm 0.61\]</span></p>
<p>this tells us that we can be sure on the first digit (6), somewhat confident on the second (4), and unsure on the decimals (46).</p>
<p>In R:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="interval-estimation.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BSDA) </span></code></pre></div>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;BSDA&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:datasets&#39;:
## 
##     Orange</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="interval-estimation.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">z.test</span>(<span class="fu">c</span>(<span class="fl">64.1</span>, <span class="fl">64.7</span>, <span class="fl">64.5</span>, <span class="fl">64.6</span>, <span class="fl">64.5</span>, <span class="fl">64.3</span>, <span class="fl">64.6</span>, <span class="fl">64.8</span>, <span class="fl">64.2</span>, <span class="fl">64.3</span>), </span>
<span id="cb32-2"><a href="interval-estimation.html#cb32-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">sigma.x=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
##  One-sample z-Test
## 
## data:  c(64.1, 64.7, 64.5, 64.6, 64.5, 64.3, 64.6, 64.8, 64.2, 64.3)
## z = 203.84, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  63.8402 65.0798
## sample estimates:
## mean of x 
##     64.46</code></pre>
<p>What if <span class="math inline">\(\sigma^2\)</span> is <strong>unknown</strong>?</p>
</div>
</div>
<div id="marging-of-error-for-unkown-variance" class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> Marging of error for unkown variance<a href="interval-estimation.html#marging-of-error-for-unkown-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We were able to compute the confidence interval <span class="math inline">\((l,u)=(\bar{x} -m, \bar{x} -m)\)</span> because we were able to find the margin of error</p>
<p><span class="math display">\[m=1.96 \frac{\sigma}{\sqrt{n}}\]</span>
since <strong>we knew</strong> <span class="math inline">\(\sigma\)</span>. <span class="math inline">\(\sigma\)</span> is a parameter of the distribution that we usually <strong>do not know</strong>, likewise <span class="math inline">\(\mu\)</span>. To find the margin of error with <strong>unknown</strong> variance, we need the following theorem, due to Gosset</p>
<div id="theorem-t-statistic" class="section level3 hasAnchor" number="13.5.1">
<h3><span class="header-section-number">13.5.1</span> Theorem (T-statistic)<a href="interval-estimation.html#theorem-t-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When <span class="math inline">\(X\)</span> is normal then the standardized statistic</p>
<p><span class="math display">\[T=\frac{\bar{X}-\mu}{\frac{S}{\sqrt{n}}}\]</span>
Follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom, where <span class="math inline">\(S^2=\frac{1}{n-1} \sum_{i=1}^n (X_i-\bar{X})^2\)</span>. We can therefore compute probabilities for <span class="math inline">\(\bar{X}\)</span>, even if we do not know <span class="math inline">\(\sigma\)</span>.</p>
<p>Let’s look at some probability densities in the family of the <span class="math inline">\(T\)</span> distributions.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<p>Now we need to recompute the the margin of error <span class="math inline">\(m\)</span> at <span class="math inline">\(5\%\)</span> level when We use the <span class="math inline">\(t\)</span>-distribution</p>
<p><span class="math inline">\(P(\mu-m \leq \bar{X} \leq\mu + m)\)</span>
<span class="math display">\[=P(-\frac{m}{s/\sqrt{n}} \leq T \leq\frac{m}{s/\sqrt{n}})=0.95\]</span></p>
<p><span class="math display">\[m=t_{0.025, n-1} \frac{s}{\sqrt{n}}\]</span>
where <span class="math inline">\(t_{0.025, n-1}\)</span> is the value <span class="math inline">\(T\)</span> that leaves <span class="math inline">\(2.5\%\)</span> of probability at the right hand side of the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
</div>
<div id="case-2-unknown-variance" class="section level3 hasAnchor" number="13.5.2">
<h3><span class="header-section-number">13.5.2</span> Case 2 (unknown variance)<a href="interval-estimation.html#case-2-unknown-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The second case to compute confidence intervals is more realistic. If</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(X\)</span> is a normal variable</li>
</ol>
<p>the confidence interval at <span class="math inline">\(95\%\)</span> is</p>
<p><span class="math display">\[(l,u)=(\bar{x} - m, \bar{x} + m)\]</span>
where <span class="math display">\[m=t_{0.025, n-1} \frac{s}{\sqrt{n}}\]</span></p>
<p>That is:</p>
<p><span class="math display">\[(l,u)=(\bar{x} - t_{0.025, n-1} \frac{s}{\sqrt{n}}, \bar{x} + t_{0.025, n-1} \frac{s}{\sqrt{n}})\]</span>
where <span class="math inline">\(t_{0.025, n-1}=F^{-1}(0.975)\)</span><code>=qt(0.975, n-1)</code></p>
<p><strong>Example (Impact energy):</strong></p>
<p>A metallic material is tested for impact to measure the energy required to cut it at a given temperature. Ten specimens of A238 steel were cut at 60ºC at the following impact energies (J):</p>
<p><span class="math inline">\(64.1, 64.7, 64.5, 64.6, 64.5, 64.3, 64.6, 64.8, 64.2, 64.3\)</span></p>
<p>If we <strong>asumme</strong> that the impact energy is normally distributed but we <strong>do not know</strong> the variance, what is the <span class="math inline">\(95\%\)</span> confidence interval for the mean of these data?</p>
<p>We know</p>
<ul>
<li><span class="math inline">\(\bar{x}=64.46\)</span></li>
<li><span class="math inline">\(s=0.227\)</span></li>
<li><span class="math inline">\(\alpha=0.05\)</span></li>
<li><span class="math inline">\(t_{0.025,9}=2.26\)</span> obtained from <span class="math inline">\(t_{0.025,9}=\)</span> <code>qt(0.975, 9)</code></li>
</ul>
<p>The confidence interval is then</p>
<p><span class="math inline">\((l,u)=(\bar{x}- t_{0.025,9}\frac{s}{\sqrt{n}},\bar{x}+t_{0.025,9} \frac{s}{\sqrt{n}})\)</span></p>
<p><span class="math display">\[=(64.46-2.26 \frac{0.227}{\sqrt{10}},64.46+2.26 \frac{0.227}{\sqrt{10}})\]</span> <span class="math display">\[=(64.29,64.62)\]</span></p>
<p>Note that when we assumed <span class="math inline">\(\sigma=1\)</span> the confidence interval <span class="math inline">\((63.84,65.08)\)</span> was larger. Data therefore suggests that <span class="math inline">\(\sigma&lt;1\)</span>.</p>
<p>In R, we can compute the confidence interval with:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="interval-estimation.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="fu">c</span>(<span class="fl">64.1</span>,<span class="fl">64.7</span>,<span class="fl">64.5</span>,<span class="fl">64.6</span>,<span class="fl">64.5</span>,<span class="fl">64.3</span>,<span class="fl">64.6</span>,<span class="fl">64.8</span>,<span class="fl">64.2</span>,<span class="fl">64.3</span>))</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  c(64.1, 64.7, 64.5, 64.6, 64.5, 64.3, 64.6, 64.8, 64.2, 64.3)
## t = 897.74, df = 9, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  64.29757 64.62243
## sample estimates:
## mean of x 
##     64.46</code></pre>
</div>
</div>
<div id="estimation-of-proportions" class="section level2 hasAnchor" number="13.6">
<h2><span class="header-section-number">13.6</span> Estimation of proportions<a href="interval-estimation.html#estimation-of-proportions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Example (vaccine):</strong></p>
<p>A random sample of <span class="math inline">\(400\)</span> patients was selected for testing a new vaccine for the influenza virus, after <span class="math inline">\(6\)</span> months of vaccination <span class="math inline">\(134\)</span> were ill. What is the expected efficacy of the vaccine?</p>
<p>Since each vaccination <span class="math inline">\(X_i\)</span> is Bernoulli trial</p>
<p><span class="math display">\[X \rightarrow Bernoulli(p)\]</span>
With mean <span class="math inline">\(\mu=p\)</span> and variance <span class="math inline">\(\sigma^2=p(1-p)\)</span>.</p>
<p>The sample is something like
<span class="math display">\[(x_1,x_2, x_3, ...x_n)=(0,1,0,.. 1, 0)_{400}\]</span> with <span class="math inline">\(136\)</span> ones and in a total of <span class="math inline">\(400\)</span> repetitions. The sample has a an average <span class="math inline">\(\bar{x}=\frac{1}{400}\sum_i^{400} x_i=134/400=0.34\)</span>. Since the sample mean is an unbiased estimator of <span class="math inline">\(\mu\)</span>, then we can have a point estimate for <span class="math inline">\(p\)</span></p>
<p><span class="math display">\[\hat{p}=\bar{x}=134/400=0.34\]</span></p>
<p>This makes sense because <span class="math inline">\(\bar{x}\)</span> is the observed relative frequency of ones <span class="math inline">\(f_1\)</span> in the sample. And as such it is an estimator of the probability of observing a one in a Bernoulli trial</p>
<p><span class="math display">\[f_1 =\hat{P}(X=1)\]</span>
This is is consistent with frequentist definition of probability that we saw in chapter 2. But how confident are we about this estimation? We want a confidence interval for <span class="math inline">\(p\)</span></p>
<div id="case-3-proportions" class="section level3 hasAnchor" number="13.6.1">
<h3><span class="header-section-number">13.6.1</span> Case 3 (proportions)<a href="interval-estimation.html#case-3-proportions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>When <span class="math inline">\(\hat{p}n&gt;5\)</span> and <span class="math inline">\((\hat{p}-1)n&gt;5\)</span>, the <strong>standardized statistic</strong> of <span class="math inline">\(\bar{X}\)</span> can be approximated by a standard distribution (CLT)</li>
</ol>
<p><span class="math display">\[Z=\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}= \frac{\bar{X}-p}{\big[\frac{p(1-p)}{n} \big]^{1/2}}\rightarrow N(0,1)\]</span>
and the <span class="math inline">\(95\%\)</span> CI interval of <span class="math inline">\(p\)</span> is:</p>
<p><span class="math display">\[CI=(l,u)=(\bar{x}-z_{0.025}\big[\frac{\bar{x}(1-\bar{x})}{n} \big]^{1/2},  \bar{x}+z_{0.025}\big[\frac{\bar{x}(1-\bar{x})}{n} \big]^{1/2})\]</span>
Where we estimate the Bernoulli variance <span class="math inline">\(\sigma=p(1-p)\)</span> by <span class="math inline">\(\hat{\sigma}=\bar{x}(1-\bar{x})\)</span>. That is <span class="math inline">\(\hat{\sigma}=\sqrt{\bar{x}(1-\bar{x})}\)</span>.</p>
<p><strong>Example (vaccine):</strong></p>
<p>In our case, we are counting failures on vaccinations <span class="math inline">\(134\)</span> in <span class="math inline">\(400\)</span> trials.</p>
<p>we know</p>
<ul>
<li><span class="math inline">\(\bar{x}=134/400=0.34\)</span></li>
<li><span class="math inline">\(z_{0.025}=1.96\)</span></li>
</ul>
<p>Therefore the <span class="math inline">\(95\%\)</span> confidence interval for <span class="math inline">\(p\)</span> is</p>
<p><span class="math inline">\((l,u)=(\bar{x}-1.96 \big[\frac{\bar{x}(1-\bar{x})}{n} \big]^{1/2}, \bar{x}+1.96 \big[\frac{\bar{x}(1-\bar{x})}{n} \big]^{1/2})\)</span></p>
<p><span class="math display">\[=(0.29,0.38)\]</span></p>
<p>The probability of failure of the vaccine is</p>
<p><span class="math display">\[\hat{p}=0.34 \pm 0.05\]</span></p>
<p>Note: Voting intention surveys (Bernoulli test) in a sample of <span class="math inline">\(n\)</span> individuals report this type of estimation with its <strong>margin of error</strong>. It does not mean that the <strong>true value</strong> of <span class="math inline">\(p\)</span> falls within this interval with probability <span class="math inline">\(95\%\)</span>. It means that we are <span class="math inline">\(95\%\)</span> confident that we have caught the <span class="math inline">\(p\)</span> that this particular sample represents.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="interval-estimation.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">134</span>, <span class="dv">400</span>, <span class="at">correct=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  134 out of 400, null probability 0.5
## X-squared = 43.56, df = 1, p-value = 4.112e-11
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.2905091 0.3826300
## sample estimates:
##     p 
## 0.335</code></pre>
</div>
</div>
<div id="estimation-of-the-variance" class="section level2 hasAnchor" number="13.7">
<h2><span class="header-section-number">13.7</span> Estimation of the variance<a href="interval-estimation.html#estimation-of-the-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have seen that whenever we take a random sample <span class="math inline">\((X_1, X_2, ... X_n)\)</span>, the sample variance
<span class="math display">\[S^2=\frac{1}{n-1}\sum_{i=1}^n (X_i-\bar{X})^2\]</span>
is an estimator of the mean <span class="math inline">\(\sigma^2\)</span> of the random variable <span class="math inline">\(X\)</span>. The estimator is <strong>unbiased</strong></p>
<ul>
<li><span class="math inline">\(E(S^2)=\sigma\)</span></li>
</ul>
<p>and it is also <strong>consistent</strong>. When we take the values of the random sample, then we take the value of <span class="math inline">\(S^2\)</span> as the the value of the variance; that is</p>
<p><span class="math display">\[s^2=\hat{\sigma}^2\]</span></p>
<p>Since <span class="math inline">\(S^2\)</span> is a random variable the estimation of the variance changes when we take another sample.</p>
<p><strong>Example (impact energy)</strong></p>
<p>A metallic material is tested for impact to measure the energy required to cut it at a given temperature. Ten specimens of A238 steel were cut at 60ºC at the following impact energies (J):</p>
<p><span class="math inline">\(64.1, 64.7, 64.5, 64.6, 64.5, 64.3, 64.6, 64.8, 64.2, 64.3\)</span></p>
<p>what is estimation of the variance of these data?</p>
<p><span class="math display">\[s^2=0.05155556\]</span>
In R: <code>sd(c(64.1, 64.7, 64.5, 64.6, 64.5, 64.3, 64.6, 64.8, 64.2, 64.3))^2 </code></p>
<p>How confident are we on the decimals of the estimation?</p>
</div>
<div id="confidence-interval-for-the-variance" class="section level2 hasAnchor" number="13.8">
<h2><span class="header-section-number">13.8</span> Confidence interval for the variance<a href="interval-estimation.html#confidence-interval-for-the-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To compute a confidence interval of for the variance, we need a statistics that is a function of <span class="math inline">\(S^2\)</span> and allows us to compute probabilities. We will use the following theorem</p>
<div id="theorem-chi2" class="section level3 hasAnchor" number="13.8.1">
<h3><span class="header-section-number">13.8.1</span> Theorem (<span class="math inline">\(\chi^2\)</span>):<a href="interval-estimation.html#theorem-chi2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When <span class="math inline">\(X\)</span> is normal then the standardized statistic</p>
<p><span class="math display">\[W=\frac{S^2(n-1)}{\sigma^2}\]</span>
follows a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom</p>
<p><span class="math display">\[\frac{S^2}{\sigma^2}(n-1)\rightarrow \chi^2_{n-1}\]</span></p>
<p>We can therefore compute probabilities for <span class="math inline">\(W\)</span>.</p>
<p>Let’s look at some probability densities in the family of the <span class="math inline">\(\chi^2\)</span> distriutions.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-99-1.png" width="672" /></p>
</div>
<div id="confidence-interval-for-the-variance-1" class="section level3 hasAnchor" number="13.8.2">
<h3><span class="header-section-number">13.8.2</span> Confidence interval for the variance<a href="interval-estimation.html#confidence-interval-for-the-variance-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We look for confidence interval of <span class="math inline">\(\sigma^2\)</span> at confidence <span class="math inline">\(95\%\)</span> <span class="math inline">\((L,U)\)</span> such that <span class="math display">\[P(L \leq \sigma^2 \leq U)=0.95\]</span></p>
<p>We can then use the <span class="math inline">\(\chi^2\)</span> to determine the <span class="math inline">\(95\%\)</span> of the distribution about <span class="math inline">\(W\)</span>. Lets start by defining the values that capture the <span class="math inline">\(95\%\)</span> of the distribution</p>
<p><span class="math display">\[P(\chi^2_{0.975,n-1} \leq W \leq \chi^2_{0.025,n-1})=0.95\]</span>
Replacing the value of <span class="math inline">\(W\)</span></p>
<p><span class="math display">\[P(\chi^2_{0.975,n-1} \leq \frac{S^2}{\sigma^2}(n-1) \leq \chi^2_{0.025,n-1})=0.95\]</span></p>
<p>and solving for <span class="math inline">\(\sigma^2\)</span></p>
<p><span class="math display">\[P(\frac{S^2 (n-1)}{\chi^2_{0.025,n-1}}\leq \sigma^2 \leq \frac{S^2(n-1)}{\chi^2_{0.975,n-1}})=0.95\]</span></p>
<p>We find a random interval that captures <span class="math inline">\(\sigma^2\)</span>
with <span class="math inline">\(95\%\)</span> confidence</p>
<p><span class="math display">\[(L,U) = (\frac{S^2 (n-1)}{\chi^2_{0.025,n-1}},\frac{S^2(n-1)}{\chi^2_{0.975,n-1}})\]</span></p>
</div>
<div id="case-4-variance" class="section level3 hasAnchor" number="13.8.3">
<h3><span class="header-section-number">13.8.3</span> Case 4 (variance)<a href="interval-estimation.html#case-4-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>When <span class="math inline">\(X\)</span> is a normal variable</li>
</ol>
<p>The <strong>observed</strong> <span class="math inline">\(95\%\)</span> confidence interval (script size) is</p>
<p><span class="math display">\[(l,u) = (\frac{s^2 (n-1)}{\chi^2_{0.025,n-1}},\frac{s^2(n-1)}{\chi^2_{0.975,n-1}})\]</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(\chi^2_{0.975,n-1}=F^{-1}(0.025)=\)</span> <code>qchisq(0.025, df=n-1)</code></p></li>
<li><p><span class="math inline">\(\chi^2_{0.025,n-1}=F^{-1}(0.975)=\)</span><code>qchisq(0.975, df=n-1)</code>
</br>for <span class="math inline">\(n=10\)</span> or <span class="math inline">\(df=n-1=9\)</span></p></li>
</ul>
<p><strong>Example (impact energy)</strong></p>
<p>A metallic material is tested for impact to measure the energy required to cut it at a given temperature. Ten specimens of A238 steel were cut at 60ºC at the following impact energies (J):</p>
<p><span class="math inline">\(64.1, 64.7, 64.5, 64.6, 64.5, 64.3, 64.6, 64.8, 64.2, 64.3\)</span></p>
<p>what is confidence interval for the variance of these data?</p>
<p><span class="math display">\[(l,u) = (\frac{s^2 (n-1)}{\chi^2_{0.025,n-1}},\frac{s^2(n-1)}{\chi^2_{0.975,n-1}})\]</span></p>
<ol style="list-style-type: decimal">
<li><p>The standard deviation of the data is <span class="math inline">\(s^2=0.05155556\)</span></p></li>
<li><p><span class="math inline">\(n=10\)</span></p></li>
<li><p>We then compute <span class="math inline">\(\chi^2_{0.025,n-1}\)</span> and <span class="math inline">\(\chi^2_{0.975,n-1}\)</span></p></li>
</ol>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="interval-estimation.html#cb38-1" aria-hidden="true" tabindex="-1"></a>chi0<span class="fl">.975</span> <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">9</span>)</span>
<span id="cb38-2"><a href="interval-estimation.html#cb38-2" aria-hidden="true" tabindex="-1"></a>chi0<span class="fl">.975</span></span></code></pre></div>
<pre><code>[1] 2.700389</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="interval-estimation.html#cb40-1" aria-hidden="true" tabindex="-1"></a>chi0<span class="fl">.025</span> <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="fl">0.975</span>, <span class="at">df=</span><span class="dv">9</span>)</span>
<span id="cb40-2"><a href="interval-estimation.html#cb40-2" aria-hidden="true" tabindex="-1"></a>chi0<span class="fl">.025</span></span></code></pre></div>
<pre><code>[1] 19.02277</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-100-1.png" width="672" /></p>
<p>Therefore</p>
<p><span class="math display">\[(l,u)= (\frac{0.227^2 (10-1)}{19.02277},\frac{0.227^2(10-1)}{2.700389})=(0.02,0.17)\]</span>
Note that when we computed the confidence interval for the mean and assumed <span class="math inline">\(\sigma^2=1\)</span> (case 1), this was not consistent with the data because the confidence interval does not contain the value <span class="math inline">\(\sigma^2=1\)</span>.
According to the data <span class="math inline">\(\sigma^2 \neq 1\)</span> at <span class="math inline">\(95\%\)</span> confidence.</p>
<p>in R:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="interval-estimation.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Ecfun)</span>
<span id="cb42-2"><a href="interval-estimation.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.var</span>(<span class="fl">0.05155556</span>, <span class="dv">9</span>)</span></code></pre></div>
<pre><code>##           lower     upper
## [1,] 0.02439183 0.1718271
## attr(,&quot;level&quot;)
## [1] 0.95</code></pre>
<p>The interval for the variance is <strong>not symmetric</strong> and we cannot formulate it as an estimate <span class="math inline">\(\pm\)</span> margin of error.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
</div>
</div>
<div id="questions-10" class="section level2 hasAnchor" number="13.9">
<h2><span class="header-section-number">13.9</span> Questions<a href="interval-estimation.html#questions-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>1)</strong> The margin of error at <span class="math inline">\(95\%\)</span> confidence of a normal variable is</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\(\frac{s}{\sqrt{n}}\)</span>;
<strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\(1.96\times se\)</span>;
<strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>;
<strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\(\sigma\)</span></p>
<p><strong>2)</strong> when we talk about <span class="math inline">\(z_{0.025}\)</span> we mean:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> The value of a normal standard variable that has accumulates up to <span class="math inline">\(75\%\)</span> of probability;
<strong><span class="math inline">\(\qquad\)</span>b:</strong> The value of a normal standard variable that has accumulates up to <span class="math inline">\(25\%\)</span> of probability;
<strong><span class="math inline">\(\qquad\)</span>c:</strong> The probability of standard variable up to <span class="math inline">\(75\%\)</span>;
<strong><span class="math inline">\(\qquad\)</span>d:</strong> The probability of standard variable up to <span class="math inline">\(25\%\)</span></p>
<p><strong>3)</strong> The random confident interval <span class="math inline">\((L,U)\)</span> for the mean at <span class="math inline">\(95\%\)</span></p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> is a two dimensional parameter of the sample distribution;
<strong><span class="math inline">\(\qquad\)</span>b:</strong> gives the limits where <span class="math inline">\(\mu\)</span> has a probability of occurring <span class="math inline">\(95\%\)</span> of the times;
<strong><span class="math inline">\(\qquad\)</span>c:</strong> is an estimate of the mean;
<strong><span class="math inline">\(\qquad\)</span>d:</strong> captures <span class="math inline">\(\mu\)</span> <span class="math inline">\(95\%\)</span> of the times</p>
<p><strong>4)</strong> A confidence interval for the mean written as <span class="math inline">\(\hat{\mu}=56.99 \pm 0.01\)</span></p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> indicates that we are <span class="math inline">\(\%99\)</span> confident that the mean is <span class="math inline">\(56.99\)</span>;
<strong><span class="math inline">\(\qquad\)</span>b:</strong> indicates that we cannot trust the last decimal place on the estimation of the mean;
<strong><span class="math inline">\(\qquad\)</span>c:</strong> indicates that the mean of the population is at <span class="math inline">\(56.99\)</span> with error <span class="math inline">\(0.01\)</span>;
<strong><span class="math inline">\(\qquad\)</span>d:</strong> indicates that we can trust the unit figure (<span class="math inline">\(6\)</span>) on the estimation of the mean</p>
<p><strong>5)</strong>If we know the value of <span class="math inline">\(\mu\)</span> and find that the confidence interval did not catch it then</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> the confidence interval is not well computed;
<strong><span class="math inline">\(\qquad\)</span>b:</strong> it is a rare observation of the confidence interval;
<strong><span class="math inline">\(\qquad\)</span>c:</strong> the confidence interval does not estimate the mean;
<strong><span class="math inline">\(\qquad\)</span>f:</strong> there is little probability of finding the mean in the confidence interval</p>
</div>
<div id="exercises-11" class="section level2 hasAnchor" number="13.10">
<h2><span class="header-section-number">13.10</span> Exercises<a href="interval-estimation.html#exercises-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-1-10" class="section level4 hasAnchor" number="13.10.0.1">
<h4><span class="header-section-number">13.10.0.1</span> Exercise 1<a href="interval-estimation.html#exercise-1-10" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In a scientific paper, the authors report a <span class="math inline">\(95\%\)</span> confidence interval of <span class="math inline">\((228, 232)\)</span> for the natural frequency (Hz) of a metallic beam. They used a sample of size <span class="math inline">\(25\)</span> and considered that the measurements were distributed normally.</p>
<ul>
<li><p>What is the mean and the standard deviation of the measurements?</p></li>
<li><p>Compute the <span class="math inline">\(99\%\)</span> confidence interval.</p></li>
</ul>
<p>hints:</p>
<ul>
<li><p>in R <span class="math inline">\(t_{0.025, 24}=\)</span> <code>qt(0.975, 24)</code><span class="math inline">\(\sim 2\)</span></p></li>
<li><p>in R <span class="math inline">\(t_{0.005, 24}=\)</span><code>qt(0.995, 24)</code><span class="math inline">\(\sim 2.8\)</span></p></li>
</ul>
</div>
<div id="exercise-2-10" class="section level4 hasAnchor" number="13.10.0.2">
<h4><span class="header-section-number">13.10.0.2</span> Exercise 2<a href="interval-estimation.html#exercise-2-10" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>compute <span class="math inline">\(95\%\)</span> CI the mean of a normal variable with known variance <span class="math inline">\(\sigma^2=9\)</span> and <span class="math inline">\(\bar{x}=22\)</span>, using a sample of size <span class="math inline">\(36\)</span>.</p>
</div>
<div id="exercise-3-7" class="section level4 hasAnchor" number="13.10.0.3">
<h4><span class="header-section-number">13.10.0.3</span> Exercise 3<a href="interval-estimation.html#exercise-3-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>This year, <span class="math inline">\(17\)</span> of <span class="math inline">\(1000\)</span> of patients with influenza developed complications.</p>
<ul>
<li><p>Compute the <span class="math inline">\(99\%\)</span> confidence interval for the proportion of complications.</p></li>
<li><p>The previous year <span class="math inline">\(2\%\)</span> showed complications. Can we say with <span class="math inline">\(99\%\)</span> confidence that this year there is a significant drop in influenza complications?</p></li>
</ul>
</div>
<div id="exercise-4-4" class="section level4 hasAnchor" number="13.10.0.4">
<h4><span class="header-section-number">13.10.0.4</span> Exercise 4<a href="interval-estimation.html#exercise-4-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>What is the confidence interval for population variance of a normal variable if we take a random sample of size <span class="math inline">\(n=10\)</span> and observe a sample variance of <span class="math inline">\(0.5\)</span>?</p>
</div>
</div>
<div id="practice-3" class="section level2 hasAnchor" number="13.11">
<h2><span class="header-section-number">13.11</span> Practice<a href="interval-estimation.html#practice-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Load misophonia data <code>data_0.txt</code></p>
<ul>
<li><p>Compute the confidence interval for the mean of the cephalometric measures. (“Angulo_convexidad,” “protusion.mandibular,” “Angulo_cuelloYtercio,” “Subnasal_H”)</p></li>
<li><p>Compute the confidence interval for the proportion of misophonic (“Misofonia.dic”), and depression (“depresion.dic”).</p></li>
<li><p>Compute the confidence interval for the variance of the age (“Edad”). What is the cofidence interval for the standard deviation of the population?</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="maximum-likelihood.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="hypothesis-testing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/13-InervalEstimation.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
