% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\title{EEBE stats}
\author{Alejandro Caceres}
\date{2023-09-17}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={EEBE stats},
  pdfauthor={Alejandro Caceres},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{objective}{%
\chapter{Objective}\label{objective}}

This is the introduction course to the statistics of the EEBE (UPC).

Statistics is a \textbf{language} that allows you to face new problems, on which we have no solution, and where the \textbf{randomness} plays a crucial role.

In this course we will discuss the \textbf{fundamental concepts} of statistics.

\begin{itemize}
\item
  3 hours of \textbf{Theory} per week: we will explain the concepts, we will exercise.
\item
  6 hours of \textbf{Individual study} per week: notes of course notes and resources in Athena.
\item
  2 hours of problem solving with \textbf{R}: face-to-face sessions (practices).
\end{itemize}

Exam dates and additional study material can be found in \textbf{ATENEA metacurso}:

\includegraphics{./figures/notas.JPG}

Evaluation objectives:

\textbf{Q1} (10\%): Test in computer Duration 2h on the indicated dates.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Basic command knowledge (practices)
\item
  Ability to calculate descriptive statistics and graphics, in specific situations (theory/practice)
\item
  Knowledge about linear regression (practices)
\end{enumerate}

\textbf{EP1} (25\%): Written test (2-3 problems)

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Capacity to interpret statements in probability formulas (theory).
\item
  Knowledge of the basic tools to solve problems of joint probability and conditional probability (theory).
\item
  Mathematical knowledge of probability functions to calculate its basic properties (theory).
\end{enumerate}

\textbf{Q2} (10\%): Test in computer Duration 2h on the indicated dates

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Capacity to identify probability models in concrete problems (theory/practice).
\item
  Use of R functions to calculate probabilities of probabilistic models (practice/theory)
\item
  Identification of a sampling statistic and its properties (theory/practice)
\item
  Knowledge of how to calculate the probability of sampling statistics (theory/practice)
\item
  Use of R commands to calculate probabilities and make random sampling simulations (practice)
\end{enumerate}

\textbf{EP2} (40\%): Written test (2-3 problems)

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Mathematical capacity to determine specific estimators of probability models.
\item
  Knowledge of the properties of specific estimators.
\item
  Knowledge of confidence intervals and their properties (theory).
\item
  Ability to identify the type of confidence interval in a specific problem (theory).
\item
  Knowledge
  of hypothesis types to be used in a specific problems (theory).
  f.Use of R commands to solve confidence intervals and hypothesis tests (practice).
\end{enumerate}

\textbf{CG} (5\%): Written test (2 questions about a text)

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Written expression capacity on a subject related to statistics.
\end{enumerate}

Coordinators:

\begin{itemize}
\tightlist
\item
  Luis Mujica (\href{mailto:Luis.eduardo.mujica@upc.edu}{\nolinkurl{Luis.eduardo.mujica@upc.edu}})
\item
  Pablo Buenestado (\href{mailto:Pablo.buenetado@upc.edu}{\nolinkurl{Pablo.buenetado@upc.edu}})
\end{itemize}

\hypertarget{recommended-reading}{%
\section{Recommended reading}\label{recommended-reading}}

\begin{itemize}
\item
  Class notes are our section will be accessible in Athena in PDF and HTML.
\item
  Douglas C. Montgomery and George C. Runger. ``Apply Statistics and Probability for Engineers'' 4th Edition. Wiley 2007.
\end{itemize}

\hypertarget{data-description}{%
\chapter{Data description}\label{data-description}}

In this chapter, we will introduce tools for describing data.

We will do so using tables, figures, and descriptive statistics of central tendency and dispersion.

We will also introduce key concepts in statistics such as randomized experiments, observations, outcomes, and absolute and relative frequencies.

\hypertarget{scientific-method}{%
\section{Scientific method}\label{scientific-method}}

One of the goals of the scientific method is to provide a framework for solving problems that arise in the study of natural phenomena or in the design of new technologies.

Modern humans have developed a \textbf{method} over thousands of years that is still in development.

The method has three main human activities:

\begin{itemize}
\tightlist
\item
  \emph{Observation} characterized by the acquisition of \textbf{data}
\item
  \emph{Reason} characterized by the development of mathematical \textbf{models}
\item
  \emph{Action} characterized by the development of new \textbf{experiments} (technology)
\end{itemize}

Their complex interaction and results are the basis of \emph{scientific activity}.

\includegraphics{./figures/stats.JPG}

\hypertarget{statistics}{%
\section{Statistics}\label{statistics}}

Statistics deals with the interaction between \emph{models} and \emph{data} (the bottom part of the figure).

The statistical questions are:

\begin{itemize}
\tightlist
\item
  What is the best model for my data (inference)?
\item
  What are the data that a certain model (prediction) would produce?
\end{itemize}

\hypertarget{data}{%
\section{Data}\label{data}}

The data is presented in the form of observations.

An \textbf{Observation} or \textbf{Realization} is the acquisition of a number or characteristic of an experiment.

For example, let's take the series of numbers produced by repeating an experiment (1: success, 0: failure).

\ldots{} 1 0 0 1 0 \textbf{1} 0 1 1 \ldots{}

The number in bold is \textbf{an observation} in a repeat of the experiment

An \textbf{outcome} is a \textbf{possible} observation that is the result of an experiment.

\textbf{1} is one result, \textbf{0} is the other result of the experiment.

Remember that the observation is \textbf{concrete} is the number you get one day in the laboratory. The \textbf{abstract} result is one of the characteristics of the type of experiment you are running.

\hypertarget{result-types}{%
\section{Result types}\label{result-types}}

In statistics we are mainly interested in two types of results.

\begin{itemize}
\item
  \textbf{Categorical}: If the result of an experiment is a quality. They can be nominal (binary: yes, no; multiple: colors) or ordinal when the qualities can be ranked (severity of a disease).
\item
  \textbf{Numeric}: If the result of an experiment is a number. The number can be discrete (number of emails received in an hour, number of leukocytes in the blood) or continuous (battery charge status, engine temperature).
\end{itemize}

\hypertarget{random-experiments}{%
\section{Random experiments}\label{random-experiments}}

It can be said that the subject of study of statistics is random experiments, the means by which we produce data.

\textbf{Definition:}

A \textbf{random experiment} is an experiment that gives different results when repeated in the same way.

Randomized experiments are of different types, depending on how they are conducted:

\begin{itemize}
\tightlist
\item
  on the same object (person): temperature, sugar levels.
  different objects but of the same size: the weight of an animal.
\item
  about events: the number of hurricanes per year.
\end{itemize}

\hypertarget{absolute-frequencies}{%
\section{Absolute frequencies}\label{absolute-frequencies}}

When we repeat a randomized experiment with \textbf{categorical} results, we record a list of results.

We summarize observations by counting how many times we saw a particular result.

\textbf{Absolute frecuency}:

\[ n_i \]

is the number of times we observe the result \(i\).

\newpage

\textbf{Example (leukocytes)}

Let's take a leukocyte from \textbf{a} donor and write down its type. Let's repeat the experiment \(N=119\) times.

\begin{verbatim}
(T cell, T cell, Neutrophil, ..., B cell)
\end{verbatim}

The second \textbf{T cell} in bold is the second observation. The last \textbf{B cell} is observation number 119.

We can list the \textbf{results} (categories) in a \textbf{frequency table}:

\begin{verbatim}
##      outcome ni
## 1     T Cell 34
## 2     B cell 50
## 3   basophil 20
## 4   Monocyte  5
## 5 Neutrophil 10
\end{verbatim}

From the table, we can say that, for example, \(n_1=34\) is the total number of T cells observed in the repeat experiment. We also note that the total number of repetitions \(N=\sum_i n_i = 119\).

\hypertarget{relative-frequencies}{%
\section{Relative frequencies}\label{relative-frequencies}}

We can also summarize observations by calculating the \textbf{proportion} of how many times we saw a particular result.

\[ f_i = n_i /N\] where \(N\) is the total number of observations

In our example, \(n_1=34\) T cells were recorded, so we asked about the proportion of T cells out of the total \(119\). We can add these proportions \(f_i\) in the frequency table.

\begin{verbatim}
##      outcome ni         fi
## 1     T Cell 34 0.28571429
## 2     B cell 50 0.42016807
## 3   basophil 20 0.16806723
## 4   Monocyte  5 0.04201681
## 5 Neutrophil 10 0.08403361
\end{verbatim}

Relative frequencies are \textbf{fundamental} in statistics. They give the proportion of one result in relation to the other results. Later we will understand them as the observations of probabilities.

For absolute and relative frequencies we have the properties

\begin{itemize}
\tightlist
\item
  \(\sum_{i=1..M} n_i = N\)
\item
  \(\sum_{i=1..M} f_i = 1\)
\end{itemize}

where \(M\) is the number of results.

\hypertarget{bar-chart}{%
\section{Bar chart}\label{bar-chart}}

When we have a lot of results and want to see which ones are most likely, we can use a bar chart that is a number of \(n_i\) Vs the results.

\includegraphics{_main_files/figure-latex/unnamed-chunk-3-1.pdf}

\hypertarget{pie-chart-pie}{%
\section{Pie chart (pie)}\label{pie-chart-pie}}

We can also visualize the relative frequencies with a pie chart.

The area of the circle represents 100\% of the observations (proportion = 1) and the sections the relative frequencies of each result.

\includegraphics{_main_files/figure-latex/unnamed-chunk-4-1.pdf}

\hypertarget{ordinal-categorical-variables}{%
\section{Ordinal categorical variables}\label{ordinal-categorical-variables}}

The leukocyte type in the above examples is a \textbf{categorical} nominal variable. Each observation belongs to a category (quality). The categories do not always have a certain order .

Sometimes \textbf{categorical} variables can be \textbf{sorted} when they meet a natural ranking. This allows you to compute \textbf{cumulative frequencies}.

\newpage

\textbf{Example (Misophonia)}

This is a clinical study on 123 patients who were examined for their degree of misophonia. Misophnia is uncontrolled anxiety/anger produced by certain sounds .

Each patient was evaluated with a questionnaire (AMISO) and they were classified into 4 different groups according to severity.

The results of the study are

\begin{verbatim}
##   [1] 4 2 0 3 0 0 2 3 0 3 0 2 2 0 2 0 0 3 3 0 3 3 2 0 0 0 4 2 2 0 2 0 0 0 3 0 2
##  [38] 3 2 2 0 2 3 0 0 2 2 3 3 0 0 4 3 3 2 0 2 0 0 0 2 2 0 0 2 3 0 1 3 2 4 3 2 3
##  [75] 0 2 3 2 4 1 2 0 2 0 2 0 2 2 4 3 0 3 0 0 0 2 2 1 3 0 0 3 2 1 3 0 4 4 2 3 3
## [112] 3 0 3 2 1 2 3 3 4 2 3 2
\end{verbatim}

Each observation is the result of a randomized experiment: measurement of the level of misophonia in a patient. This data series can be summarized in terms of the results in the frequency table

\begin{verbatim}
##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073
\end{verbatim}

\hypertarget{accumulated-absolute-and-relative-frequencies}{%
\section{Accumulated absolute and relative frequencies}\label{accumulated-absolute-and-relative-frequencies}}

Misophonia severity is \textbf{categorical} \textbf{ordinal} because its results can be ordered relative to its degree.

When the results can be ordered, it is useful to ask how many observations were obtained up to a given result. We call this number the \textbf{absolute cumulative frequency} up to the result \(i\):
\[N_i =\sum_{k= 1..i } n_k\]
It is also useful for calculating the \textbf{proportion} of observations up to a given result.

\[F_i =\sum_{k= 1..i } f_k\]

We can add these frequencies in the \textbf{frequency table}

\begin{verbatim}
##   outcome ni         fi  Ni        Fi
## 0       0 41 0.33333333  41 0.3333333
## 1       1  5 0.04065041  46 0.3739837
## 2       2 37 0.30081301  83 0.6747967
## 3       3 31 0.25203252 114 0.9268293
## 4       4  9 0.07317073 123 1.0000000
\end{verbatim}

Therefore, \textbf{67\%} of patients had misophonia up to severity \textbf{2} and \textbf{37\%} of patients had severity less than or equal to \textbf{1}.

\hypertarget{cumulative-frequency-graph}{%
\section{Cumulative frequency graph}\label{cumulative-frequency-graph}}

\(F_i\) is an important quantity because it allows us to define the accumulation of probabilities down to intermediate levels.

The probability of an intermediate level \(x\) (\(i\leq x< i+1\)) is just the accumulation up to the lower level \(F_x = F_i\).

\(F_x\) is therefore a function on a \textbf{continuous} range of values. We can draw it with respect to the results.

\includegraphics{_main_files/figure-latex/unnamed-chunk-8-1.pdf}

Therefore, we can say that \textbf{67\%} of the patients had misophonia up to severity \(2.3\), although \(2.3\) is not an observed outcome.

\hypertarget{numeric-variables}{%
\section{Numeric variables}\label{numeric-variables}}

The result of a random experiment can produce a number. If the number is \textbf{discrete}, we can generate a frequency table, with absolute, relative, and cumulative frequencies, and illustrate them with bar, pie, and cumulative charts.

When the number is \textbf{continuous} the frequencies are not useful, we are most likely to observe or not observe a particular continuous number.

\textbf{Example (misophonia)}

The researchers wondered if the convexity of the jaw would affect the severity of misophonia. The scientific hypothesis is that the angle of convexity of the jaw can influence hearing and its sensitivity. These are the mandibular convexity results (degrees) for each patient:

\begin{verbatim}
##   [1]  7.97 18.23 12.27  7.81  9.81 13.50 19.30  7.70 12.30  7.90 12.60 19.00
##  [13]  7.27 14.00  5.40  8.00 11.20  7.75  7.94 16.69  7.62  7.02  7.00 19.20
##  [25]  7.96 14.70  7.24  7.80  7.90  4.70  4.40 14.00 14.40 16.00  1.40  9.76
##  [37]  7.90  7.90  7.40  6.30  7.76  7.30  7.00 11.23 16.00  7.90  7.29  6.91
##  [49]  7.10 13.40 11.60 -1.00  6.00  7.82  4.80 11.00  9.00 11.50 16.00 15.00
##  [61]  1.40 16.80  7.70 16.14  7.12 -1.00 17.00  9.26 18.70  3.40 21.30  7.50
##  [73]  6.03  7.50 19.00 19.01  8.10  7.80  6.10 15.26  7.95 18.00  4.60 15.00
##  [85]  7.50  8.00 16.80  8.54  7.00 18.30  7.80 16.00 14.00 12.30 11.40  8.50
##  [97]  7.00  7.96 17.60 10.00  3.50  6.70 17.00 20.26  6.64  1.80  7.02  2.46
## [109] 19.00 17.86  6.10  6.64 12.00  6.60  8.70 14.05  7.20 19.70  7.70  6.02
## [121]  2.50 19.00  6.80
\end{verbatim}

\hypertarget{transforming-continuous-data}{%
\section{Transforming continuous data}\label{transforming-continuous-data}}

Since continuous outcomes cannot be counted (informatively), we transform them into ordered categorical variables.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  First we cover the range of observations in regular intervals of the same size (bins)
\end{enumerate}

\begin{verbatim}
## [1] "[-1.02,3.46]" "(3.46,7.92]"  "(7.92,12.4]"  "(12.4,16.8]"  "(16.8,21.3]"
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Then we map each observation to its interval: creating a categorical variable \textbf{ordered}; in this case with 5 possible outcomes
\end{enumerate}

\begin{verbatim}
##   [1] "(7.92,12.4]"  "(16.8,21.3]"  "(7.92,12.4]"  "(3.46,7.92]"  "(7.92,12.4]" 
##   [6] "(12.4,16.8]"  "(16.8,21.3]"  "(3.46,7.92]"  "(7.92,12.4]"  "(3.46,7.92]" 
##  [11] "(12.4,16.8]"  "(16.8,21.3]"  "(3.46,7.92]"  "(12.4,16.8]"  "(3.46,7.92]" 
##  [16] "(7.92,12.4]"  "(7.92,12.4]"  "(3.46,7.92]"  "(7.92,12.4]"  "(12.4,16.8]" 
##  [21] "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]"  "(16.8,21.3]"  "(7.92,12.4]" 
##  [26] "(12.4,16.8]"  "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]" 
##  [31] "(3.46,7.92]"  "(12.4,16.8]"  "(12.4,16.8]"  "(12.4,16.8]"  "[-1.02,3.46]"
##  [36] "(7.92,12.4]"  "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]" 
##  [41] "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]"  "(7.92,12.4]"  "(12.4,16.8]" 
##  [46] "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]"  "(12.4,16.8]" 
##  [51] "(7.92,12.4]"  "[-1.02,3.46]" "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]" 
##  [56] "(7.92,12.4]"  "(7.92,12.4]"  "(7.92,12.4]"  "(12.4,16.8]"  "(12.4,16.8]" 
##  [61] "[-1.02,3.46]" "(12.4,16.8]"  "(3.46,7.92]"  "(12.4,16.8]"  "(3.46,7.92]" 
##  [66] "[-1.02,3.46]" "(16.8,21.3]"  "(7.92,12.4]"  "(16.8,21.3]"  "[-1.02,3.46]"
##  [71] "(16.8,21.3]"  "(3.46,7.92]"  "(3.46,7.92]"  "(3.46,7.92]"  "(16.8,21.3]" 
##  [76] "(16.8,21.3]"  "(7.92,12.4]"  "(3.46,7.92]"  "(3.46,7.92]"  "(12.4,16.8]" 
##  [81] "(7.92,12.4]"  "(16.8,21.3]"  "(3.46,7.92]"  "(12.4,16.8]"  "(3.46,7.92]" 
##  [86] "(7.92,12.4]"  "(12.4,16.8]"  "(7.92,12.4]"  "(3.46,7.92]"  "(16.8,21.3]" 
##  [91] "(3.46,7.92]"  "(12.4,16.8]"  "(12.4,16.8]"  "(7.92,12.4]"  "(7.92,12.4]" 
##  [96] "(7.92,12.4]"  "(3.46,7.92]"  "(7.92,12.4]"  "(16.8,21.3]"  "(7.92,12.4]" 
## [101] "(3.46,7.92]"  "(3.46,7.92]"  "(16.8,21.3]"  "(16.8,21.3]"  "(3.46,7.92]" 
## [106] "[-1.02,3.46]" "(3.46,7.92]"  "[-1.02,3.46]" "(16.8,21.3]"  "(16.8,21.3]" 
## [111] "(3.46,7.92]"  "(3.46,7.92]"  "(7.92,12.4]"  "(3.46,7.92]"  "(7.92,12.4]" 
## [116] "(12.4,16.8]"  "(3.46,7.92]"  "(16.8,21.3]"  "(3.46,7.92]"  "(3.46,7.92]" 
## [121] "[-1.02,3.46]" "(16.8,21.3]"  "(3.46,7.92]"
\end{verbatim}

Therefore, instead of saying that the first patient had an angle of convexity of \(7.97\), we say that his angle was between the interval (or \textbf{bin}) \((7.92,12.4]\).

No other patients had an angle of \(7.97\), but many had angles between \((7.92,12.4]\).

\hypertarget{frequency-table-for-a-continuous-variable}{%
\section{Frequency table for a continuous variable}\label{frequency-table-for-a-continuous-variable}}

For a given regular partition of the interval of results into intervals, we can produce a frequency table as before

\begin{verbatim}
##        outcome ni         fi  Ni         Fi
## 1 [-1.02,3.46]  8 0.06504065   8 0.06504065
## 2  (3.46,7.92] 51 0.41463415  59 0.47967480
## 3  (7.92,12.4] 26 0.21138211  85 0.69105691
## 4  (12.4,16.8] 20 0.16260163 105 0.85365854
## 5  (16.8,21.3] 18 0.14634146 123 1.00000000
\end{verbatim}

\hypertarget{histogram}{%
\section{Histogram}\label{histogram}}

The histogram is the graph of \(n_i\) or \(f_i\) Vs the results in intervals (bins). The histogram depends on the size of the bins .

\includegraphics{_main_files/figure-latex/unnamed-chunk-13-1.pdf}

\newpage

This is a histogram with 20 bins .

\includegraphics{_main_files/figure-latex/unnamed-chunk-14-1.pdf}

We see that most people have angles within \((7, 8]\)

\hypertarget{cumulative-frequency-graph-1}{%
\section{Cumulative frequency graph}\label{cumulative-frequency-graph-1}}

We can also plot \(F_x\) against the results. Since \(F_x\) is of continuous range, we can order the observations (\(x_1 <... x_j < x_{j+1} < x_n\)) and therefore

\[F_x = \frac{k}{ n}\]

for \(x_{k} \leq x < x_{k+ 1}\) .

\(F_x\) is known as the \textbf{distribution} of the data. \(F_x\) does not depend on the size of the bin. However, its \textbf{resolution} depends on the amount of data.

\includegraphics{_main_files/figure-latex/unnamed-chunk-15-1.pdf}

\hypertarget{summary-statistics}{%
\section{Summary Statistics}\label{summary-statistics}}

Summary statistics are numbers calculated from the data that tell us important characteristics of the numerical variables (discrete or continuous).

For example, we have statistics that describe extreme values:

\begin{itemize}
\tightlist
\item
  \textbf{minimum}: the minimum result observed
\item
  \textbf{maximum}: the maximum result observed
\end{itemize}

\hypertarget{average-sample-mean}{%
\section{Average (sample mean)}\label{average-sample-mean}}

An important statistic that describes the central value of the results (where to expect most observations) is the \textbf{average}

\[\bar{x}=\frac{1}{N} \sum_{j= 1..N } x_j \]

where \(x_j\) is the \textbf{observation} \(j\) out of a total of \(N\).

\textbf{Example (Misophonia)}

The average convexity can be calculated directly from the \textbf{observations} in the usual way

\(\bar{x}= \frac{1}{ N}\sum_j x_j\)

\(= \frac{1}{ N}( 7.97 + 18.23 + 12.27... + 6.80) = 10.19894\)

For \textbf{categorically ordered} variables, we can \textbf{also} use the relative frequencies to calculate the average

\(\bar{x}=\frac{1}{ N}\sum_{i=1...N} x_j =\frac{1}{N}\sum_{i=1...M} x_i n_ {i}=\)
\[\sum_{i=1...M} x_i f_{i}\]

where we went from adding \(N\) \textbf{observations} to adding \(M\) \textbf{results}.

The form \(\bar{x}= \sum_{i = 1...M} x_i f_i\) shows that the average is the \textbf{center of gravity} of the results. As if each result had a mass density given by \(f_i\).

\textbf{Example (Misophonia)}

The average \textbf{severity} of misophonia in the study can be calculated from the relative frequencies of the \textbf{outcomes}

\begin{verbatim}
##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073
\end{verbatim}

\(\bar{x}=0*f_ {0}+ 1*f_{1}+2*f_{2}+3*f_{3}+4*f_{4}=1.691057\)

The average is also the center of gravity for continuous variables. That is the point where the relative frequencies balance.

\includegraphics{_main_files/figure-latex/unnamed-chunk-17-1.pdf}

\hypertarget{median}{%
\section{Median}\label{median}}

Another measure of centrality is the median. The median \(x_m\), or \(q_{0.5}\), is the value below which we find half of the observations. When we order the observations \(x_1 <... x_j < x_{j+1} < x_N\), we count them until we find half of them. Therefore, \(x_m\) is the observation such that \(m\) satisfies

\[\sum_{i\leq m} 1 = \frac{N}{2}\]
\textbf{Example (Misophonia)}

If we order the angles of convexity, we see that \(62\) observations (individuals) (\(N/2 \sim 123/2\)) are below \(7.96\). The \textbf{median convexity} is therefore \(q_{0.5}= x_{62}=7.96\)

\begin{verbatim}
##  [1] -1.00 -1.00  1.40  1.40  1.80  2.46  2.50  3.40  3.50  4.40  4.60  4.70
## [13]  4.80  5.40  6.00  6.02  6.03  6.10  6.10  6.30  6.60  6.64  6.64  6.70
## [25]  6.80  6.91  7.00  7.00  7.00  7.00  7.02  7.02  7.10  7.12  7.20  7.24
## [37]  7.27  7.29  7.30  7.40  7.50  7.50  7.50  7.62  7.70  7.70  7.70  7.75
## [49]  7.76  7.80  7.80  7.80  7.81  7.82  7.90  7.90  7.90  7.90  7.90  7.94
## [61]  7.95  7.96
\end{verbatim}

\begin{verbatim}
##  [1]  7.96  7.97  8.00  8.00  8.10  8.50  8.54  8.70  9.00  9.26  9.76  9.81
## [13] 10.00 11.00 11.20 11.23 11.40 11.50 11.60 12.00 12.27 12.30 12.30 12.60
## [25] 13.40 13.50 14.00 14.00 14.00 14.05 14.40 14.70 15.00 15.00 15.26 16.00
## [37] 16.00 16.00 16.00 16.14 16.69 16.80 16.80 17.00 17.00 17.60 17.86 18.00
## [49] 18.23 18.30 18.70 19.00 19.00 19.00 19.00 19.01 19.20 19.30 19.70 20.26
## [61] 21.30
\end{verbatim}

We cut the data at

\begin{verbatim}
## [1] 7.96
\end{verbatim}

to split them in half.

\newpage

In terms of frequencies, \(q_{0.5}\) makes the cumulative frequency \(F_x\) equal to \(0.5\)

\[\sum_{i = 0, ... m} f_i =F_{q_{0.5}}=0.5\]
that is

\[q_{ 0.5}= F^{-1}(0.5)\]

This last equation means that, in the distribution graph, the median \(q_{ 0.5}\) is the value of \(x\) at which we have climbed half of the total height of \(F\).

\includegraphics{_main_files/figure-latex/unnamed-chunk-21-1.pdf}

The mean and median are not always the same.

\includegraphics{_main_files/figure-latex/unnamed-chunk-22-1.pdf}

\hypertarget{dispersion}{%
\section{Dispersion}\label{dispersion}}

Other important summary statistics for observations are the \textbf{spread} statistics.

Many experiments may share their mean, but differ in how \textbf{sparse} the values are.

The dispersion of the observations is a measure of the \textbf{noise}.

\includegraphics{_main_files/figure-latex/unnamed-chunk-23-1.pdf} \includegraphics{_main_files/figure-latex/unnamed-chunk-23-2.pdf}

\hypertarget{sample-variance}{%
\section{Sample variance}\label{sample-variance}}

The dispersion about the mean is measured by the sample variance

\[s^2=\frac{ 1}{ N-1} \sum_{j=1..N} ( x_j -\bar{x})^2\]

This number measures the average squared distance of the \textbf{observations} from the average. The reason for \(N-1\) will be explained when we talk about inference, when we study the spread of \(\bar{x}\), as well as the spread of the observations.

In terms of the frequencies of the variables that are \textbf{categorical and ordered}, we can \textbf{also} calculate the sample variance as

\[s^2=\frac{N}{N-1} \sum_{i=1... M} (x_i -\bar{x})^2 f_i\]

\(s^2\) can be considered as the \textbf{moment of inertia} of the observations.

The square root of the sample variance, \(s\), is called \textbf{standard deviation} of the sample.

\textbf{Example (Misophonia)}

The standard deviation of the angle of convexity is

\(s= [\frac{ 1}{123-1}((7.97-10.19894)^2+ (18.23-10.19894)^2\)
\[+ (12.27-10.19894 )^ 2 + ...)]^{1/2} = 5.086707\]

The jaw convexity deviates from its mean by \(5.086707\).

\hypertarget{interquartile-range-iqr}{%
\section{Interquartile range (IQR)}\label{interquartile-range-iqr}}

The spread of the data can also be measured with respect to the median using the \textbf{interquartile range}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  We define the \textbf{first} quartile as the value \(x_m\) that makes the cumulative frequency \(F_{q_{0.25}}\) equal to \(0.25\) (or the value of \(x\) where we have accumulated a quarter of the observations, or the value that splits the first quarter of the observations)
\end{enumerate}

\[q_{0.25}=F^{-1}(0.25)\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  We define the \textbf{third} quartile as the value \(x_m\) that makes the cumulative frequency \(F_{q_{0.75}}\) equal to \(0.75\) (or the value of \(x\) where we have accumulated three quarters of observations)
\end{enumerate}

\[q_{0.75}=F^{-1}(0.75)\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  The \textbf{interquartile range} (IQR) is \[IQR=q_{0.75} - q_{0.25}\]
\end{enumerate}

This is the distance between the third and first quartiles and captures the central \(50\%\) of the observations

\includegraphics{_main_files/figure-latex/unnamed-chunk-24-1.pdf}

\hypertarget{boxplot}{%
\section{Boxplot}\label{boxplot}}

The interquartile range, median, and \(5\%\) and \(95\%\) of the data can be displayed in a \textbf{box plot}.

In the boxplot, the values of the results are on the y-axis. The IQR is the box, the median is the middle line, and the whiskers mark the \(5\%\) and \(95\%\) of the data.

\includegraphics{_main_files/figure-latex/unnamed-chunk-25-1.pdf}

\hypertarget{questions}{%
\section{Questions}\label{questions}}

\textbf{1)} In the following boxplot, the first quartile and second quartile of the data are:

\textbf{\(\qquad\)a:} \((-1.00, 21.30)\); \textbf{\(\qquad\)b:} \((-1.00, 7.02)\); \textbf{\(\qquad\)c:} \((7.02, 7.96)\); \textbf{\(\qquad\)d:} \((7.02, 14.22)\)

\textbf{2)} The main disadvantage of a histogram is that:

\textbf{\(\qquad\) a :} Depends on the size of the bin ; \textbf{\(\qquad\)b :} Cannot be used for categorical variables;

\textbf{\(\qquad\) c :} Cannot be used when the bin size is small;
\textbf{\(\qquad\) d :} Used only for relative frequencies;

\textbf{3)} If the relative cumulative frequencies of a random experiment with outcomes \(\{1,2,3,4\}\) are: \(F(1)=0.15, \qquad F(2)=0.60, \qquad F(3)=0.85, \qquad F(4)=1\).

Then the relative frequency for the outcome \(3\) is

\textbf{\(\qquad\)a:} \(0.15\); \textbf{\(\qquad\)b:} \(0.85\); \textbf{\(\qquad\)c:} \(0.45\); \textbf{\(\qquad\)d:} \(0.25\)

\textbf{4)} In a sample of size \(10\) from a random experiment we obtained the following data:

\(8, \qquad 3, \qquad 3, \qquad 7, \qquad 3, \qquad 6, \qquad 5, \qquad 10, \qquad 3, \qquad 8\).

The first quartile of the data is:

\textbf{\(\qquad\)a:} \(3.5\); \textbf{\(\qquad\)b:} \(4\); \textbf{\(\qquad\)c:} \(5\); \textbf{\(\qquad\)d:} \(3\)

\textbf{5)} Imagine that we collect data for two quantities that are not mutually exclusive, for example, the gender and nationality of passengers on a flight. If we want to make a single pie chart for the data, which of these statements is true?

\textbf{\(\qquad\)a :} We can \textbf{only} make a nationality pie chart because it has more than two possible outcomes;

\textbf{\(\qquad\)b :} We can make a pie graph for a new variable marking gender \textbf{and} nationality;

\textbf{\(\qquad\)c :} We can make a pie chart for the variable sex \textbf{or} the variable nationality;

\textbf{\(\qquad\)d :} We can only choose \textbf{whether} to make a pie chart for gender \textbf{or} a pie chart for nationality.

\hypertarget{exercises}{%
\section{Exercises}\label{exercises}}

\hypertarget{exercise-1}{%
\subsubsection{Exercise 1}\label{exercise-1}}

We have performed an experiment 8 times with the following results

\begin{verbatim}
## [1]  3  3 10  2  6 11  5  4
\end{verbatim}

Answer the following questions:

\begin{itemize}
\tightlist
\item
  Calculate the relative frequencies of each result.
\item
  Calculate the cumulative frequencies of each result.
\item
  What is the average of the observations?
\item
  What is the median?
\item
  What is the third quartile?
\item
  What is the first quartile?
\end{itemize}

\hypertarget{exercise-2}{%
\subsubsection{Exercise 2}\label{exercise-2}}

We have performed an experiment 10 times with the following results

\begin{verbatim}
##  [1] 2.875775 7.883051 4.089769 8.830174 9.404673 0.455565 5.281055 8.924190
##  [9] 5.514350 4.566147
\end{verbatim}

Consider 10 bins of size 1: {[}0,1{]}, (1,2{]} \ldots( 9,10).

Answer the following questions:

\begin{itemize}
\item
  Calculate the relative frequencies of each result and draw the histogram
\item
  Calculate the cumulative frequencies of each result and draw the cumulative graph.
\item
  Draw a box plot .
\end{itemize}

\hypertarget{probability}{%
\chapter{Probability}\label{probability}}

In this chapter we will introduce the concept of probability from relative frequencies.

We will define the events as the elements on which the probability is applied. Composite events will be defined using set algebra.

Then we will discuss the concept of conditional probability derived from the joint probability of two events.

\hypertarget{random-experiments-1}{%
\section{Random experiments}\label{random-experiments-1}}

Let's remember the basic objective of statistics. Statistics deals with data that is presented in the form of observations.

\begin{itemize}
\tightlist
\item
  An \textbf{observation} is the acquisition of a number or characteristic from an experiment
\end{itemize}

Observations are realizations of \textbf{results}.

\begin{itemize}
\tightlist
\item
  An \textbf{outcome} is a possible observation that is the result of an experiment.
\end{itemize}

When conducting experiments, we often get different results. The description of the variability of the results is one of the objectives of statistics.

\begin{itemize}
\tightlist
\item
  A \textbf{random experiment} is an experiment that gives different results when repeated in the same way.
\end{itemize}

The philosophical question behind it is how can we know something if every time we look at it it changes?

\hypertarget{measurement-probability}{%
\section{Measurement probability}\label{measurement-probability}}

We would like to have a measure for the outcome of a randomized experiment that tells us \textbf{how sure} we are of observing the outcome when we perform a \textbf{future} randomized experiment.

We will call this measure the probability of the outcome and assign values to it:

\begin{itemize}
\item
  0, when we are sure that the observation will \textbf{not} occur.
\item
  1, when we are sure that the observation will happen.
\end{itemize}

\hypertarget{classical-probability}{%
\section{Classical probability}\label{classical-probability}}

\textbf{As long as} a random experiment has \(M\) possible outcomes that are all \textbf{equally likely}, the probability of each \(i\) outcome is \[P_i =\frac{1}{ M}\].

Classical probability was defended by Laplace (1814).

Since every outcome is \textbf{equally likely} in this type of experiment, we declare complete ignorance and the best we can do is equally distribute the same probability for each outcome.

\begin{itemize}
\tightlist
\item
  We do not observe \(P_i\)
\item
  We deduce \(P_i\) from our ratio and we don't need to carry out any experiment to know it.
\end{itemize}

\textbf{Example (dice):}

What is the probability that we will get \(2\) on the roll of a die?

\(P_2=1/6=0.166666\).

\hypertarget{relative-frequencies-1}{%
\section{Relative frequencies}\label{relative-frequencies-1}}

What about random experiments whose possible outcomes are \textbf{not} equally likely?

How then can we define the probabilities of the outcomes?

\textbf{Example (random experiment)}

Imagine that we repeat a random experiment \(8\) times and obtain the following observations

8 4 12 7 10 7 9 12

\begin{itemize}
\tightlist
\item
  How sure are we of obtaining the result \(12\) in the following observation?
\end{itemize}

The frequency table is

\begin{verbatim}
##   outcome ni    fi
## 1       4  1 0.125
## 2       7  2 0.250
## 3       8  1 0.125
## 4       9  1 0.125
## 5      10  1 0.125
## 6      12  2 0.250
\end{verbatim}

\includegraphics{_main_files/figure-latex/unnamed-chunk-29-1.pdf}

The \textbf{relative frequency} \(f_i =\frac{ n_ i }{ N}\) seems like a reasonable probability measure because

\begin{itemize}
\tightlist
\item
  is a number between \(0\) and \(1\).
\item
  measures the proportion of the total number of observations that we observe of a particular result.
\end{itemize}

Since \(f_{12}=0.25\) then we would be one quarter sure, one out of every 4 observations, of getting \(12\).

\textbf{Question}: How good is \(f_i\) as a measure of certainty of the result \(i\)?

\textbf{Example (random experiment with more repetitions)}

Let's say we repeat the experiment 100,000 more times:

The frequency table is now

\begin{verbatim}
##    outcome    ni      fi
## 1        2  2807 0.02807
## 2        3  5607 0.05607
## 3        4  8435 0.08435
## 4        5 11070 0.11070
## 5        6 13940 0.13940
## 6        7 16613 0.16613
## 7        8 13806 0.13806
## 8        9 10962 0.10962
## 9       10  8402 0.08402
## 10      11  5581 0.05581
## 11      12  2777 0.02777
\end{verbatim}

and the barplot is

\includegraphics{_main_files/figure-latex/unnamed-chunk-31-1.pdf}

New results came out and \(f_{12}\) is now only \(0.027\), and so we are only \(\sim 3\%\) sure to get \(12\) in the next experiment. The probabilities measured by \(f_i\) change with \(N\).

\hypertarget{relative-frequencies-at-infinity}{%
\section{Relative frequencies at infinity}\label{relative-frequencies-at-infinity}}

A crucial observation is that if we measure the probabilities of \(f_i\) in increasing values of \(N\) they \textbf{converge}!

In this graph each vertical section gives the relative frequency of each observation. We see that after \(N=1000\) (\(log10(N)=3\)) the proportions hardly change with more \(N\).

\includegraphics{_main_files/figure-latex/unnamed-chunk-32-1.pdf}

We find that each of the relative frequencies \(f_i\) converges to a constant value

\[lim_{N\rightarrow \infty} f_i = P_i\]

\hypertarget{frequentist-probability}{%
\section{Frequentist probability}\label{frequentist-probability}}

We call \textbf{Probability} \(P_i\) the limit as \(N \rightarrow \infty\) of the \textbf{relative frequency} of observing the outcome \(i\) in a random experiment.

Defended by Venn (1876), the frequentist definition of probability is derived from (empirical) data/experience.

\begin{itemize}
\tightlist
\item
  We do not observe \(P_i\), we observe \(f_i\)
\item
  \textbf{We estimate} \(P_i\) with \(f_i\) (usually when \(N\) is large), we write: \[\hat {P_ i}= f_i\]
\end{itemize}

Similar to the relationship between \textbf{observation} and \textbf{result}, we have the relationship between \textbf{relative frequency} and \textbf{probability} as a concrete value of an abstract quantity.

\hypertarget{classical-and-frequentist-probabilities}{%
\section{Classical and frequentist probabilities}\label{classical-and-frequentist-probabilities}}

We have situations where classical probability can be used to find the limit of relative frequencies:

\begin{itemize}
\tightlist
\item
  If the results are \textbf{equally probable}, the classical probability gives us the limit:
\end{itemize}

\[P_i=lim_{N\rightarrow \infty} \frac{n_i}{N}=\frac{1}{M}\]

\begin{itemize}
\tightlist
\item
  If the results in which we are interested can be derived from other \textbf{equally probable} results. We will see more about this when we study probability models.
\end{itemize}

\textbf{Example (sum of two dice)}

Our previous example is based on the \textbf{sum of two dice}.
Although we perform the experiment many times, write down the results, and calculate the \textbf{relative frequencies}, we can know the exact value of probability.

This probability \textbf{follows} from the fact that the outcome of each die is \textbf{equally likely}. From this assumption, we can find that (Exercise 1)

\[
    P_i =
\begin{cases}
\frac{i-1}{36},& i \in \{2,3,4,5,6, 7\} \\
\frac{13-i}{36},& i \in \{8,9,10,11,12\} \\
\end{cases}
\]

The motivation of the frequentist definition is \textbf{empirical} (data) while that of the classical definition is \textbf{rational} (models). We often combine both approaches (inference and deduction) to find out the probabilities of our random experiment.

\includegraphics{./figures/prob.JPG}

\hypertarget{definition-of-probability}{%
\section{Definition of probability}\label{definition-of-probability}}

A probability is a number that is assigned to each possible outcome of a random experiment and satisfies the following properties or \textbf{axioms}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  when the results \(E_1\) and \(E_2\) are mutually exclusive; that is, only one of them can occur, so the probability of observing \(E_1\) \textbf{or} \(E_1\), written as \(E_1\cup E_2\), is their sum:
  \[ P( E_1\cup E_2) = P(E_1) + P(E_2)\]
\item
  when \(S\) is the set of all possible outcomes, then its probability is \(1\) (at least something is observed): \[P(S)=1\]
\item
  The probability of any outcome is between 0 and 1 \[P(E) \in [0,1]\]
\end{enumerate}

Proposed by Kolmogorov's less than 100 years ago (1933)

\hypertarget{probabilities-table}{%
\section{Probabilities Table}\label{probabilities-table}}

Kolmogorov properties are the basic rules for building a \textbf{probability table}, similar to the relative frequency table.

\textbf{Example (dice)}

The probability table for the throw of a dice

\begin{longtable}[]{@{}cc@{}}
\toprule
result & probability \\
\midrule
\endhead
\(1\) & 1/6 \\
\(2\) & 1/6 \\
\(3\) & 1/6 \\
\(4\) & 1/6 \\
\(5\) & 1/6 \\
\(6\) & 1/6 \\
\(P( 1 \cup 2\cup ... \cup 6)\) & 1 \\
\bottomrule
\end{longtable}

Let's verify the axioms:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  Where \(1 \cup 2\) is, for example, the \textbf{event} of rolling a \(1\) \textbf{or} a \(2\). So \[ P( 1 \cup 2)=P(1)+P(2)=2/6\]
\item
  Since \(S= \{ 1,2,3,4,5,6\}\) is made up of \textbf{mutually exclusive} outcomes, then
\end{enumerate}

\[P(S)=P(1\cup 2\cup ... \cup 6) = P(1)+P(2)+ ...+P(n)=1\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  The probabilities of each outcome are between \(0\) and \(1\).
\end{enumerate}

\hypertarget{sample-space}{%
\section{Sample space}\label{sample-space}}

The set of all possible outcomes of a random experiment is called the \textbf{sample space} and is denoted \(S\).

The sample space can be made up of categorical or numerical outcomes.

\emph{For example:}

\begin{itemize}
\tightlist
\item
  human temperature: \(S = (36, 42)\) degrees Celsius.
\item
  sugar levels in humans: \(S =( 70-80) mg/ dL\)
\item
  the size of a production line screw: \(S =( 70-72) mm\)
\item
  number of emails received in an hour: \(S = \{ 1, ...\infty \}\)
\item
  the throw of a dice: \(S= \{ 1, 2, 3, 4, 5, 6\}\)
\end{itemize}

\hypertarget{events}{%
\section{Events}\label{events}}

An \textbf{event} \(A\) is a \textbf{subset} of the sample space. It is a \textbf{collection} of posible results.

\emph{Examples of events:}

\begin{itemize}
\tightlist
\item
  The event of a healthy temperature: \(A=37-38\) degrees Celsius
\item
  The event of producing a screw with a size: \(A=71.5mm\)
\item
  The event of receiving more than 4 emails in an hour: \(A= \{ 4, \infty \}\)
\item
  The event of obtaining a number less than or equal to 3 in the roll of a says: \(A= \{ 1,2,3\}\)
\end{itemize}

An event refers to a possible set of \textbf{outcomes}.

\hypertarget{algebra-of-events}{%
\section{Algebra of events}\label{algebra-of-events}}

For two events \(A\) and \(B\), we can construct the following derived events using the basic set operations:

\begin{itemize}
\tightlist
\item
  Complement \(A'\): the event of \textbf{not} \(A\)
\item
  Union \(A \cup B\): the event of \(A\) \textbf{or} \(B\)
\item
  Intersection \(A \ cap B\): the event of \(A\) \textbf{and} \(B\)
\end{itemize}

\textbf{Example (dice)}

Let's roll a die and look at the events (result set):

\begin{itemize}
\tightlist
\item
  a number less than or equal to three \(A:\{ 1,2,3\}\)
\item
  an even number \(B:\{ 2,4,6\}\)
\end{itemize}

Let's see how we can build new events with set operations:

\begin{itemize}
\tightlist
\item
  a number not less than three: \(A ':\{4,5,6\}\)
\item
  a number less than or equal to three \textbf{or} even: \(A \cup B: \{ 1,2,3,4,6\}\)
\item
  a number less than or equal to three \textbf{and} even \(A \cap B: \{ 2\}\)
\end{itemize}

\hypertarget{mutually-exclusive-results}{%
\section{Mutually exclusive results}\label{mutually-exclusive-results}}

Outcomes like rolling \(1\) and \(2\) on a die are events that cannot occur at the same time. We say that they are \textbf{mutually exclusive}.

In general, two events denoted as \(E_1\) and \(E_2\) are mutually exclusive when

\[E_1\cap E_2=\emptyset\]

\emph{Examples:}

\begin{itemize}
\item
  The result of having a misophonia severity of \(1\) and a severity of \(4\).
\item
  The results of obtaining \(12\) and \(5\) by adding the throw of two dice.
\end{itemize}

According to the Kolmogorov properties , only \textbf{mutually exclusive} outcomes can be arranged in \textbf{probability tables}, as in relative frequency tables.

\hypertarget{joint-probabilities}{%
\section{Joint probabilities}\label{joint-probabilities}}

The \textbf{joint probability} of \(A\) and \(B\) is the probability of \(A\) and \(B\). That's \[P( A \cap B)\] or \(P(A,B)\).

To write joint probabilities of non mutually exclusive events (\(A \cap B \neq \emptyset\)) into a probability table, we note that we can always decompose the sample space into \textbf{mutually exclusive} sets involving the intersections:

\(S=\{A\cap B, A \cap B', A'\cap B, A'\cap B'\}\)

\textbf{Let's consider the Ven diagram} for the example where \(A\) is the event that corresponds to drawing a number less than or equal to 3 and \(B\) corresponds to an even number:

\includegraphics{./figures/Venn.JPG}

The \textbf{marginals} of \(A\) and \(B\) are the probability of \(A\) and the probability of \(B\), respectively:

\begin{itemize}
\tightlist
\item
  \(P(A)=P(A\cap B') + P(A \cap B)=2/6+1/6=3/6\)
\item
  \(P(B)=P(A'\cap B) +P(A \cap B)=2/6+1/6=3/6\)
\end{itemize}

We can now write the \textbf{probability table} for the joint probabilities

\begin{longtable}[]{@{}cc@{}}
\toprule
Result & probability \\
\midrule
\endhead
\((A\cap B)\) & \(P(A \cap B)=1/6\) \\
\((A\cap B')\) & \(P(A \cap B')=2/6\) \\
\((A'\cap B)\) & \(P(A' \cap B)=2/6\) \\
\((A'\cap B')\) & \(P(A' \cap B')=1/6\) \\
sum & \(1\) \\
\bottomrule
\end{longtable}

Each result has \(two\) values (one for the feature of type \(A\) and one for type \(B\))

\hypertarget{contingency-table}{%
\section{Contingency table}\label{contingency-table}}

The joint probability table can also be written in a \textbf{contingency table}

\begin{longtable}[]{@{}cccc@{}}
\toprule
& \(B\) & \(B'\) & sum \\
\midrule
\endhead
\(A\) & \(P(A \cap B )\) & \(P(A\cap B' )\) & \(P(A)\) \\
\(A'\) & \(P(A'\cap B )\) & \(P(A'\cap B' )\) & \(P(A')\) \\
sum & \(P(B)\) & \(P(B')\) & 1 \\
\bottomrule
\end{longtable}

Where the marginals are the sums in the margins of the table, for example:

\begin{itemize}
\tightlist
\item
  \(P(A)=P(A \cap B') + P(A \cap B)\)
\item
  \(P(B)=P(A' \cap B) +P(A \cap B)\)
\end{itemize}

In our example, the contingency table is

\begin{longtable}[]{@{}cccc@{}}
\toprule
& \(B\) & \(B'\) & sum \\
\midrule
\endhead
\(A\) & \(1/6\) & \(2/6\) & \(3/6\) \\
\(A'\) & \(2/6\) & \(1/6\) & \(3/6\) \\
sum & \(3/6\) & \(3/6\) & \(1\) \\
\bottomrule
\end{longtable}

\hypertarget{the-addition-rule}{%
\section{The addition rule:}\label{the-addition-rule}}

The addition rule allows us to calculate the probability of \(A\) or \(B\), \(P( A \cup B)\), in terms of the probability of \(A\) and \(B\), \(P(A \cup B )\). We can do this in three equivalent ways:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  Using the marginals and the joint probability
  \[P(A \cup B)=P(A) + P(B) - P(A\cap B)\]
\item
  Using only joint probabilities
  \[P( A \cup B)=P(A \cap B)+P(A\cap B')+P(A'\cap B)\]
\item
  Using the complement of joint probability
  \[P(A \cup B)=1-P(A'\cap B')\]
\end{enumerate}

\textbf{Example (dice)}

Take the events \(A:\{ 1,2,3\}\), rolling a number less than or equal to \(3\), and \(B:\{2,4,6\}\), rolling an even number on the roll of a dice.

Therefore:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  \(P( A \cup B)=P(A) + P(B) - P(A\cap B)=3/6+3/6-1/6=5/6\)
\item
  \(P(A \cup B)=P(A \cap B)+P(A\cap B')+P(A'\cap B)=1/6+2/6+2/6=5/6\)
\item
  \(P(A \cup B)=1-P(A'\cap B')= 1-1/6=5/6\)
\end{enumerate}

In the contingency table \(P( A \cup B)\) corresponds to the cells in bold (method 2 above). That is all cells but 1/6 from the bottom right (method 3).

\begin{longtable}[]{@{}ccc@{}}
\toprule
& \(B\) & \(B'\) \\
\midrule
\endhead
\(A\) & \textbf{1/6} & \textbf{2/6} \\
\(A'\) & \textbf{2/6} & \emph{1/6} \\
\bottomrule
\end{longtable}

\hypertarget{questions-1}{%
\section{Questions}\label{questions-1}}

We collect the age and category of 100 athletes in a competition

\begin{longtable}[]{@{}ccc@{}}
\toprule
& \(age:junior\) & \(age:senior\) \\
\midrule
\endhead
\(category:1st\) & \(14\) & \(12\) \\
\(category:2nd\) & \(21\) & \(18\) \\
\(category:3rd\) & \(22\) & \(13\) \\
\bottomrule
\end{longtable}

\textbf{1)} What is the estimated probability that an athlete is 2nd category and senior?

\textbf{\(\qquad\)a:} \(18/100\); \textbf{\(\qquad\)b:} \(18/43\); \textbf{\(\qquad\)c:} \(18\); \textbf{\(\qquad\)d:} \(18/39\)

\textbf{2)} What is the estimated probability that the athlete is not in the third category and is senior?

\textbf{\(\qquad\)a:} \(35/100\); \textbf{\(\qquad\)b:} \(30/100\); \textbf{\(\qquad\)c:} \(22/100\); \textbf{\(\qquad\)d:} \(13/100\)

\textbf{3)} What is the marginal probability of the third category?

\textbf{\(\qquad\)a:} \(13/100\); \textbf{\(\qquad\)b:} \(35/100\); \textbf{\(\qquad\)c:} \(22/100\); \textbf{\(\qquad\)d:} \(13/22\)

\textbf{4)} What is the marginal probability of being senior?

\textbf{\(\qquad\)a:} \(13/100\); \textbf{\(\qquad\)b:} \(43/100\); \textbf{\(\qquad\)c:} \(43/57\); \textbf{\(\qquad\)d:} \(57/100\)

\textbf{5)} What is the probability of being senior or third category?

\textbf{\(\qquad\)a:} \(65/100\); \textbf{\(\qquad\)b:} \(86/100\); \textbf{\(\qquad\)c:} \(78/100\); \textbf{\(\qquad\)d:} \(13/100\)

\hypertarget{exercises-1}{%
\section{Exercises}\label{exercises-1}}

\hypertarget{classical-probability-exercise-1}{%
\subsubsection{Classical probability: Exercise 1}\label{classical-probability-exercise-1}}

\begin{itemize}
\item
  Write the table of \textbf{joint probability} for the \textbf{results} of rolling two dice; In the rows write the results of the first die and in the columns the results of the second die.
\item
  What is the probability of drawing \((3, 4)\) ? (R:1/36)
\item
  What is the probability of rolling \(3\) and \(4\) with any of the two dice? (R:2/36)
\item
  What is the probability of rolling \(3\) on the first die or \(4\) on the second? (To:11/36)
\item
  What is the probability of rolling \(3\) or \(4\) with any dice? (R:20/36)
\item
  Write the \textbf{probability table} for the result of the \textbf{add} of two dice. Assume that the outcome of each die is \textbf{equally likely}. Verify that it is:
\end{itemize}

\[
P_i=
\begin{cases}
\frac{i-1}{36},& i \in \{2,3,4,5,6, 7\} \\
\frac{13-i}{36},& i \in \{8,9,10,11,12\} \\
\end{cases}
\]

\hypertarget{frequentist-probability-exercise-2}{%
\subsubsection{Frequentist probability: Exercise 2}\label{frequentist-probability-exercise-2}}

The result of a randomized experiment is to measure the severity of misophonia \textbf{and} the state of depression of a patient.

Misophonia

\begin{itemize}
\tightlist
\item
  severity: \(S_M:\{M_ 0,M _1,M_2,M_3,M_4\}\)
\item
  Depression: \(S_ D:\{ D', D\}\))
\end{itemize}

Write the contingency table for the absolute frequencies (\(n_{ M,D }\)) for a study on a total of 123 patients in which it was observed

\begin{itemize}
\tightlist
\item
  100 individuals did not have depression.
\item
  No individual with misophonia 4 and without depression.
\item
  5 individuals with grade 1 misophonia and no depression.
\item
  The same number as the previous case for individuals with depression and without misophonia .
\item
  25 individuals without depression and grade 3 misophonia .
\item
  The number of misophonics without depression for grades 2 and 0 were distributed equally .
\item
  The number of individuals with depression and misophonia increased progressively
  in multiples of three, starting at 0 individuals for grade 1.
\end{itemize}

Answer the following questions:

\begin{itemize}
\tightlist
\item
  How many individuals had misophonia ? (A:83)
\item
  How many individuals had grade 3 misophonia ? (R:31)
\item
  How many individuals had grade 2 misophonia without depression? (R:35)
\end{itemize}

Write down the contingency table for relative frequencies \(f_{ M,D }\). Suppose \(N\) is large and the absolute frequencies \textbf{estimate} the probabilities \(f_{ M,D }=\hat {P}(M \cap D)\). Answer the following questions:

\begin{itemize}
\tightlist
\item
  What is the marginal probability of severity 2 misophonia ? (R: 0.3)
\item
  What is the probability of not being misophonic \textbf{and} not being depressed? (R:0.284)
\item
  What is the probability of being misophonic \textbf{or} depressed? (R: 0.715)
\item
  What is the probability of being misophonic \textbf{and} being depressed? (R: 0.146)
\item
  Describe in spoken language the results with probability 0.
\end{itemize}

\hypertarget{exercise-3}{%
\subsubsection{Exercise 3}\label{exercise-3}}

We have carried out a randomized experiment \(10\) times, which consists of recording the sex and vital status of patients with some type of cancer after 10 years of diagnosis. We got the following results

\begin{verbatim}
##           A     B
## 1     male   dead
## 2     male   dead
## 3     male   dead
## 4   female  alive
## 5     male   dead
## 6   female  alive
## 7   female   dead
## 8   female  alive
## 9     male  alive
## 10    male  alive
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Create the contingency table for the number (\(n_{ i,j }\)) of observations of each result (\(A,B\))
\item
  Create the contingency table for the relative frequency (\(f_{ i,j }\)) of the results
\item
  What is the marginal frequency of being a man? (R/0.6)
\item
  What is the marginal frequency of being alive? (R/0.5)
\item
  What is the frequency of being alive \textbf{or} being a woman? (R/0.6)
\end{itemize}

\hypertarget{theory-exercise-4}{%
\subsubsection{Theory: Exercise 4}\label{theory-exercise-4}}

\begin{itemize}
\item
  From the second form of the addition rule, obtain the first and the third form.
\item
  What is the third form addition rule for the probability of three events \(P(A \cup B \cup C)\)?
\end{itemize}

  \bibliography{book.bib,packages.bib}

\end{document}
