<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Data description | EEBE stats</title>
  <meta name="description" content="EEBE" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Data description | EEBE stats" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="EEBE" />
  <meta name="github-repo" content="alejandro-isglobal/master" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Data description | EEBE stats" />
  
  <meta name="twitter:description" content="EEBE" />
  

<meta name="author" content="Alejandro Caceres" />


<meta name="date" content="2023-09-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="probability.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">EEBE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Objective</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#recommended-reading"><i class="fa fa-check"></i><b>1.1</b> Recommended reading</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-description.html"><a href="data-description.html"><i class="fa fa-check"></i><b>2</b> Data description</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-description.html"><a href="data-description.html#scientific-method"><i class="fa fa-check"></i><b>2.1</b> Scientific method</a></li>
<li class="chapter" data-level="2.2" data-path="data-description.html"><a href="data-description.html#statistics"><i class="fa fa-check"></i><b>2.2</b> Statistics</a></li>
<li class="chapter" data-level="2.3" data-path="data-description.html"><a href="data-description.html#data"><i class="fa fa-check"></i><b>2.3</b> Data</a></li>
<li class="chapter" data-level="2.4" data-path="data-description.html"><a href="data-description.html#result-types"><i class="fa fa-check"></i><b>2.4</b> Result types</a></li>
<li class="chapter" data-level="2.5" data-path="data-description.html"><a href="data-description.html#random-experiments"><i class="fa fa-check"></i><b>2.5</b> Random experiments</a></li>
<li class="chapter" data-level="2.6" data-path="data-description.html"><a href="data-description.html#absolute-frequencies"><i class="fa fa-check"></i><b>2.6</b> Absolute frequencies</a></li>
<li class="chapter" data-level="2.7" data-path="data-description.html"><a href="data-description.html#relative-frequencies"><i class="fa fa-check"></i><b>2.7</b> Relative frequencies</a></li>
<li class="chapter" data-level="2.8" data-path="data-description.html"><a href="data-description.html#bar-chart"><i class="fa fa-check"></i><b>2.8</b> Bar chart</a></li>
<li class="chapter" data-level="2.9" data-path="data-description.html"><a href="data-description.html#pie-chart-pie"><i class="fa fa-check"></i><b>2.9</b> Pie chart (pie)</a></li>
<li class="chapter" data-level="2.10" data-path="data-description.html"><a href="data-description.html#ordinal-categorical-variables"><i class="fa fa-check"></i><b>2.10</b> Ordinal categorical variables</a></li>
<li class="chapter" data-level="2.11" data-path="data-description.html"><a href="data-description.html#accumulated-absolute-and-relative-frequencies"><i class="fa fa-check"></i><b>2.11</b> Accumulated absolute and relative frequencies</a></li>
<li class="chapter" data-level="2.12" data-path="data-description.html"><a href="data-description.html#cumulative-frequency-graph"><i class="fa fa-check"></i><b>2.12</b> Cumulative frequency graph</a></li>
<li class="chapter" data-level="2.13" data-path="data-description.html"><a href="data-description.html#numeric-variables"><i class="fa fa-check"></i><b>2.13</b> Numeric variables</a></li>
<li class="chapter" data-level="2.14" data-path="data-description.html"><a href="data-description.html#transforming-continuous-data"><i class="fa fa-check"></i><b>2.14</b> Transforming continuous data</a></li>
<li class="chapter" data-level="2.15" data-path="data-description.html"><a href="data-description.html#frequency-table-for-a-continuous-variable"><i class="fa fa-check"></i><b>2.15</b> Frequency table for a continuous variable</a></li>
<li class="chapter" data-level="2.16" data-path="data-description.html"><a href="data-description.html#histogram"><i class="fa fa-check"></i><b>2.16</b> Histogram</a></li>
<li class="chapter" data-level="2.17" data-path="data-description.html"><a href="data-description.html#cumulative-frequency-graph-1"><i class="fa fa-check"></i><b>2.17</b> Cumulative frequency graph</a></li>
<li class="chapter" data-level="2.18" data-path="data-description.html"><a href="data-description.html#summary-statistics"><i class="fa fa-check"></i><b>2.18</b> Summary Statistics</a></li>
<li class="chapter" data-level="2.19" data-path="data-description.html"><a href="data-description.html#average-sample-mean"><i class="fa fa-check"></i><b>2.19</b> Average (sample mean)</a></li>
<li class="chapter" data-level="2.20" data-path="data-description.html"><a href="data-description.html#median"><i class="fa fa-check"></i><b>2.20</b> Median</a></li>
<li class="chapter" data-level="2.21" data-path="data-description.html"><a href="data-description.html#dispersion"><i class="fa fa-check"></i><b>2.21</b> Dispersion</a></li>
<li class="chapter" data-level="2.22" data-path="data-description.html"><a href="data-description.html#sample-variance"><i class="fa fa-check"></i><b>2.22</b> Sample variance</a></li>
<li class="chapter" data-level="2.23" data-path="data-description.html"><a href="data-description.html#interquartile-range-iqr"><i class="fa fa-check"></i><b>2.23</b> Interquartile range (IQR)</a></li>
<li class="chapter" data-level="2.24" data-path="data-description.html"><a href="data-description.html#boxplot"><i class="fa fa-check"></i><b>2.24</b> Boxplot</a></li>
<li class="chapter" data-level="2.25" data-path="data-description.html"><a href="data-description.html#questions"><i class="fa fa-check"></i><b>2.25</b> Questions</a></li>
<li class="chapter" data-level="2.26" data-path="data-description.html"><a href="data-description.html#exercises"><i class="fa fa-check"></i><b>2.26</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>3</b> Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probability.html"><a href="probability.html#random-experiments-1"><i class="fa fa-check"></i><b>3.1</b> Random experiments</a></li>
<li class="chapter" data-level="3.2" data-path="probability.html"><a href="probability.html#measurement-probability"><i class="fa fa-check"></i><b>3.2</b> Measurement probability</a></li>
<li class="chapter" data-level="3.3" data-path="probability.html"><a href="probability.html#classical-probability"><i class="fa fa-check"></i><b>3.3</b> Classical probability</a></li>
<li class="chapter" data-level="3.4" data-path="probability.html"><a href="probability.html#relative-frequencies-1"><i class="fa fa-check"></i><b>3.4</b> Relative frequencies</a></li>
<li class="chapter" data-level="3.5" data-path="probability.html"><a href="probability.html#relative-frequencies-at-infinity"><i class="fa fa-check"></i><b>3.5</b> Relative frequencies at infinity</a></li>
<li class="chapter" data-level="3.6" data-path="probability.html"><a href="probability.html#frequentist-probability"><i class="fa fa-check"></i><b>3.6</b> Frequentist probability</a></li>
<li class="chapter" data-level="3.7" data-path="probability.html"><a href="probability.html#classical-and-frequentist-probabilities"><i class="fa fa-check"></i><b>3.7</b> Classical and frequentist probabilities</a></li>
<li class="chapter" data-level="3.8" data-path="probability.html"><a href="probability.html#definition-of-probability"><i class="fa fa-check"></i><b>3.8</b> Definition of probability</a></li>
<li class="chapter" data-level="3.9" data-path="probability.html"><a href="probability.html#probabilities-table"><i class="fa fa-check"></i><b>3.9</b> Probabilities Table</a></li>
<li class="chapter" data-level="3.10" data-path="probability.html"><a href="probability.html#sample-space"><i class="fa fa-check"></i><b>3.10</b> Sample space</a></li>
<li class="chapter" data-level="3.11" data-path="probability.html"><a href="probability.html#events"><i class="fa fa-check"></i><b>3.11</b> Events</a></li>
<li class="chapter" data-level="3.12" data-path="probability.html"><a href="probability.html#algebra-of-events"><i class="fa fa-check"></i><b>3.12</b> Algebra of events</a></li>
<li class="chapter" data-level="3.13" data-path="probability.html"><a href="probability.html#mutually-exclusive-results"><i class="fa fa-check"></i><b>3.13</b> Mutually exclusive results</a></li>
<li class="chapter" data-level="3.14" data-path="probability.html"><a href="probability.html#joint-probabilities"><i class="fa fa-check"></i><b>3.14</b> Joint probabilities</a></li>
<li class="chapter" data-level="3.15" data-path="probability.html"><a href="probability.html#contingency-table"><i class="fa fa-check"></i><b>3.15</b> Contingency table</a></li>
<li class="chapter" data-level="3.16" data-path="probability.html"><a href="probability.html#the-addition-rule"><i class="fa fa-check"></i><b>3.16</b> The addition rule:</a></li>
<li class="chapter" data-level="3.17" data-path="probability.html"><a href="probability.html#questions-1"><i class="fa fa-check"></i><b>3.17</b> Questions</a></li>
<li class="chapter" data-level="3.18" data-path="probability.html"><a href="probability.html#exercises-1"><i class="fa fa-check"></i><b>3.18</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">EEBE stats</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-description" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Data description<a href="data-description.html#data-description" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we will introduce tools for describing data.</p>
<p>We will do so using tables, figures, and descriptive statistics of central tendency and dispersion.</p>
<p>We will also introduce key concepts in statistics such as randomized experiments, observations, outcomes, and absolute and relative frequencies.</p>
<div id="scientific-method" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Scientific method<a href="data-description.html#scientific-method" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the goals of the scientific method is to provide a framework for solving problems that arise in the study of natural phenomena or in the design of new technologies.</p>
<p>Modern humans have developed a <strong>method</strong> over thousands of years that is still in development.</p>
<p>The method has three main human activities:</p>
<ul>
<li><em>Observation</em> characterized by the acquisition of <strong>data</strong></li>
<li><em>Reason</em> characterized by the development of mathematical <strong>models</strong></li>
<li><em>Action</em> characterized by the development of new <strong>experiments</strong> (technology)</li>
</ul>
<p>Their complex interaction and results are the basis of <em>scientific activity</em>.</p>
<p><img src="figures/stats.JPG" /></p>
</div>
<div id="statistics" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Statistics<a href="data-description.html#statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Statistics deals with the interaction between <em>models</em> and <em>data</em> (the bottom part of the figure).</p>
<p>The statistical questions are:</p>
<ul>
<li>What is the best model for my data (inference)?</li>
<li>What are the data that a certain model (prediction) would produce?</li>
</ul>
</div>
<div id="data" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Data<a href="data-description.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The data is presented in the form of observations.</p>
<p>An <strong>Observation</strong> or <strong>Realization</strong> is the acquisition of a number or characteristic of an experiment.</p>
<p>For example, let’s take the series of numbers produced by repeating an experiment (1: success, 0: failure).</p>
<p>… 1 0 0 1 0 <strong>1</strong> 0 1 1 …</p>
<p>The number in bold is <strong>an observation</strong> in a repeat of the experiment</p>
<p>An <strong>outcome</strong> is a <strong>possible</strong> observation that is the result of an experiment.</p>
<p><strong>1</strong> is one result, <strong>0</strong> is the other result of the experiment.</p>
<p>Remember that the observation is <strong>concrete</strong> is the number you get one day in the laboratory. The <strong>abstract</strong> result is one of the characteristics of the type of experiment you are running.</p>
</div>
<div id="result-types" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Result types<a href="data-description.html#result-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In statistics we are mainly interested in two types of results.</p>
<ul>
<li><p><strong>Categorical</strong>: If the result of an experiment is a quality. They can be nominal (binary: yes, no; multiple: colors) or ordinal when the qualities can be ranked (severity of a disease).</p></li>
<li><p><strong>Numeric</strong>: If the result of an experiment is a number. The number can be discrete (number of emails received in an hour, number of leukocytes in the blood) or continuous (battery charge status, engine temperature).</p></li>
</ul>
</div>
<div id="random-experiments" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Random experiments<a href="data-description.html#random-experiments" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It can be said that the subject of study of statistics is random experiments, the means by which we produce data.</p>
<p><strong>Definition:</strong></p>
<p>A <strong>random experiment</strong> is an experiment that gives different results when repeated in the same way.</p>
<p>Randomized experiments are of different types, depending on how they are conducted:</p>
<ul>
<li>on the same object (person): temperature, sugar levels.
different objects but of the same size: the weight of an animal.</li>
<li>about events: the number of hurricanes per year.</li>
</ul>
</div>
<div id="absolute-frequencies" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Absolute frequencies<a href="data-description.html#absolute-frequencies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we repeat a randomized experiment with <strong>categorical</strong> results, we record a list of results.</p>
<p>We summarize observations by counting how many times we saw a particular result.</p>
<p><strong>Absolute frecuency</strong>:</p>
<p><span class="math display">\[ n_i \]</span></p>
<p>is the number of times we observe the result <span class="math inline">\(i\)</span>.</p>
<div style="page-break-after: always;"></div>
<p><strong>Example (leukocytes)</strong></p>
<p>Let’s take a leukocyte from <strong>a</strong> donor and write down its type. Let’s repeat the experiment <span class="math inline">\(N=119\)</span> times.</p>
<pre><code>(T cell, T cell, Neutrophil, ..., B cell)</code></pre>
<p>The second <strong>T cell</strong> in bold is the second observation. The last <strong>B cell</strong> is observation number 119.</p>
<p>We can list the <strong>results</strong> (categories) in a <strong>frequency table</strong>:</p>
<pre><code>##      outcome ni
## 1     T Cell 34
## 2     B cell 50
## 3   basophil 20
## 4   Monocyte  5
## 5 Neutrophil 10</code></pre>
<p>From the table, we can say that, for example, <span class="math inline">\(n_1=34\)</span> is the total number of T cells observed in the repeat experiment. We also note that the total number of repetitions <span class="math inline">\(N=\sum_i n_i = 119\)</span>.</p>
</div>
<div id="relative-frequencies" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Relative frequencies<a href="data-description.html#relative-frequencies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can also summarize observations by calculating the <strong>proportion</strong> of how many times we saw a particular result.</p>
<p><span class="math display">\[ f_i = n_i /N\]</span> where <span class="math inline">\(N\)</span> is the total number of observations</p>
<p>In our example, <span class="math inline">\(n_1=34\)</span> T cells were recorded, so we asked about the proportion of T cells out of the total <span class="math inline">\(119\)</span>. We can add these proportions <span class="math inline">\(f_i\)</span> in the frequency table.</p>
<pre><code>##      outcome ni         fi
## 1     T Cell 34 0.28571429
## 2     B cell 50 0.42016807
## 3   basophil 20 0.16806723
## 4   Monocyte  5 0.04201681
## 5 Neutrophil 10 0.08403361</code></pre>
<p>Relative frequencies are <strong>fundamental</strong> in statistics. They give the proportion of one result in relation to the other results. Later we will understand them as the observations of probabilities.</p>
<p>For absolute and relative frequencies we have the properties</p>
<ul>
<li><span class="math inline">\(\sum_{i=1..M} n_i = N\)</span></li>
<li><span class="math inline">\(\sum_{i=1..M} f_i = 1\)</span></li>
</ul>
<p>where <span class="math inline">\(M\)</span> is the number of results.</p>
</div>
<div id="bar-chart" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Bar chart<a href="data-description.html#bar-chart" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we have a lot of results and want to see which ones are most likely, we can use a bar chart that is a number of <span class="math inline">\(n_i\)</span> Vs the results.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="pie-chart-pie" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Pie chart (pie)<a href="data-description.html#pie-chart-pie" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can also visualize the relative frequencies with a pie chart.</p>
<p>The area of the circle represents 100% of the observations (proportion = 1) and the sections the relative frequencies of each result.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="ordinal-categorical-variables" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> Ordinal categorical variables<a href="data-description.html#ordinal-categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The leukocyte type in the above examples is a <strong>categorical</strong> nominal variable. Each observation belongs to a category (quality). The categories do not always have a certain order .</p>
<p>Sometimes <strong>categorical</strong> variables can be <strong>sorted</strong> when they meet a natural ranking. This allows you to compute <strong>cumulative frequencies</strong>.</p>
<div style="page-break-after: always;"></div>
<p><strong>Example (Misophonia)</strong></p>
<p>This is a clinical study on 123 patients who were examined for their degree of misophonia. Misophnia is uncontrolled anxiety/anger produced by certain sounds .</p>
<p>Each patient was evaluated with a questionnaire (AMISO) and they were classified into 4 different groups according to severity.</p>
<p>The results of the study are</p>
<pre><code>##   [1] 4 2 0 3 0 0 2 3 0 3 0 2 2 0 2 0 0 3 3 0 3 3 2 0 0 0 4 2 2 0 2 0 0 0 3 0 2
##  [38] 3 2 2 0 2 3 0 0 2 2 3 3 0 0 4 3 3 2 0 2 0 0 0 2 2 0 0 2 3 0 1 3 2 4 3 2 3
##  [75] 0 2 3 2 4 1 2 0 2 0 2 0 2 2 4 3 0 3 0 0 0 2 2 1 3 0 0 3 2 1 3 0 4 4 2 3 3
## [112] 3 0 3 2 1 2 3 3 4 2 3 2</code></pre>
<p>Each observation is the result of a randomized experiment: measurement of the level of misophonia in a patient. This data series can be summarized in terms of the results in the frequency table</p>
<pre><code>##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073</code></pre>
</div>
<div id="accumulated-absolute-and-relative-frequencies" class="section level2 hasAnchor" number="2.11">
<h2><span class="header-section-number">2.11</span> Accumulated absolute and relative frequencies<a href="data-description.html#accumulated-absolute-and-relative-frequencies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Misophonia severity is <strong>categorical</strong> <strong>ordinal</strong> because its results can be ordered relative to its degree.</p>
<p>When the results can be ordered, it is useful to ask how many observations were obtained up to a given result. We call this number the <strong>absolute cumulative frequency</strong> up to the result <span class="math inline">\(i\)</span>:
<span class="math display">\[N_i =\sum_{k= 1..i } n_k\]</span>
It is also useful for calculating the <strong>proportion</strong> of observations up to a given result.</p>
<p><span class="math display">\[F_i =\sum_{k= 1..i } f_k\]</span></p>
<p>We can add these frequencies in the <strong>frequency table</strong></p>
<pre><code>##   outcome ni         fi  Ni        Fi
## 0       0 41 0.33333333  41 0.3333333
## 1       1  5 0.04065041  46 0.3739837
## 2       2 37 0.30081301  83 0.6747967
## 3       3 31 0.25203252 114 0.9268293
## 4       4  9 0.07317073 123 1.0000000</code></pre>
<p>Therefore, <strong>67%</strong> of patients had misophonia up to severity <strong>2</strong> and <strong>37%</strong> of patients had severity less than or equal to <strong>1</strong>.</p>
<p><br>
<br>
<br></p>
</div>
<div id="cumulative-frequency-graph" class="section level2 hasAnchor" number="2.12">
<h2><span class="header-section-number">2.12</span> Cumulative frequency graph<a href="data-description.html#cumulative-frequency-graph" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><span class="math inline">\(F_i\)</span> is an important quantity because it allows us to define the accumulation of probabilities down to intermediate levels.</p>
<p>The probability of an intermediate level <span class="math inline">\(x\)</span> (<span class="math inline">\(i\leq x&lt; i+1\)</span>) is just the accumulation up to the lower level <span class="math inline">\(F_x = F_i\)</span>.</p>
<p><span class="math inline">\(F_x\)</span> is therefore a function on a <strong>continuous</strong> range of values. We can draw it with respect to the results.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Therefore, we can say that <strong>67%</strong> of the patients had misophonia up to severity <span class="math inline">\(2.3\)</span>, although <span class="math inline">\(2.3\)</span> is not an observed outcome.</p>
</div>
<div id="numeric-variables" class="section level2 hasAnchor" number="2.13">
<h2><span class="header-section-number">2.13</span> Numeric variables<a href="data-description.html#numeric-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The result of a random experiment can produce a number. If the number is <strong>discrete</strong>, we can generate a frequency table, with absolute, relative, and cumulative frequencies, and illustrate them with bar, pie, and cumulative charts.</p>
<p>When the number is <strong>continuous</strong> the frequencies are not useful, we are most likely to observe or not observe a particular continuous number.</p>
<p><strong>Example (misophonia)</strong></p>
<p>The researchers wondered if the convexity of the jaw would affect the severity of misophonia. The scientific hypothesis is that the angle of convexity of the jaw can influence hearing and its sensitivity. These are the mandibular convexity results (degrees) for each patient:</p>
<pre><code>##   [1]  7.97 18.23 12.27  7.81  9.81 13.50 19.30  7.70 12.30  7.90 12.60 19.00
##  [13]  7.27 14.00  5.40  8.00 11.20  7.75  7.94 16.69  7.62  7.02  7.00 19.20
##  [25]  7.96 14.70  7.24  7.80  7.90  4.70  4.40 14.00 14.40 16.00  1.40  9.76
##  [37]  7.90  7.90  7.40  6.30  7.76  7.30  7.00 11.23 16.00  7.90  7.29  6.91
##  [49]  7.10 13.40 11.60 -1.00  6.00  7.82  4.80 11.00  9.00 11.50 16.00 15.00
##  [61]  1.40 16.80  7.70 16.14  7.12 -1.00 17.00  9.26 18.70  3.40 21.30  7.50
##  [73]  6.03  7.50 19.00 19.01  8.10  7.80  6.10 15.26  7.95 18.00  4.60 15.00
##  [85]  7.50  8.00 16.80  8.54  7.00 18.30  7.80 16.00 14.00 12.30 11.40  8.50
##  [97]  7.00  7.96 17.60 10.00  3.50  6.70 17.00 20.26  6.64  1.80  7.02  2.46
## [109] 19.00 17.86  6.10  6.64 12.00  6.60  8.70 14.05  7.20 19.70  7.70  6.02
## [121]  2.50 19.00  6.80</code></pre>
</div>
<div id="transforming-continuous-data" class="section level2 hasAnchor" number="2.14">
<h2><span class="header-section-number">2.14</span> Transforming continuous data<a href="data-description.html#transforming-continuous-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Since continuous outcomes cannot be counted (informatively), we transform them into ordered categorical variables.</p>
<ol style="list-style-type: decimal">
<li>First we cover the range of observations in regular intervals of the same size (bins)</li>
</ol>
<pre><code>## [1] &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Then we map each observation to its interval: creating a categorical variable <strong>ordered</strong>; in this case with 5 possible outcomes</li>
</ol>
<pre><code>##   [1] &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot; 
##   [6] &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot; 
##  [11] &quot;(12.4,16.8]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [16] &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot; 
##  [21] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot; 
##  [26] &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [31] &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;[-1.02,3.46]&quot;
##  [36] &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [41] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot; 
##  [46] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot; 
##  [51] &quot;(7.92,12.4]&quot;  &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
##  [56] &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot; 
##  [61] &quot;[-1.02,3.46]&quot; &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [66] &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;[-1.02,3.46]&quot;
##  [71] &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot; 
##  [76] &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot; 
##  [81] &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot; 
##  [86] &quot;(7.92,12.4]&quot;  &quot;(12.4,16.8]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot; 
##  [91] &quot;(3.46,7.92]&quot;  &quot;(12.4,16.8]&quot;  &quot;(12.4,16.8]&quot;  &quot;(7.92,12.4]&quot;  &quot;(7.92,12.4]&quot; 
##  [96] &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(16.8,21.3]&quot;  &quot;(7.92,12.4]&quot; 
## [101] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot; 
## [106] &quot;[-1.02,3.46]&quot; &quot;(3.46,7.92]&quot;  &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(16.8,21.3]&quot; 
## [111] &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot;  &quot;(3.46,7.92]&quot;  &quot;(7.92,12.4]&quot; 
## [116] &quot;(12.4,16.8]&quot;  &quot;(3.46,7.92]&quot;  &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;  &quot;(3.46,7.92]&quot; 
## [121] &quot;[-1.02,3.46]&quot; &quot;(16.8,21.3]&quot;  &quot;(3.46,7.92]&quot;</code></pre>
<p>Therefore, instead of saying that the first patient had an angle of convexity of <span class="math inline">\(7.97\)</span>, we say that his angle was between the interval (or <strong>bin</strong>) <span class="math inline">\((7.92,12.4]\)</span>.</p>
<p>No other patients had an angle of <span class="math inline">\(7.97\)</span>, but many had angles between <span class="math inline">\((7.92,12.4]\)</span>.</p>
</div>
<div id="frequency-table-for-a-continuous-variable" class="section level2 hasAnchor" number="2.15">
<h2><span class="header-section-number">2.15</span> Frequency table for a continuous variable<a href="data-description.html#frequency-table-for-a-continuous-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For a given regular partition of the interval of results into intervals, we can produce a frequency table as before</p>
<pre><code>##        outcome ni         fi  Ni         Fi
## 1 [-1.02,3.46]  8 0.06504065   8 0.06504065
## 2  (3.46,7.92] 51 0.41463415  59 0.47967480
## 3  (7.92,12.4] 26 0.21138211  85 0.69105691
## 4  (12.4,16.8] 20 0.16260163 105 0.85365854
## 5  (16.8,21.3] 18 0.14634146 123 1.00000000</code></pre>
</div>
<div id="histogram" class="section level2 hasAnchor" number="2.16">
<h2><span class="header-section-number">2.16</span> Histogram<a href="data-description.html#histogram" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The histogram is the graph of <span class="math inline">\(n_i\)</span> or <span class="math inline">\(f_i\)</span> Vs the results in intervals (bins). The histogram depends on the size of the bins .</p>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div style="page-break-after: always;"></div>
<p>This is a histogram with 20 bins .</p>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>We see that most people have angles within <span class="math inline">\((7, 8]\)</span></p>
</div>
<div id="cumulative-frequency-graph-1" class="section level2 hasAnchor" number="2.17">
<h2><span class="header-section-number">2.17</span> Cumulative frequency graph<a href="data-description.html#cumulative-frequency-graph-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can also plot <span class="math inline">\(F_x\)</span> against the results. Since <span class="math inline">\(F_x\)</span> is of continuous range, we can order the observations (<span class="math inline">\(x_1 &lt;... x_j &lt; x_{j+1} &lt; x_n\)</span>) and therefore</p>
<p><span class="math display">\[F_x = \frac{k}{ n}\]</span></p>
<p>for <span class="math inline">\(x_{k} \leq x &lt; x_{k+ 1}\)</span> .</p>
<p><span class="math inline">\(F_x\)</span> is known as the <strong>distribution</strong> of the data. <span class="math inline">\(F_x\)</span> does not depend on the size of the bin. However, its <strong>resolution</strong> depends on the amount of data.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="summary-statistics" class="section level2 hasAnchor" number="2.18">
<h2><span class="header-section-number">2.18</span> Summary Statistics<a href="data-description.html#summary-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Summary statistics are numbers calculated from the data that tell us important characteristics of the numerical variables (discrete or continuous).</p>
<p>For example, we have statistics that describe extreme values:</p>
<ul>
<li><strong>minimum</strong>: the minimum result observed</li>
<li><strong>maximum</strong>: the maximum result observed</li>
</ul>
</div>
<div id="average-sample-mean" class="section level2 hasAnchor" number="2.19">
<h2><span class="header-section-number">2.19</span> Average (sample mean)<a href="data-description.html#average-sample-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>An important statistic that describes the central value of the results (where to expect most observations) is the <strong>average</strong></p>
<p><span class="math display">\[\bar{x}=\frac{1}{N} \sum_{j= 1..N } x_j \]</span></p>
<p>where <span class="math inline">\(x_j\)</span> is the <strong>observation</strong> <span class="math inline">\(j\)</span> out of a total of <span class="math inline">\(N\)</span>.</p>
<p><strong>Example (Misophonia)</strong></p>
<p>The average convexity can be calculated directly from the <strong>observations</strong> in the usual way</p>
<p><span class="math inline">\(\bar{x}= \frac{1}{ N}\sum_j x_j\)</span></p>
<p></br>
<span class="math inline">\(= \frac{1}{ N}( 7.97 + 18.23 + 12.27... + 6.80) = 10.19894\)</span></p>
<p>For <strong>categorically ordered</strong> variables, we can <strong>also</strong> use the relative frequencies to calculate the average</p>
<p><br>
<span class="math inline">\(\bar{x}=\frac{1}{ N}\sum_{i=1...N} x_j =\frac{1}{N}\sum_{i=1...M} x_i n_ {i}=\)</span>
<br>
<span class="math display">\[\sum_{i=1...M} x_i f_{i}\]</span></p>
<p>where we went from adding <span class="math inline">\(N\)</span> <strong>observations</strong> to adding <span class="math inline">\(M\)</span> <strong>results</strong>.</p>
<p>The form <span class="math inline">\(\bar{x}= \sum_{i = 1...M} x_i f_i\)</span> shows that the average is the <strong>center of gravity</strong> of the results. As if each result had a mass density given by <span class="math inline">\(f_i\)</span>.</p>
<p><strong>Example (Misophonia)</strong></p>
<p>The average <strong>severity</strong> of misophonia in the study can be calculated from the relative frequencies of the <strong>outcomes</strong></p>
<pre><code>##   outcome ni         fi
## 1       0 41 0.33333333
## 2       1  5 0.04065041
## 3       2 37 0.30081301
## 4       3 31 0.25203252
## 5       4  9 0.07317073</code></pre>
<p><br>
<span class="math inline">\(\bar{x}=0*f_ {0}+ 1*f_{1}+2*f_{2}+3*f_{3}+4*f_{4}=1.691057\)</span></p>
<p>The average is also the center of gravity for continuous variables. That is the point where the relative frequencies balance.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="median" class="section level2 hasAnchor" number="2.20">
<h2><span class="header-section-number">2.20</span> Median<a href="data-description.html#median" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Another measure of centrality is the median. The median <span class="math inline">\(x_m\)</span>, or <span class="math inline">\(q_{0.5}\)</span>, is the value below which we find half of the observations. When we order the observations <span class="math inline">\(x_1 &lt;... x_j &lt; x_{j+1} &lt; x_N\)</span>, we count them until we find half of them. Therefore, <span class="math inline">\(x_m\)</span> is the observation such that <span class="math inline">\(m\)</span> satisfies</p>
<p><span class="math display">\[\sum_{i\leq m} 1 = \frac{N}{2}\]</span>
<strong>Example (Misophonia)</strong></p>
<p>If we order the angles of convexity, we see that <span class="math inline">\(62\)</span> observations (individuals) (<span class="math inline">\(N/2 \sim 123/2\)</span>) are below <span class="math inline">\(7.96\)</span>. The <strong>median convexity</strong> is therefore <span class="math inline">\(q_{0.5}= x_{62}=7.96\)</span></p>
<pre><code>##  [1] -1.00 -1.00  1.40  1.40  1.80  2.46  2.50  3.40  3.50  4.40  4.60  4.70
## [13]  4.80  5.40  6.00  6.02  6.03  6.10  6.10  6.30  6.60  6.64  6.64  6.70
## [25]  6.80  6.91  7.00  7.00  7.00  7.00  7.02  7.02  7.10  7.12  7.20  7.24
## [37]  7.27  7.29  7.30  7.40  7.50  7.50  7.50  7.62  7.70  7.70  7.70  7.75
## [49]  7.76  7.80  7.80  7.80  7.81  7.82  7.90  7.90  7.90  7.90  7.90  7.94
## [61]  7.95  7.96</code></pre>
<pre><code>##  [1]  7.96  7.97  8.00  8.00  8.10  8.50  8.54  8.70  9.00  9.26  9.76  9.81
## [13] 10.00 11.00 11.20 11.23 11.40 11.50 11.60 12.00 12.27 12.30 12.30 12.60
## [25] 13.40 13.50 14.00 14.00 14.00 14.05 14.40 14.70 15.00 15.00 15.26 16.00
## [37] 16.00 16.00 16.00 16.14 16.69 16.80 16.80 17.00 17.00 17.60 17.86 18.00
## [49] 18.23 18.30 18.70 19.00 19.00 19.00 19.00 19.01 19.20 19.30 19.70 20.26
## [61] 21.30</code></pre>
<p>We cut the data at</p>
<pre><code>## [1] 7.96</code></pre>
<p>to split them in half.</p>
<div style="page-break-after: always;"></div>
<p>In terms of frequencies, <span class="math inline">\(q_{0.5}\)</span> makes the cumulative frequency <span class="math inline">\(F_x\)</span> equal to <span class="math inline">\(0.5\)</span></p>
<p><span class="math display">\[\sum_{i = 0, ... m} f_i =F_{q_{0.5}}=0.5\]</span>
that is</p>
<p><span class="math display">\[q_{ 0.5}= F^{-1}(0.5)\]</span></p>
<p>This last equation means that, in the distribution graph, the median <span class="math inline">\(q_{ 0.5}\)</span> is the value of <span class="math inline">\(x\)</span> at which we have climbed half of the total height of <span class="math inline">\(F\)</span>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>The mean and median are not always the same.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="dispersion" class="section level2 hasAnchor" number="2.21">
<h2><span class="header-section-number">2.21</span> Dispersion<a href="data-description.html#dispersion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Other important summary statistics for observations are the <strong>spread</strong> statistics.</p>
<p>Many experiments may share their mean, but differ in how <strong>sparse</strong> the values are.</p>
<p>The dispersion of the observations is a measure of the <strong>noise</strong>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
</div>
<div id="sample-variance" class="section level2 hasAnchor" number="2.22">
<h2><span class="header-section-number">2.22</span> Sample variance<a href="data-description.html#sample-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The dispersion about the mean is measured by the sample variance</p>
<p><span class="math display">\[s^2=\frac{ 1}{ N-1} \sum_{j=1..N} ( x_j -\bar{x})^2\]</span></p>
<p>This number measures the average squared distance of the <strong>observations</strong> from the average. The reason for <span class="math inline">\(N-1\)</span> will be explained when we talk about inference, when we study the spread of <span class="math inline">\(\bar{x}\)</span>, as well as the spread of the observations.</p>
<p>In terms of the frequencies of the variables that are <strong>categorical and ordered</strong>, we can <strong>also</strong> calculate the sample variance as</p>
<p><span class="math display">\[s^2=\frac{N}{N-1} \sum_{i=1... M} (x_i -\bar{x})^2 f_i\]</span></p>
<p><span class="math inline">\(s^2\)</span> can be considered as the <strong>moment of inertia</strong> of the observations.</p>
<p>The square root of the sample variance, <span class="math inline">\(s\)</span>, is called <strong>standard deviation</strong> of the sample.</p>
<p><strong>Example (Misophonia)</strong></p>
<p>The standard deviation of the angle of convexity is</p>
<p><span class="math inline">\(s= [\frac{ 1}{123-1}((7.97-10.19894)^2+ (18.23-10.19894)^2\)</span>
<span class="math display">\[+ (12.27-10.19894 )^ 2 + ...)]^{1/2} = 5.086707\]</span></p>
<p>The jaw convexity deviates from its mean by <span class="math inline">\(5.086707\)</span>.</p>
</div>
<div id="interquartile-range-iqr" class="section level2 hasAnchor" number="2.23">
<h2><span class="header-section-number">2.23</span> Interquartile range (IQR)<a href="data-description.html#interquartile-range-iqr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The spread of the data can also be measured with respect to the median using the <strong>interquartile range</strong>:</p>
<ol style="list-style-type: decimal">
<li>We define the <strong>first</strong> quartile as the value <span class="math inline">\(x_m\)</span> that makes the cumulative frequency <span class="math inline">\(F_{q_{0.25}}\)</span> equal to <span class="math inline">\(0.25\)</span> (or the value of <span class="math inline">\(x\)</span> where we have accumulated a quarter of the observations, or the value that splits the first quarter of the observations)</li>
</ol>
<p><span class="math display">\[q_{0.25}=F^{-1}(0.25)\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>We define the <strong>third</strong> quartile as the value <span class="math inline">\(x_m\)</span> that makes the cumulative frequency <span class="math inline">\(F_{q_{0.75}}\)</span> equal to <span class="math inline">\(0.75\)</span> (or the value of <span class="math inline">\(x\)</span> where we have accumulated three quarters of observations)</li>
</ol>
<p><span class="math display">\[q_{0.75}=F^{-1}(0.75)\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>The <strong>interquartile range</strong> (IQR) is <span class="math display">\[IQR=q_{0.75} - q_{0.25}\]</span></li>
</ol>
<p>This is the distance between the third and first quartiles and captures the central <span class="math inline">\(50\%\)</span> of the observations</p>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="boxplot" class="section level2 hasAnchor" number="2.24">
<h2><span class="header-section-number">2.24</span> Boxplot<a href="data-description.html#boxplot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The interquartile range, median, and <span class="math inline">\(5\%\)</span> and <span class="math inline">\(95\%\)</span> of the data can be displayed in a <strong>box plot</strong>.</p>
<p>In the boxplot, the values of the results are on the y-axis. The IQR is the box, the median is the middle line, and the whiskers mark the <span class="math inline">\(5\%\)</span> and <span class="math inline">\(95\%\)</span> of the data.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
<div id="questions" class="section level2 hasAnchor" number="2.25">
<h2><span class="header-section-number">2.25</span> Questions<a href="data-description.html#questions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>1)</strong> In the following boxplot, the first quartile and second quartile of the data are:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\((-1.00, 21.30)\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\((-1.00, 7.02)\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\((7.02, 7.96)\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\((7.02, 14.22)\)</span></p>
<p><img src="figures/box.png" style="width:30%" align="center"></br></p>
<p><strong>2)</strong> The main disadvantage of a histogram is that:</p>
<p><strong><span class="math inline">\(\qquad\)</span> a :</strong> Depends on the size of the bin ; <strong><span class="math inline">\(\qquad\)</span>b :</strong> Cannot be used for categorical variables;</p>
<p><strong><span class="math inline">\(\qquad\)</span> c :</strong> Cannot be used when the bin size is small;
<strong><span class="math inline">\(\qquad\)</span> d :</strong> Used only for relative frequencies;</p>
<p><strong>3)</strong> If the relative cumulative frequencies of a random experiment with outcomes <span class="math inline">\(\{1,2,3,4\}\)</span> are: <span class="math inline">\(F(1)=0.15, \qquad F(2)=0.60, \qquad F(3)=0.85, \qquad F(4)=1\)</span>.</p>
<p>Then the relative frequency for the outcome <span class="math inline">\(3\)</span> is</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\(0.15\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\(0.85\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\(0.45\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\(0.25\)</span></p>
<p><strong>4)</strong> In a sample of size <span class="math inline">\(10\)</span> from a random experiment we obtained the following data:</p>
<p><span class="math inline">\(8, \qquad 3, \qquad 3, \qquad 7, \qquad 3, \qquad 6, \qquad 5, \qquad 10, \qquad 3, \qquad 8\)</span>.</p>
<p>The first quartile of the data is:</p>
<p><strong><span class="math inline">\(\qquad\)</span>a:</strong> <span class="math inline">\(3.5\)</span>; <strong><span class="math inline">\(\qquad\)</span>b:</strong> <span class="math inline">\(4\)</span>; <strong><span class="math inline">\(\qquad\)</span>c:</strong> <span class="math inline">\(5\)</span>; <strong><span class="math inline">\(\qquad\)</span>d:</strong> <span class="math inline">\(3\)</span></p>
<p><strong>5)</strong> Imagine that we collect data for two quantities that are not mutually exclusive, for example, the gender and nationality of passengers on a flight. If we want to make a single pie chart for the data, which of these statements is true?</p>
<p><strong><span class="math inline">\(\qquad\)</span>a :</strong> We can <strong>only</strong> make a nationality pie chart because it has more than two possible outcomes;</p>
<p><strong><span class="math inline">\(\qquad\)</span>b :</strong> We can make a pie graph for a new variable marking gender <strong>and</strong> nationality;</p>
<p><strong><span class="math inline">\(\qquad\)</span>c :</strong> We can make a pie chart for the variable sex <strong>or</strong> the variable nationality;</p>
<p><strong><span class="math inline">\(\qquad\)</span>d :</strong> We can only choose <strong>whether</strong> to make a pie chart for gender <strong>or</strong> a pie chart for nationality.</p>
</div>
<div id="exercises" class="section level2 hasAnchor" number="2.26">
<h2><span class="header-section-number">2.26</span> Exercises<a href="data-description.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-1" class="section level4 hasAnchor" number="2.26.0.1">
<h4><span class="header-section-number">2.26.0.1</span> Exercise 1<a href="data-description.html#exercise-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have performed an experiment 8 times with the following results</p>
<pre><code>## [1]  3  3 10  2  6 11  5  4</code></pre>
<p>Answer the following questions:</p>
<ul>
<li>Calculate the relative frequencies of each result.</li>
<li>Calculate the cumulative frequencies of each result.</li>
<li>What is the average of the observations?</li>
<li>What is the median?</li>
<li>What is the third quartile?</li>
<li>What is the first quartile?</li>
</ul>
</div>
<div id="exercise-2" class="section level4 hasAnchor" number="2.26.0.2">
<h4><span class="header-section-number">2.26.0.2</span> Exercise 2<a href="data-description.html#exercise-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have performed an experiment 10 times with the following results</p>
<pre><code>##  [1] 2.875775 7.883051 4.089769 8.830174 9.404673 0.455565 5.281055 8.924190
##  [9] 5.514350 4.566147</code></pre>
<p>Consider 10 bins of size 1: [0,1], (1,2] …( 9,10).</p>
<p>Answer the following questions:</p>
<ul>
<li><p>Calculate the relative frequencies of each result and draw the histogram</p></li>
<li><p>Calculate the cumulative frequencies of each result and draw the cumulative graph.</p></li>
<li><p>Draw a box plot .</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-DataDescription.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
